/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.account.model.db.tables;


import io.zeitwert.fm.account.model.db.Keys;
import io.zeitwert.fm.account.model.db.Public;
import io.zeitwert.fm.account.model.db.tables.ObjAccount.ObjAccountPath;
import io.zeitwert.fm.account.model.db.tables.records.CodeClientSegmentRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeClientSegment extends TableImpl<CodeClientSegmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.code_client_segment</code>
     */
    public static final CodeClientSegment CODE_CLIENT_SEGMENT = new CodeClientSegment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeClientSegmentRecord> getRecordType() {
        return CodeClientSegmentRecord.class;
    }

    /**
     * The column <code>public.code_client_segment.id</code>.
     */
    public final TableField<CodeClientSegmentRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.code_client_segment.name</code>.
     */
    public final TableField<CodeClientSegmentRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private CodeClientSegment(Name alias, Table<CodeClientSegmentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CodeClientSegment(Name alias, Table<CodeClientSegmentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.code_client_segment</code> table reference
     */
    public CodeClientSegment(String alias) {
        this(DSL.name(alias), CODE_CLIENT_SEGMENT);
    }

    /**
     * Create an aliased <code>public.code_client_segment</code> table reference
     */
    public CodeClientSegment(Name alias) {
        this(alias, CODE_CLIENT_SEGMENT);
    }

    /**
     * Create a <code>public.code_client_segment</code> table reference
     */
    public CodeClientSegment() {
        this(DSL.name("code_client_segment"), null);
    }

    public <O extends Record> CodeClientSegment(Table<O> path, ForeignKey<O, CodeClientSegmentRecord> childPath, InverseForeignKey<O, CodeClientSegmentRecord> parentPath) {
        super(path, childPath, parentPath, CODE_CLIENT_SEGMENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CodeClientSegmentPath extends CodeClientSegment implements Path<CodeClientSegmentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CodeClientSegmentPath(Table<O> path, ForeignKey<O, CodeClientSegmentRecord> childPath, InverseForeignKey<O, CodeClientSegmentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CodeClientSegmentPath(Name alias, Table<CodeClientSegmentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CodeClientSegmentPath as(String alias) {
            return new CodeClientSegmentPath(DSL.name(alias), this);
        }

        @Override
        public CodeClientSegmentPath as(Name alias) {
            return new CodeClientSegmentPath(alias, this);
        }

        @Override
        public CodeClientSegmentPath as(Table<?> alias) {
            return new CodeClientSegmentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CodeClientSegmentRecord> getPrimaryKey() {
        return Keys.CODE_CLIENT_SEGMENT_PKEY;
    }

    private transient ObjAccountPath _objAccount;

    /**
     * Get the implicit to-many join path to the <code>public.obj_account</code>
     * table
     */
    public ObjAccountPath objAccount() {
        if (_objAccount == null)
            _objAccount = new ObjAccountPath(this, null, Keys.OBJ_ACCOUNT__OBJ_ACCOUNT_CLIENT_SEGMENT_ID_FKEY.getInverseKey());

        return _objAccount;
    }

    @Override
    public CodeClientSegment as(String alias) {
        return new CodeClientSegment(DSL.name(alias), this);
    }

    @Override
    public CodeClientSegment as(Name alias) {
        return new CodeClientSegment(alias, this);
    }

    @Override
    public CodeClientSegment as(Table<?> alias) {
        return new CodeClientSegment(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeClientSegment rename(String name) {
        return new CodeClientSegment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeClientSegment rename(Name name) {
        return new CodeClientSegment(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeClientSegment rename(Table<?> name) {
        return new CodeClientSegment(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeClientSegment where(Condition condition) {
        return new CodeClientSegment(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeClientSegment where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeClientSegment where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeClientSegment where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeClientSegment where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeClientSegment where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeClientSegment where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeClientSegment where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeClientSegment whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeClientSegment whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
