/*
 * This file is generated by jOOQ.
 */
package fm.comunas.fm.lead.model.db.tables.records;


import fm.comunas.fm.lead.model.db.tables.DocLeadV;

import java.time.OffsetDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocLeadVRecord extends TableRecordImpl<DocLeadVRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.doc_lead_v.tenant_id</code>.
     */
    public void setTenantId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.tenant_id</code>.
     */
    public Integer getTenantId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.doc_lead_v.doc_type_id</code>.
     */
    public void setDocTypeId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.doc_type_id</code>.
     */
    public String getDocTypeId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.doc_lead_v.id</code>.
     */
    public void setId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.id</code>.
     */
    public Integer getId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.doc_lead_v.owner_id</code>.
     */
    public void setOwnerId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.owner_id</code>.
     */
    public Integer getOwnerId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.doc_lead_v.assignee_id</code>.
     */
    public void setAssigneeId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.assignee_id</code>.
     */
    public Integer getAssigneeId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.doc_lead_v.caption</code>.
     */
    public void setCaption(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.caption</code>.
     */
    public String getCaption() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.doc_lead_v.case_def_id</code>.
     */
    public void setCaseDefId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.case_def_id</code>.
     */
    public String getCaseDefId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.doc_lead_v.case_stage_id</code>.
     */
    public void setCaseStageId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.case_stage_id</code>.
     */
    public String getCaseStageId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.doc_lead_v.is_in_work</code>.
     */
    public void setIsInWork(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.is_in_work</code>.
     */
    public Boolean getIsInWork() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.doc_lead_v.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.doc_lead_v.created_by_user_id</code>.
     */
    public void setCreatedByUserId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.created_by_user_id</code>.
     */
    public Integer getCreatedByUserId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.doc_lead_v.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>public.doc_lead_v.modified_by_user_id</code>.
     */
    public void setModifiedByUserId(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.modified_by_user_id</code>.
     */
    public Integer getModifiedByUserId() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.doc_lead_v.modified_at</code>.
     */
    public void setModifiedAt(OffsetDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.modified_at</code>.
     */
    public OffsetDateTime getModifiedAt() {
        return (OffsetDateTime) get(13);
    }

    /**
     * Setter for <code>public.doc_lead_v.doc_id</code>.
     */
    public void setDocId(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.doc_id</code>.
     */
    public Integer getDocId() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.doc_lead_v.intl_key</code>.
     */
    public void setIntlKey(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.intl_key</code>.
     */
    public String getIntlKey() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.doc_lead_v.subject</code>.
     */
    public void setSubject(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.subject</code>.
     */
    public String getSubject() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.doc_lead_v.description</code>.
     */
    public void setDescription(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.description</code>.
     */
    public String getDescription() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.doc_lead_v.contact_id</code>.
     */
    public void setContactId(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.contact_id</code>.
     */
    public Integer getContactId() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>public.doc_lead_v.lead_source_id</code>.
     */
    public void setLeadSourceId(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.lead_source_id</code>.
     */
    public String getLeadSourceId() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.doc_lead_v.salutation_id</code>.
     */
    public void setSalutationId(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.salutation_id</code>.
     */
    public String getSalutationId() {
        return (String) get(20);
    }

    /**
     * Setter for <code>public.doc_lead_v.title_id</code>.
     */
    public void setTitleId(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.title_id</code>.
     */
    public String getTitleId() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.doc_lead_v.first_name</code>.
     */
    public void setFirstName(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(22);
    }

    /**
     * Setter for <code>public.doc_lead_v.last_name</code>.
     */
    public void setLastName(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.last_name</code>.
     */
    public String getLastName() {
        return (String) get(23);
    }

    /**
     * Setter for <code>public.doc_lead_v.phone</code>.
     */
    public void setPhone(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.phone</code>.
     */
    public String getPhone() {
        return (String) get(24);
    }

    /**
     * Setter for <code>public.doc_lead_v.mobile</code>.
     */
    public void setMobile(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.mobile</code>.
     */
    public String getMobile() {
        return (String) get(25);
    }

    /**
     * Setter for <code>public.doc_lead_v.email</code>.
     */
    public void setEmail(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.email</code>.
     */
    public String getEmail() {
        return (String) get(26);
    }

    /**
     * Setter for <code>public.doc_lead_v.lead_rating_id</code>.
     */
    public void setLeadRatingId(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.lead_rating_id</code>.
     */
    public String getLeadRatingId() {
        return (String) get(27);
    }

    /**
     * Setter for <code>public.doc_lead_v.street</code>.
     */
    public void setStreet(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.street</code>.
     */
    public String getStreet() {
        return (String) get(28);
    }

    /**
     * Setter for <code>public.doc_lead_v.zip</code>.
     */
    public void setZip(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.zip</code>.
     */
    public String getZip() {
        return (String) get(29);
    }

    /**
     * Setter for <code>public.doc_lead_v.city</code>.
     */
    public void setCity(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.city</code>.
     */
    public String getCity() {
        return (String) get(30);
    }

    /**
     * Setter for <code>public.doc_lead_v.state</code>.
     */
    public void setState(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.state</code>.
     */
    public String getState() {
        return (String) get(31);
    }

    /**
     * Setter for <code>public.doc_lead_v.country_id</code>.
     */
    public void setCountryId(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>public.doc_lead_v.country_id</code>.
     */
    public String getCountryId() {
        return (String) get(32);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DocLeadVRecord
     */
    public DocLeadVRecord() {
        super(DocLeadV.DOC_LEAD_V);
    }

    /**
     * Create a detached, initialised DocLeadVRecord
     */
    public DocLeadVRecord(Integer tenantId, String docTypeId, Integer id, Integer ownerId, Integer assigneeId, String caption, String caseDefId, String caseStageId, Boolean isInWork, Integer accountId, Integer createdByUserId, OffsetDateTime createdAt, Integer modifiedByUserId, OffsetDateTime modifiedAt, Integer docId, String intlKey, String subject, String description, Integer contactId, String leadSourceId, String salutationId, String titleId, String firstName, String lastName, String phone, String mobile, String email, String leadRatingId, String street, String zip, String city, String state, String countryId) {
        super(DocLeadV.DOC_LEAD_V);

        setTenantId(tenantId);
        setDocTypeId(docTypeId);
        setId(id);
        setOwnerId(ownerId);
        setAssigneeId(assigneeId);
        setCaption(caption);
        setCaseDefId(caseDefId);
        setCaseStageId(caseStageId);
        setIsInWork(isInWork);
        setAccountId(accountId);
        setCreatedByUserId(createdByUserId);
        setCreatedAt(createdAt);
        setModifiedByUserId(modifiedByUserId);
        setModifiedAt(modifiedAt);
        setDocId(docId);
        setIntlKey(intlKey);
        setSubject(subject);
        setDescription(description);
        setContactId(contactId);
        setLeadSourceId(leadSourceId);
        setSalutationId(salutationId);
        setTitleId(titleId);
        setFirstName(firstName);
        setLastName(lastName);
        setPhone(phone);
        setMobile(mobile);
        setEmail(email);
        setLeadRatingId(leadRatingId);
        setStreet(street);
        setZip(zip);
        setCity(city);
        setState(state);
        setCountryId(countryId);
    }
}
