/*
 * This file is generated by jOOQ.
 */
package fm.comunas.fm.portfolio.model.db;


import fm.comunas.fm.portfolio.model.db.tables.ObjPortfolio;
import fm.comunas.fm.portfolio.model.db.tables.ObjPortfolioSearch;
import fm.comunas.fm.portfolio.model.db.tables.ObjPortfolioV;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.obj_portfolio</code>.
     */
    public final ObjPortfolio OBJ_PORTFOLIO = ObjPortfolio.OBJ_PORTFOLIO;

    /**
     * The table <code>public.obj_portfolio_search</code>.
     */
    public final ObjPortfolioSearch OBJ_PORTFOLIO_SEARCH = ObjPortfolioSearch.OBJ_PORTFOLIO_SEARCH;

    /**
     * The table <code>public.obj_portfolio_v</code>.
     */
    public final ObjPortfolioV OBJ_PORTFOLIO_V = ObjPortfolioV.OBJ_PORTFOLIO_V;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            ObjPortfolio.OBJ_PORTFOLIO,
            ObjPortfolioSearch.OBJ_PORTFOLIO_SEARCH,
            ObjPortfolioV.OBJ_PORTFOLIO_V);
    }
}
