/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.contact.model.db.tables;


import io.zeitwert.fm.contact.model.db.Keys;
import io.zeitwert.fm.contact.model.db.Public;
import io.zeitwert.fm.contact.model.db.tables.records.CodeTitleRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CodeTitle extends TableImpl<CodeTitleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.code_title</code>
     */
    public static final CodeTitle CODE_TITLE = new CodeTitle();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeTitleRecord> getRecordType() {
        return CodeTitleRecord.class;
    }

    /**
     * The column <code>public.code_title.id</code>.
     */
    public final TableField<CodeTitleRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.code_title.name</code>.
     */
    public final TableField<CodeTitleRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private CodeTitle(Name alias, Table<CodeTitleRecord> aliased) {
        this(alias, aliased, null);
    }

    private CodeTitle(Name alias, Table<CodeTitleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.code_title</code> table reference
     */
    public CodeTitle(String alias) {
        this(DSL.name(alias), CODE_TITLE);
    }

    /**
     * Create an aliased <code>public.code_title</code> table reference
     */
    public CodeTitle(Name alias) {
        this(alias, CODE_TITLE);
    }

    /**
     * Create a <code>public.code_title</code> table reference
     */
    public CodeTitle() {
        this(DSL.name("code_title"), null);
    }

    public <O extends Record> CodeTitle(Table<O> child, ForeignKey<O, CodeTitleRecord> key) {
        super(child, key, CODE_TITLE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<CodeTitleRecord> getPrimaryKey() {
        return Keys.CODE_TITLE_PKEY;
    }

    @Override
    public List<UniqueKey<CodeTitleRecord>> getKeys() {
        return Arrays.<UniqueKey<CodeTitleRecord>>asList(Keys.CODE_TITLE_PKEY);
    }

    @Override
    public CodeTitle as(String alias) {
        return new CodeTitle(DSL.name(alias), this);
    }

    @Override
    public CodeTitle as(Name alias) {
        return new CodeTitle(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeTitle rename(String name) {
        return new CodeTitle(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeTitle rename(Name name) {
        return new CodeTitle(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
