/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.contact.model.db.tables;


import io.zeitwert.fm.contact.model.db.Keys;
import io.zeitwert.fm.contact.model.db.Public;
import io.zeitwert.fm.contact.model.db.tables.records.ObjContactPartAnniversaryRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObjContactPartAnniversary extends TableImpl<ObjContactPartAnniversaryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.obj_contact_part_anniversary</code>
     */
    public static final ObjContactPartAnniversary OBJ_CONTACT_PART_ANNIVERSARY = new ObjContactPartAnniversary();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ObjContactPartAnniversaryRecord> getRecordType() {
        return ObjContactPartAnniversaryRecord.class;
    }

    /**
     * The column <code>public.obj_contact_part_anniversary.id</code>.
     */
    public final TableField<ObjContactPartAnniversaryRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.obj_contact_part_anniversary.obj_id</code>.
     */
    public final TableField<ObjContactPartAnniversaryRecord, Integer> OBJ_ID = createField(DSL.name("obj_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.obj_contact_part_anniversary.parent_part_id</code>.
     */
    public final TableField<ObjContactPartAnniversaryRecord, Integer> PARENT_PART_ID = createField(DSL.name("parent_part_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_contact_part_anniversary.part_list_type_id</code>.
     */
    public final TableField<ObjContactPartAnniversaryRecord, String> PART_LIST_TYPE_ID = createField(DSL.name("part_list_type_id"), SQLDataType.VARCHAR(40).nullable(false).defaultValue(DSL.field("'contact.anniversaryList'::character varying", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.obj_contact_part_anniversary.seq_nr</code>.
     */
    public final TableField<ObjContactPartAnniversaryRecord, Integer> SEQ_NR = createField(DSL.name("seq_nr"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_contact_part_anniversary.key</code>.
     */
    public final TableField<ObjContactPartAnniversaryRecord, String> KEY = createField(DSL.name("key"), SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>public.obj_contact_part_anniversary.anniversary_type_id</code>.
     */
    public final TableField<ObjContactPartAnniversaryRecord, String> ANNIVERSARY_TYPE_ID = createField(DSL.name("anniversary_type_id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.obj_contact_part_anniversary.start_date</code>.
     */
    public final TableField<ObjContactPartAnniversaryRecord, LocalDate> START_DATE = createField(DSL.name("start_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.obj_contact_part_anniversary.anniversary_notification_id</code>.
     */
    public final TableField<ObjContactPartAnniversaryRecord, String> ANNIVERSARY_NOTIFICATION_ID = createField(DSL.name("anniversary_notification_id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.obj_contact_part_anniversary.anniversary_template_id</code>.
     */
    public final TableField<ObjContactPartAnniversaryRecord, String> ANNIVERSARY_TEMPLATE_ID = createField(DSL.name("anniversary_template_id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    private ObjContactPartAnniversary(Name alias, Table<ObjContactPartAnniversaryRecord> aliased) {
        this(alias, aliased, null);
    }

    private ObjContactPartAnniversary(Name alias, Table<ObjContactPartAnniversaryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.obj_contact_part_anniversary</code> table reference
     */
    public ObjContactPartAnniversary(String alias) {
        this(DSL.name(alias), OBJ_CONTACT_PART_ANNIVERSARY);
    }

    /**
     * Create an aliased <code>public.obj_contact_part_anniversary</code> table reference
     */
    public ObjContactPartAnniversary(Name alias) {
        this(alias, OBJ_CONTACT_PART_ANNIVERSARY);
    }

    /**
     * Create a <code>public.obj_contact_part_anniversary</code> table reference
     */
    public ObjContactPartAnniversary() {
        this(DSL.name("obj_contact_part_anniversary"), null);
    }

    public <O extends Record> ObjContactPartAnniversary(Table<O> child, ForeignKey<O, ObjContactPartAnniversaryRecord> key) {
        super(child, key, OBJ_CONTACT_PART_ANNIVERSARY);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<ObjContactPartAnniversaryRecord> getPrimaryKey() {
        return Keys.OBJ_CONTACT_PART_ANNIVERSARY_PKEY;
    }

    @Override
    public List<UniqueKey<ObjContactPartAnniversaryRecord>> getKeys() {
        return Arrays.<UniqueKey<ObjContactPartAnniversaryRecord>>asList(Keys.OBJ_CONTACT_PART_ANNIVERSARY_PKEY);
    }

    @Override
    public List<ForeignKey<ObjContactPartAnniversaryRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ObjContactPartAnniversaryRecord, ?>>asList(Keys.OBJ_CONTACT_PART_ANNIVERSARY__OBJ_CONTACT_PART_ANNIVERSARY_OBJ_ID_FKEY, Keys.OBJ_CONTACT_PART_ANNIVERSARY__OBJ_CONTACT_PART_ANNIVERSARY_ANNIVERSARY_TYPE_ID_FKEY, Keys.OBJ_CONTACT_PART_ANNIVERSARY__OBJ_CONTACT_PART_ANNIVERSARY_ANNIVERSARY_NOTIFICATION_ID_FKEY, Keys.OBJ_CONTACT_PART_ANNIVERSARY__OBJ_CONTACT_PART_ANNIVERSARY_ANNIVERSARY_TEMPLATE_ID_FKEY);
    }

    private transient ObjContact _objContact;
    private transient CodeAnniversaryType _codeAnniversaryType;
    private transient CodeAnniversaryNotification _codeAnniversaryNotification;
    private transient CodeAnniversaryTemplate _codeAnniversaryTemplate;

    public ObjContact objContact() {
        if (_objContact == null)
            _objContact = new ObjContact(this, Keys.OBJ_CONTACT_PART_ANNIVERSARY__OBJ_CONTACT_PART_ANNIVERSARY_OBJ_ID_FKEY);

        return _objContact;
    }

    public CodeAnniversaryType codeAnniversaryType() {
        if (_codeAnniversaryType == null)
            _codeAnniversaryType = new CodeAnniversaryType(this, Keys.OBJ_CONTACT_PART_ANNIVERSARY__OBJ_CONTACT_PART_ANNIVERSARY_ANNIVERSARY_TYPE_ID_FKEY);

        return _codeAnniversaryType;
    }

    public CodeAnniversaryNotification codeAnniversaryNotification() {
        if (_codeAnniversaryNotification == null)
            _codeAnniversaryNotification = new CodeAnniversaryNotification(this, Keys.OBJ_CONTACT_PART_ANNIVERSARY__OBJ_CONTACT_PART_ANNIVERSARY_ANNIVERSARY_NOTIFICATION_ID_FKEY);

        return _codeAnniversaryNotification;
    }

    public CodeAnniversaryTemplate codeAnniversaryTemplate() {
        if (_codeAnniversaryTemplate == null)
            _codeAnniversaryTemplate = new CodeAnniversaryTemplate(this, Keys.OBJ_CONTACT_PART_ANNIVERSARY__OBJ_CONTACT_PART_ANNIVERSARY_ANNIVERSARY_TEMPLATE_ID_FKEY);

        return _codeAnniversaryTemplate;
    }

    @Override
    public ObjContactPartAnniversary as(String alias) {
        return new ObjContactPartAnniversary(DSL.name(alias), this);
    }

    @Override
    public ObjContactPartAnniversary as(Name alias) {
        return new ObjContactPartAnniversary(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjContactPartAnniversary rename(String name) {
        return new ObjContactPartAnniversary(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjContactPartAnniversary rename(Name name) {
        return new ObjContactPartAnniversary(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, Integer, Integer, String, Integer, String, String, LocalDate, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
