/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.contact.model.db.tables;


import io.zeitwert.fm.contact.model.db.Public;
import io.zeitwert.fm.contact.model.db.tables.records.ObjContactVRecord;

import java.time.LocalDate;
import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObjContactV extends TableImpl<ObjContactVRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.obj_contact_v</code>
     */
    public static final ObjContactV OBJ_CONTACT_V = new ObjContactV();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ObjContactVRecord> getRecordType() {
        return ObjContactVRecord.class;
    }

    /**
     * The column <code>public.obj_contact_v.obj_type_id</code>.
     */
    public final TableField<ObjContactVRecord, String> OBJ_TYPE_ID = createField(DSL.name("obj_type_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.obj_contact_v.id</code>.
     */
    public final TableField<ObjContactVRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_contact_v.owner_id</code>.
     */
    public final TableField<ObjContactVRecord, Integer> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_contact_v.caption</code>.
     */
    public final TableField<ObjContactVRecord, String> CAPTION = createField(DSL.name("caption"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.obj_contact_v.created_by_user_id</code>.
     */
    public final TableField<ObjContactVRecord, Integer> CREATED_BY_USER_ID = createField(DSL.name("created_by_user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_contact_v.created_at</code>.
     */
    public final TableField<ObjContactVRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.obj_contact_v.modified_by_user_id</code>.
     */
    public final TableField<ObjContactVRecord, Integer> MODIFIED_BY_USER_ID = createField(DSL.name("modified_by_user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_contact_v.modified_at</code>.
     */
    public final TableField<ObjContactVRecord, OffsetDateTime> MODIFIED_AT = createField(DSL.name("modified_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.obj_contact_v.closed_by_user_id</code>.
     */
    public final TableField<ObjContactVRecord, Integer> CLOSED_BY_USER_ID = createField(DSL.name("closed_by_user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_contact_v.closed_at</code>.
     */
    public final TableField<ObjContactVRecord, OffsetDateTime> CLOSED_AT = createField(DSL.name("closed_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.obj_contact_v.obj_id</code>.
     */
    public final TableField<ObjContactVRecord, Integer> OBJ_ID = createField(DSL.name("obj_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_contact_v.tenant_id</code>.
     */
    public final TableField<ObjContactVRecord, Integer> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_contact_v.account_id</code>.
     */
    public final TableField<ObjContactVRecord, Integer> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_contact_v.intl_key</code>.
     */
    public final TableField<ObjContactVRecord, String> INTL_KEY = createField(DSL.name("intl_key"), SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>public.obj_contact_v.description</code>.
     */
    public final TableField<ObjContactVRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.obj_contact_v.contact_role_id</code>.
     */
    public final TableField<ObjContactVRecord, String> CONTACT_ROLE_ID = createField(DSL.name("contact_role_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.obj_contact_v.salutation_id</code>.
     */
    public final TableField<ObjContactVRecord, String> SALUTATION_ID = createField(DSL.name("salutation_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.obj_contact_v.title_id</code>.
     */
    public final TableField<ObjContactVRecord, String> TITLE_ID = createField(DSL.name("title_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.obj_contact_v.first_name</code>.
     */
    public final TableField<ObjContactVRecord, String> FIRST_NAME = createField(DSL.name("first_name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.obj_contact_v.last_name</code>.
     */
    public final TableField<ObjContactVRecord, String> LAST_NAME = createField(DSL.name("last_name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.obj_contact_v.birth_date</code>.
     */
    public final TableField<ObjContactVRecord, LocalDate> BIRTH_DATE = createField(DSL.name("birth_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.obj_contact_v.phone</code>.
     */
    public final TableField<ObjContactVRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>public.obj_contact_v.mobile</code>.
     */
    public final TableField<ObjContactVRecord, String> MOBILE = createField(DSL.name("mobile"), SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>public.obj_contact_v.email</code>.
     */
    public final TableField<ObjContactVRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(60), this, "");

    private ObjContactV(Name alias, Table<ObjContactVRecord> aliased) {
        this(alias, aliased, null);
    }

    private ObjContactV(Name alias, Table<ObjContactVRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("create view \"obj_contact_v\" as  SELECT obj.obj_type_id,\n    ct.obj_id AS id,\n    obj.owner_id,\n    obj.caption,\n    obj.created_by_user_id,\n    obj.created_at,\n    obj.modified_by_user_id,\n    obj.modified_at,\n    obj.closed_by_user_id,\n    obj.closed_at,\n    ct.obj_id,\n    ct.tenant_id,\n    ct.account_id,\n    ct.intl_key,\n    ct.description,\n    ct.contact_role_id,\n    ct.salutation_id,\n    ct.title_id,\n    ct.first_name,\n    ct.last_name,\n    ct.birth_date,\n    ct.phone,\n    ct.mobile,\n    ct.email\n   FROM (obj_contact ct\n     JOIN obj ON ((obj.id = ct.obj_id)));"));
    }

    /**
     * Create an aliased <code>public.obj_contact_v</code> table reference
     */
    public ObjContactV(String alias) {
        this(DSL.name(alias), OBJ_CONTACT_V);
    }

    /**
     * Create an aliased <code>public.obj_contact_v</code> table reference
     */
    public ObjContactV(Name alias) {
        this(alias, OBJ_CONTACT_V);
    }

    /**
     * Create a <code>public.obj_contact_v</code> table reference
     */
    public ObjContactV() {
        this(DSL.name("obj_contact_v"), null);
    }

    public <O extends Record> ObjContactV(Table<O> child, ForeignKey<O, ObjContactVRecord> key) {
        super(child, key, OBJ_CONTACT_V);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public ObjContactV as(String alias) {
        return new ObjContactV(DSL.name(alias), this);
    }

    @Override
    public ObjContactV as(Name alias) {
        return new ObjContactV(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjContactV rename(String name) {
        return new ObjContactV(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjContactV rename(Name name) {
        return new ObjContactV(name, null);
    }
}
