/*
 * This file is generated by jOOQ.
 */
package fm.comunas.fm.building.model.db.tables;


import fm.comunas.fm.building.model.db.Keys;
import fm.comunas.fm.building.model.db.Public;
import fm.comunas.fm.building.model.db.tables.records.CodeBuildingMaintenanceStrategyRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CodeBuildingMaintenanceStrategy extends TableImpl<CodeBuildingMaintenanceStrategyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.code_building_maintenance_strategy</code>
     */
    public static final CodeBuildingMaintenanceStrategy CODE_BUILDING_MAINTENANCE_STRATEGY = new CodeBuildingMaintenanceStrategy();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeBuildingMaintenanceStrategyRecord> getRecordType() {
        return CodeBuildingMaintenanceStrategyRecord.class;
    }

    /**
     * The column <code>public.code_building_maintenance_strategy.id</code>.
     */
    public final TableField<CodeBuildingMaintenanceStrategyRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.code_building_maintenance_strategy.name</code>.
     */
    public final TableField<CodeBuildingMaintenanceStrategyRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private CodeBuildingMaintenanceStrategy(Name alias, Table<CodeBuildingMaintenanceStrategyRecord> aliased) {
        this(alias, aliased, null);
    }

    private CodeBuildingMaintenanceStrategy(Name alias, Table<CodeBuildingMaintenanceStrategyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.code_building_maintenance_strategy</code> table reference
     */
    public CodeBuildingMaintenanceStrategy(String alias) {
        this(DSL.name(alias), CODE_BUILDING_MAINTENANCE_STRATEGY);
    }

    /**
     * Create an aliased <code>public.code_building_maintenance_strategy</code> table reference
     */
    public CodeBuildingMaintenanceStrategy(Name alias) {
        this(alias, CODE_BUILDING_MAINTENANCE_STRATEGY);
    }

    /**
     * Create a <code>public.code_building_maintenance_strategy</code> table reference
     */
    public CodeBuildingMaintenanceStrategy() {
        this(DSL.name("code_building_maintenance_strategy"), null);
    }

    public <O extends Record> CodeBuildingMaintenanceStrategy(Table<O> child, ForeignKey<O, CodeBuildingMaintenanceStrategyRecord> key) {
        super(child, key, CODE_BUILDING_MAINTENANCE_STRATEGY);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<CodeBuildingMaintenanceStrategyRecord> getPrimaryKey() {
        return Keys.CODE_BUILDING_MAINTENANCE_STRATEGY_PKEY;
    }

    @Override
    public List<UniqueKey<CodeBuildingMaintenanceStrategyRecord>> getKeys() {
        return Arrays.<UniqueKey<CodeBuildingMaintenanceStrategyRecord>>asList(Keys.CODE_BUILDING_MAINTENANCE_STRATEGY_PKEY);
    }

    @Override
    public CodeBuildingMaintenanceStrategy as(String alias) {
        return new CodeBuildingMaintenanceStrategy(DSL.name(alias), this);
    }

    @Override
    public CodeBuildingMaintenanceStrategy as(Name alias) {
        return new CodeBuildingMaintenanceStrategy(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeBuildingMaintenanceStrategy rename(String name) {
        return new CodeBuildingMaintenanceStrategy(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeBuildingMaintenanceStrategy rename(Name name) {
        return new CodeBuildingMaintenanceStrategy(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
