/*
 * This file is generated by jOOQ.
 */
package fm.comunas.fm.building.model.db.tables;


import fm.comunas.fm.building.model.db.Keys;
import fm.comunas.fm.building.model.db.Public;
import fm.comunas.fm.building.model.db.tables.records.CodeBuildingPartCatalogRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CodeBuildingPartCatalog extends TableImpl<CodeBuildingPartCatalogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.code_building_part_catalog</code>
     */
    public static final CodeBuildingPartCatalog CODE_BUILDING_PART_CATALOG = new CodeBuildingPartCatalog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeBuildingPartCatalogRecord> getRecordType() {
        return CodeBuildingPartCatalogRecord.class;
    }

    /**
     * The column <code>public.code_building_part_catalog.id</code>.
     */
    public final TableField<CodeBuildingPartCatalogRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.code_building_part_catalog.name</code>.
     */
    public final TableField<CodeBuildingPartCatalogRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.code_building_part_catalog.parts</code>.
     */
    public final TableField<CodeBuildingPartCatalogRecord, String> PARTS = createField(DSL.name("parts"), SQLDataType.VARCHAR(400), this, "");

    private CodeBuildingPartCatalog(Name alias, Table<CodeBuildingPartCatalogRecord> aliased) {
        this(alias, aliased, null);
    }

    private CodeBuildingPartCatalog(Name alias, Table<CodeBuildingPartCatalogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.code_building_part_catalog</code> table reference
     */
    public CodeBuildingPartCatalog(String alias) {
        this(DSL.name(alias), CODE_BUILDING_PART_CATALOG);
    }

    /**
     * Create an aliased <code>public.code_building_part_catalog</code> table reference
     */
    public CodeBuildingPartCatalog(Name alias) {
        this(alias, CODE_BUILDING_PART_CATALOG);
    }

    /**
     * Create a <code>public.code_building_part_catalog</code> table reference
     */
    public CodeBuildingPartCatalog() {
        this(DSL.name("code_building_part_catalog"), null);
    }

    public <O extends Record> CodeBuildingPartCatalog(Table<O> child, ForeignKey<O, CodeBuildingPartCatalogRecord> key) {
        super(child, key, CODE_BUILDING_PART_CATALOG);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<CodeBuildingPartCatalogRecord> getPrimaryKey() {
        return Keys.CODE_BUILDING_PART_CATALOG_PKEY;
    }

    @Override
    public List<UniqueKey<CodeBuildingPartCatalogRecord>> getKeys() {
        return Arrays.<UniqueKey<CodeBuildingPartCatalogRecord>>asList(Keys.CODE_BUILDING_PART_CATALOG_PKEY);
    }

    @Override
    public CodeBuildingPartCatalog as(String alias) {
        return new CodeBuildingPartCatalog(DSL.name(alias), this);
    }

    @Override
    public CodeBuildingPartCatalog as(Name alias) {
        return new CodeBuildingPartCatalog(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeBuildingPartCatalog rename(String name) {
        return new CodeBuildingPartCatalog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeBuildingPartCatalog rename(Name name) {
        return new CodeBuildingPartCatalog(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
