/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.dms.model.db.tables.records;


import io.zeitwert.fm.dms.model.db.tables.ObjDocumentPartContent;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObjDocumentPartContentRecord extends UpdatableRecordImpl<ObjDocumentPartContentRecord> implements Record6<Integer, Integer, String, byte[], Integer, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.obj_document_part_content.obj_id</code>.
     */
    public void setObjId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.obj_document_part_content.obj_id</code>.
     */
    public Integer getObjId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.obj_document_part_content.version_nr</code>.
     */
    public void setVersionNr(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.obj_document_part_content.version_nr</code>.
     */
    public Integer getVersionNr() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.obj_document_part_content.content_type_id</code>.
     */
    public void setContentTypeId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.obj_document_part_content.content_type_id</code>.
     */
    public String getContentTypeId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.obj_document_part_content.content</code>.
     */
    public void setContent(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.obj_document_part_content.content</code>.
     */
    public byte[] getContent() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>public.obj_document_part_content.created_by_user_id</code>.
     */
    public void setCreatedByUserId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.obj_document_part_content.created_by_user_id</code>.
     */
    public Integer getCreatedByUserId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.obj_document_part_content.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.obj_document_part_content.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, byte[], Integer, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, String, byte[], Integer, OffsetDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ObjDocumentPartContent.OBJ_DOCUMENT_PART_CONTENT.OBJ_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ObjDocumentPartContent.OBJ_DOCUMENT_PART_CONTENT.VERSION_NR;
    }

    @Override
    public Field<String> field3() {
        return ObjDocumentPartContent.OBJ_DOCUMENT_PART_CONTENT.CONTENT_TYPE_ID;
    }

    @Override
    public Field<byte[]> field4() {
        return ObjDocumentPartContent.OBJ_DOCUMENT_PART_CONTENT.CONTENT;
    }

    @Override
    public Field<Integer> field5() {
        return ObjDocumentPartContent.OBJ_DOCUMENT_PART_CONTENT.CREATED_BY_USER_ID;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return ObjDocumentPartContent.OBJ_DOCUMENT_PART_CONTENT.CREATED_AT;
    }

    @Override
    public Integer component1() {
        return getObjId();
    }

    @Override
    public Integer component2() {
        return getVersionNr();
    }

    @Override
    public String component3() {
        return getContentTypeId();
    }

    @Override
    public byte[] component4() {
        return getContent();
    }

    @Override
    public Integer component5() {
        return getCreatedByUserId();
    }

    @Override
    public OffsetDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public Integer value1() {
        return getObjId();
    }

    @Override
    public Integer value2() {
        return getVersionNr();
    }

    @Override
    public String value3() {
        return getContentTypeId();
    }

    @Override
    public byte[] value4() {
        return getContent();
    }

    @Override
    public Integer value5() {
        return getCreatedByUserId();
    }

    @Override
    public OffsetDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public ObjDocumentPartContentRecord value1(Integer value) {
        setObjId(value);
        return this;
    }

    @Override
    public ObjDocumentPartContentRecord value2(Integer value) {
        setVersionNr(value);
        return this;
    }

    @Override
    public ObjDocumentPartContentRecord value3(String value) {
        setContentTypeId(value);
        return this;
    }

    @Override
    public ObjDocumentPartContentRecord value4(byte[] value) {
        setContent(value);
        return this;
    }

    @Override
    public ObjDocumentPartContentRecord value5(Integer value) {
        setCreatedByUserId(value);
        return this;
    }

    @Override
    public ObjDocumentPartContentRecord value6(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ObjDocumentPartContentRecord values(Integer value1, Integer value2, String value3, byte[] value4, Integer value5, OffsetDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ObjDocumentPartContentRecord
     */
    public ObjDocumentPartContentRecord() {
        super(ObjDocumentPartContent.OBJ_DOCUMENT_PART_CONTENT);
    }

    /**
     * Create a detached, initialised ObjDocumentPartContentRecord
     */
    public ObjDocumentPartContentRecord(Integer objId, Integer versionNr, String contentTypeId, byte[] content, Integer createdByUserId, OffsetDateTime createdAt) {
        super(ObjDocumentPartContent.OBJ_DOCUMENT_PART_CONTENT);

        setObjId(objId);
        setVersionNr(versionNr);
        setContentTypeId(contentTypeId);
        setContent(content);
        setCreatedByUserId(createdByUserId);
        setCreatedAt(createdAt);
    }
}
