/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.dms.model.db.tables.records;


import io.zeitwert.fm.dms.model.db.tables.ObjDocument;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObjDocumentRecord extends UpdatableRecordImpl<ObjDocumentRecord> implements Record6<Integer, String, String, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.obj_document.obj_id</code>.
     */
    public void setObjId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.obj_document.obj_id</code>.
     */
    public Integer getObjId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.obj_document.content_kind_id</code>.
     */
    public void setContentKindId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.obj_document.content_kind_id</code>.
     */
    public String getContentKindId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.obj_document.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.obj_document.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.obj_document.document_kind_id</code>.
     */
    public void setDocumentKindId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.obj_document.document_kind_id</code>.
     */
    public String getDocumentKindId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.obj_document.document_category_id</code>.
     */
    public void setDocumentCategoryId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.obj_document.document_category_id</code>.
     */
    public String getDocumentCategoryId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.obj_document.template_document_id</code>.
     */
    public void setTemplateDocumentId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.obj_document.template_document_id</code>.
     */
    public Integer getTemplateDocumentId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ObjDocument.OBJ_DOCUMENT.OBJ_ID;
    }

    @Override
    public Field<String> field2() {
        return ObjDocument.OBJ_DOCUMENT.CONTENT_KIND_ID;
    }

    @Override
    public Field<String> field3() {
        return ObjDocument.OBJ_DOCUMENT.NAME;
    }

    @Override
    public Field<String> field4() {
        return ObjDocument.OBJ_DOCUMENT.DOCUMENT_KIND_ID;
    }

    @Override
    public Field<String> field5() {
        return ObjDocument.OBJ_DOCUMENT.DOCUMENT_CATEGORY_ID;
    }

    @Override
    public Field<Integer> field6() {
        return ObjDocument.OBJ_DOCUMENT.TEMPLATE_DOCUMENT_ID;
    }

    @Override
    public Integer component1() {
        return getObjId();
    }

    @Override
    public String component2() {
        return getContentKindId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDocumentKindId();
    }

    @Override
    public String component5() {
        return getDocumentCategoryId();
    }

    @Override
    public Integer component6() {
        return getTemplateDocumentId();
    }

    @Override
    public Integer value1() {
        return getObjId();
    }

    @Override
    public String value2() {
        return getContentKindId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDocumentKindId();
    }

    @Override
    public String value5() {
        return getDocumentCategoryId();
    }

    @Override
    public Integer value6() {
        return getTemplateDocumentId();
    }

    @Override
    public ObjDocumentRecord value1(Integer value) {
        setObjId(value);
        return this;
    }

    @Override
    public ObjDocumentRecord value2(String value) {
        setContentKindId(value);
        return this;
    }

    @Override
    public ObjDocumentRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public ObjDocumentRecord value4(String value) {
        setDocumentKindId(value);
        return this;
    }

    @Override
    public ObjDocumentRecord value5(String value) {
        setDocumentCategoryId(value);
        return this;
    }

    @Override
    public ObjDocumentRecord value6(Integer value) {
        setTemplateDocumentId(value);
        return this;
    }

    @Override
    public ObjDocumentRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ObjDocumentRecord
     */
    public ObjDocumentRecord() {
        super(ObjDocument.OBJ_DOCUMENT);
    }

    /**
     * Create a detached, initialised ObjDocumentRecord
     */
    public ObjDocumentRecord(Integer objId, String contentKindId, String name, String documentKindId, String documentCategoryId, Integer templateDocumentId) {
        super(ObjDocument.OBJ_DOCUMENT);

        setObjId(objId);
        setContentKindId(contentKindId);
        setName(name);
        setDocumentKindId(documentKindId);
        setDocumentCategoryId(documentCategoryId);
        setTemplateDocumentId(templateDocumentId);
    }
}
