/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.collaboration.model.db.tables.records;


import io.zeitwert.fm.collaboration.model.db.tables.CodeNoteType;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeNoteTypeRecord extends UpdatableRecordImpl<CodeNoteTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.code_note_type.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.code_note_type.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.code_note_type.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.code_note_type.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CodeNoteTypeRecord
     */
    public CodeNoteTypeRecord() {
        super(CodeNoteType.CODE_NOTE_TYPE);
    }

    /**
     * Create a detached, initialised CodeNoteTypeRecord
     */
    public CodeNoteTypeRecord(String id, String name) {
        super(CodeNoteType.CODE_NOTE_TYPE);

        setId(id);
        setName(name);
        resetChangedOnNotNull();
    }
}
