/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.collaboration.model.db.tables.records;


import io.zeitwert.fm.collaboration.model.db.tables.ObjNote;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ObjNoteRecord extends UpdatableRecordImpl<ObjNoteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.obj_note.obj_id</code>.
     */
    public void setObjId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.obj_note.obj_id</code>.
     */
    public Integer getObjId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.obj_note.tenant_id</code>.
     */
    public void setTenantId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.obj_note.tenant_id</code>.
     */
    public Integer getTenantId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.obj_note.note_type_id</code>.
     */
    public void setNoteTypeId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.obj_note.note_type_id</code>.
     */
    public String getNoteTypeId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.obj_note.subject</code>.
     */
    public void setSubject(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.obj_note.subject</code>.
     */
    public String getSubject() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.obj_note.content</code>.
     */
    public void setContent(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.obj_note.content</code>.
     */
    public String getContent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.obj_note.is_private</code>.
     */
    public void setIsPrivate(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.obj_note.is_private</code>.
     */
    public Boolean getIsPrivate() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.obj_note.related_to_id</code>.
     */
    public void setRelatedToId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.obj_note.related_to_id</code>.
     */
    public Integer getRelatedToId() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ObjNoteRecord
     */
    public ObjNoteRecord() {
        super(ObjNote.OBJ_NOTE);
    }

    /**
     * Create a detached, initialised ObjNoteRecord
     */
    public ObjNoteRecord(Integer objId, Integer tenantId, String noteTypeId, String subject, String content, Boolean isPrivate, Integer relatedToId) {
        super(ObjNote.OBJ_NOTE);

        setObjId(objId);
        setTenantId(tenantId);
        setNoteTypeId(noteTypeId);
        setSubject(subject);
        setContent(content);
        setIsPrivate(isPrivate);
        setRelatedToId(relatedToId);
        resetChangedOnNotNull();
    }
}
