/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.contact.model.db;


import io.zeitwert.fm.contact.model.db.tables.CodeAddressChannel;
import io.zeitwert.fm.contact.model.db.tables.CodeAddressType;
import io.zeitwert.fm.contact.model.db.tables.CodeContactRole;
import io.zeitwert.fm.contact.model.db.tables.CodeGender;
import io.zeitwert.fm.contact.model.db.tables.CodeSalutation;
import io.zeitwert.fm.contact.model.db.tables.CodeTitle;
import io.zeitwert.fm.contact.model.db.tables.ObjContact;
import io.zeitwert.fm.contact.model.db.tables.ObjContactPartAddress;
import io.zeitwert.fm.contact.model.db.tables.ObjContactV;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.code_address_channel</code>.
     */
    public static final CodeAddressChannel CODE_ADDRESS_CHANNEL = CodeAddressChannel.CODE_ADDRESS_CHANNEL;

    /**
     * The table <code>public.code_address_type</code>.
     */
    public static final CodeAddressType CODE_ADDRESS_TYPE = CodeAddressType.CODE_ADDRESS_TYPE;

    /**
     * The table <code>public.code_contact_role</code>.
     */
    public static final CodeContactRole CODE_CONTACT_ROLE = CodeContactRole.CODE_CONTACT_ROLE;

    /**
     * The table <code>public.code_gender</code>.
     */
    public static final CodeGender CODE_GENDER = CodeGender.CODE_GENDER;

    /**
     * The table <code>public.code_salutation</code>.
     */
    public static final CodeSalutation CODE_SALUTATION = CodeSalutation.CODE_SALUTATION;

    /**
     * The table <code>public.code_title</code>.
     */
    public static final CodeTitle CODE_TITLE = CodeTitle.CODE_TITLE;

    /**
     * The table <code>public.obj_contact</code>.
     */
    public static final ObjContact OBJ_CONTACT = ObjContact.OBJ_CONTACT;

    /**
     * The table <code>public.obj_contact_part_address</code>.
     */
    public static final ObjContactPartAddress OBJ_CONTACT_PART_ADDRESS = ObjContactPartAddress.OBJ_CONTACT_PART_ADDRESS;

    /**
     * The table <code>public.obj_contact_v</code>.
     */
    public static final ObjContactV OBJ_CONTACT_V = ObjContactV.OBJ_CONTACT_V;
}
