/*
 * This file is generated by jOOQ.
 */
package io.domain.test.model.db.tables.records;


import io.domain.test.model.db.tables.DocTest;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DocTestRecord extends UpdatableRecordImpl<DocTestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.doc_test.doc_id</code>.
     */
    public void setDocId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.doc_test.doc_id</code>.
     */
    public Integer getDocId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.doc_test.tenant_id</code>.
     */
    public void setTenantId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.doc_test.tenant_id</code>.
     */
    public Integer getTenantId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.doc_test.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.doc_test.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.doc_test.short_text</code>.
     */
    public void setShortText(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.doc_test.short_text</code>.
     */
    public String getShortText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.doc_test.long_text</code>.
     */
    public void setLongText(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.doc_test.long_text</code>.
     */
    public String getLongText() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.doc_test.date</code>.
     */
    public void setDate(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.doc_test.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>public.doc_test.int</code>.
     */
    public void setInt(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.doc_test.int</code>.
     */
    public Integer getInt() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.doc_test.is_done</code>.
     */
    public void setIsDone(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.doc_test.is_done</code>.
     */
    public Boolean getIsDone() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.doc_test.json</code>.
     */
    public void setJson(JSON value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.doc_test.json</code>.
     */
    public JSON getJson() {
        return (JSON) get(8);
    }

    /**
     * Setter for <code>public.doc_test.nr</code>.
     */
    public void setNr(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.doc_test.nr</code>.
     */
    public BigDecimal getNr() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>public.doc_test.test_type_id</code>.
     */
    public void setTestTypeId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.doc_test.test_type_id</code>.
     */
    public String getTestTypeId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.doc_test.ref_obj_id</code>.
     */
    public void setRefObjId(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.doc_test.ref_obj_id</code>.
     */
    public Integer getRefObjId() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.doc_test.ref_doc_id</code>.
     */
    public void setRefDocId(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.doc_test.ref_doc_id</code>.
     */
    public Integer getRefDocId() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DocTestRecord
     */
    public DocTestRecord() {
        super(DocTest.DOC_TEST);
    }

    /**
     * Create a detached, initialised DocTestRecord
     */
    public DocTestRecord(Integer docId, Integer tenantId, Integer accountId, String shortText, String longText, LocalDate date, Integer int_, Boolean isDone, JSON json, BigDecimal nr, String testTypeId, Integer refObjId, Integer refDocId) {
        super(DocTest.DOC_TEST);

        setDocId(docId);
        setTenantId(tenantId);
        setAccountId(accountId);
        setShortText(shortText);
        setLongText(longText);
        setDate(date);
        setInt(int_);
        setIsDone(isDone);
        setJson(json);
        setNr(nr);
        setTestTypeId(testTypeId);
        setRefObjId(refObjId);
        setRefDocId(refDocId);
        resetChangedOnNotNull();
    }
}
