/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.dms.model.db;


import io.zeitwert.fm.dms.model.db.tables.CodeContentKind;
import io.zeitwert.fm.dms.model.db.tables.CodeContentType;
import io.zeitwert.fm.dms.model.db.tables.CodeDocumentCategory;
import io.zeitwert.fm.dms.model.db.tables.CodeDocumentKind;
import io.zeitwert.fm.dms.model.db.tables.ObjDocument;
import io.zeitwert.fm.dms.model.db.tables.ObjDocumentPartContent;
import io.zeitwert.fm.dms.model.db.tables.ObjDocumentV;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.code_content_kind</code>.
     */
    public static final CodeContentKind CODE_CONTENT_KIND = CodeContentKind.CODE_CONTENT_KIND;

    /**
     * The table <code>public.code_content_type</code>.
     */
    public static final CodeContentType CODE_CONTENT_TYPE = CodeContentType.CODE_CONTENT_TYPE;

    /**
     * The table <code>public.code_document_category</code>.
     */
    public static final CodeDocumentCategory CODE_DOCUMENT_CATEGORY = CodeDocumentCategory.CODE_DOCUMENT_CATEGORY;

    /**
     * The table <code>public.code_document_kind</code>.
     */
    public static final CodeDocumentKind CODE_DOCUMENT_KIND = CodeDocumentKind.CODE_DOCUMENT_KIND;

    /**
     * The table <code>public.obj_document</code>.
     */
    public static final ObjDocument OBJ_DOCUMENT = ObjDocument.OBJ_DOCUMENT;

    /**
     * The table <code>public.obj_document_part_content</code>.
     */
    public static final ObjDocumentPartContent OBJ_DOCUMENT_PART_CONTENT = ObjDocumentPartContent.OBJ_DOCUMENT_PART_CONTENT;

    /**
     * The table <code>public.obj_document_v</code>.
     */
    public static final ObjDocumentV OBJ_DOCUMENT_V = ObjDocumentV.OBJ_DOCUMENT_V;
}
