/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.account.model.db.tables;


import io.zeitwert.fm.account.model.db.Keys;
import io.zeitwert.fm.account.model.db.Public;
import io.zeitwert.fm.account.model.db.tables.records.ObjAccountRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObjAccount extends TableImpl<ObjAccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.obj_account</code>
     */
    public static final ObjAccount OBJ_ACCOUNT = new ObjAccount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ObjAccountRecord> getRecordType() {
        return ObjAccountRecord.class;
    }

    /**
     * The column <code>public.obj_account.obj_id</code>.
     */
    public final TableField<ObjAccountRecord, Integer> OBJ_ID = createField(DSL.name("obj_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.obj_account.tenant_id</code>.
     */
    public final TableField<ObjAccountRecord, Integer> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.obj_account.intl_key</code>.
     */
    public final TableField<ObjAccountRecord, String> INTL_KEY = createField(DSL.name("intl_key"), SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>public.obj_account.name</code>.
     */
    public final TableField<ObjAccountRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.obj_account.description</code>.
     */
    public final TableField<ObjAccountRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.obj_account.account_type_id</code>.
     */
    public final TableField<ObjAccountRecord, String> ACCOUNT_TYPE_ID = createField(DSL.name("account_type_id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.obj_account.client_segment_id</code>.
     */
    public final TableField<ObjAccountRecord, String> CLIENT_SEGMENT_ID = createField(DSL.name("client_segment_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.obj_account.main_contact_id</code>.
     */
    public final TableField<ObjAccountRecord, Integer> MAIN_CONTACT_ID = createField(DSL.name("main_contact_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_account.reference_currency_id</code>.
     */
    public final TableField<ObjAccountRecord, String> REFERENCE_CURRENCY_ID = createField(DSL.name("reference_currency_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.obj_account.logo_img_id</code>.
     */
    public final TableField<ObjAccountRecord, Integer> LOGO_IMG_ID = createField(DSL.name("logo_img_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_account.banner_img_id</code>.
     */
    public final TableField<ObjAccountRecord, Integer> BANNER_IMG_ID = createField(DSL.name("banner_img_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_account.inflation_rate</code>.
     */
    public final TableField<ObjAccountRecord, BigDecimal> INFLATION_RATE = createField(DSL.name("inflation_rate"), SQLDataType.NUMERIC, this, "");

    private ObjAccount(Name alias, Table<ObjAccountRecord> aliased) {
        this(alias, aliased, null);
    }

    private ObjAccount(Name alias, Table<ObjAccountRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.obj_account</code> table reference
     */
    public ObjAccount(String alias) {
        this(DSL.name(alias), OBJ_ACCOUNT);
    }

    /**
     * Create an aliased <code>public.obj_account</code> table reference
     */
    public ObjAccount(Name alias) {
        this(alias, OBJ_ACCOUNT);
    }

    /**
     * Create a <code>public.obj_account</code> table reference
     */
    public ObjAccount() {
        this(DSL.name("obj_account"), null);
    }

    public <O extends Record> ObjAccount(Table<O> child, ForeignKey<O, ObjAccountRecord> key) {
        super(child, key, OBJ_ACCOUNT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<ObjAccountRecord> getPrimaryKey() {
        return Keys.OBJ_ACCOUNT_PKEY;
    }

    @Override
    public List<UniqueKey<ObjAccountRecord>> getKeys() {
        return Arrays.<UniqueKey<ObjAccountRecord>>asList(Keys.OBJ_ACCOUNT_PKEY);
    }

    @Override
    public List<ForeignKey<ObjAccountRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ObjAccountRecord, ?>>asList(Keys.OBJ_ACCOUNT__OBJ_ACCOUNT_ACCOUNT_TYPE_ID_FKEY, Keys.OBJ_ACCOUNT__OBJ_ACCOUNT_CLIENT_SEGMENT_ID_FKEY, Keys.OBJ_ACCOUNT__OBJ_ACCOUNT_REFERENCE_CURRENCY_ID_FKEY);
    }

    private transient CodeAccountType _codeAccountType;
    private transient CodeClientSegment _codeClientSegment;
    private transient CodeCurrency _codeCurrency;

    public CodeAccountType codeAccountType() {
        if (_codeAccountType == null)
            _codeAccountType = new CodeAccountType(this, Keys.OBJ_ACCOUNT__OBJ_ACCOUNT_ACCOUNT_TYPE_ID_FKEY);

        return _codeAccountType;
    }

    public CodeClientSegment codeClientSegment() {
        if (_codeClientSegment == null)
            _codeClientSegment = new CodeClientSegment(this, Keys.OBJ_ACCOUNT__OBJ_ACCOUNT_CLIENT_SEGMENT_ID_FKEY);

        return _codeClientSegment;
    }

    public CodeCurrency codeCurrency() {
        if (_codeCurrency == null)
            _codeCurrency = new CodeCurrency(this, Keys.OBJ_ACCOUNT__OBJ_ACCOUNT_REFERENCE_CURRENCY_ID_FKEY);

        return _codeCurrency;
    }

    @Override
    public ObjAccount as(String alias) {
        return new ObjAccount(DSL.name(alias), this);
    }

    @Override
    public ObjAccount as(Name alias) {
        return new ObjAccount(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjAccount rename(String name) {
        return new ObjAccount(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjAccount rename(Name name) {
        return new ObjAccount(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, Integer, String, String, String, String, String, Integer, String, Integer, Integer, BigDecimal> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
