/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.account.model.db.tables;


import io.zeitwert.fm.account.model.db.Public;
import io.zeitwert.fm.account.model.db.tables.records.ObjAccountVRecord;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row20;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObjAccountV extends TableImpl<ObjAccountVRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.obj_account_v</code>
     */
    public static final ObjAccountV OBJ_ACCOUNT_V = new ObjAccountV();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ObjAccountVRecord> getRecordType() {
        return ObjAccountVRecord.class;
    }

    /**
     * The column <code>public.obj_account_v.obj_type_id</code>.
     */
    public final TableField<ObjAccountVRecord, String> OBJ_TYPE_ID = createField(DSL.name("obj_type_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.obj_account_v.id</code>.
     */
    public final TableField<ObjAccountVRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_account_v.owner_id</code>.
     */
    public final TableField<ObjAccountVRecord, Integer> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_account_v.caption</code>.
     */
    public final TableField<ObjAccountVRecord, String> CAPTION = createField(DSL.name("caption"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.obj_account_v.created_by_user_id</code>.
     */
    public final TableField<ObjAccountVRecord, Integer> CREATED_BY_USER_ID = createField(DSL.name("created_by_user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_account_v.created_at</code>.
     */
    public final TableField<ObjAccountVRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.obj_account_v.modified_by_user_id</code>.
     */
    public final TableField<ObjAccountVRecord, Integer> MODIFIED_BY_USER_ID = createField(DSL.name("modified_by_user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_account_v.modified_at</code>.
     */
    public final TableField<ObjAccountVRecord, OffsetDateTime> MODIFIED_AT = createField(DSL.name("modified_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.obj_account_v.closed_by_user_id</code>.
     */
    public final TableField<ObjAccountVRecord, Integer> CLOSED_BY_USER_ID = createField(DSL.name("closed_by_user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_account_v.closed_at</code>.
     */
    public final TableField<ObjAccountVRecord, OffsetDateTime> CLOSED_AT = createField(DSL.name("closed_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.obj_account_v.account_id</code>.
     */
    public final TableField<ObjAccountVRecord, Integer> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_account_v.obj_id</code>.
     */
    public final TableField<ObjAccountVRecord, Integer> OBJ_ID = createField(DSL.name("obj_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_account_v.tenant_id</code>.
     */
    public final TableField<ObjAccountVRecord, Integer> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_account_v.intl_key</code>.
     */
    public final TableField<ObjAccountVRecord, String> INTL_KEY = createField(DSL.name("intl_key"), SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>public.obj_account_v.name</code>.
     */
    public final TableField<ObjAccountVRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.obj_account_v.description</code>.
     */
    public final TableField<ObjAccountVRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.obj_account_v.account_type_id</code>.
     */
    public final TableField<ObjAccountVRecord, String> ACCOUNT_TYPE_ID = createField(DSL.name("account_type_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.obj_account_v.client_segment_id</code>.
     */
    public final TableField<ObjAccountVRecord, String> CLIENT_SEGMENT_ID = createField(DSL.name("client_segment_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.obj_account_v.main_contact_id</code>.
     */
    public final TableField<ObjAccountVRecord, Integer> MAIN_CONTACT_ID = createField(DSL.name("main_contact_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_account_v.reference_currency_id</code>.
     */
    public final TableField<ObjAccountVRecord, String> REFERENCE_CURRENCY_ID = createField(DSL.name("reference_currency_id"), SQLDataType.VARCHAR(40), this, "");

    private ObjAccountV(Name alias, Table<ObjAccountVRecord> aliased) {
        this(alias, aliased, null);
    }

    private ObjAccountV(Name alias, Table<ObjAccountVRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("create view \"obj_account_v\" as  SELECT obj.obj_type_id,\n    a.obj_id AS id,\n    obj.owner_id,\n    obj.caption,\n    obj.created_by_user_id,\n    obj.created_at,\n    obj.modified_by_user_id,\n    obj.modified_at,\n    obj.closed_by_user_id,\n    obj.closed_at,\n    a.obj_id AS account_id,\n    a.obj_id,\n    a.tenant_id,\n    a.intl_key,\n    a.name,\n    a.description,\n    a.account_type_id,\n    a.client_segment_id,\n    a.main_contact_id,\n    a.reference_currency_id\n   FROM (obj_account a\n     JOIN obj ON ((obj.id = a.obj_id)));"));
    }

    /**
     * Create an aliased <code>public.obj_account_v</code> table reference
     */
    public ObjAccountV(String alias) {
        this(DSL.name(alias), OBJ_ACCOUNT_V);
    }

    /**
     * Create an aliased <code>public.obj_account_v</code> table reference
     */
    public ObjAccountV(Name alias) {
        this(alias, OBJ_ACCOUNT_V);
    }

    /**
     * Create a <code>public.obj_account_v</code> table reference
     */
    public ObjAccountV() {
        this(DSL.name("obj_account_v"), null);
    }

    public <O extends Record> ObjAccountV(Table<O> child, ForeignKey<O, ObjAccountVRecord> key) {
        super(child, key, OBJ_ACCOUNT_V);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public ObjAccountV as(String alias) {
        return new ObjAccountV(DSL.name(alias), this);
    }

    @Override
    public ObjAccountV as(Name alias) {
        return new ObjAccountV(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjAccountV rename(String name) {
        return new ObjAccountV(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjAccountV rename(Name name) {
        return new ObjAccountV(name, null);
    }

    // -------------------------------------------------------------------------
    // Row20 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row20<String, Integer, Integer, String, Integer, OffsetDateTime, Integer, OffsetDateTime, Integer, OffsetDateTime, Integer, Integer, Integer, String, String, String, String, String, Integer, String> fieldsRow() {
        return (Row20) super.fieldsRow();
    }
}
