/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.building.model.db.tables;


import io.zeitwert.fm.building.model.db.Keys;
import io.zeitwert.fm.building.model.db.Public;
import io.zeitwert.fm.building.model.db.tables.ObjBuildingPartRating.ObjBuildingPartRatingPath;
import io.zeitwert.fm.building.model.db.tables.records.CodeBuildingMaintenanceStrategyRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeBuildingMaintenanceStrategy extends TableImpl<CodeBuildingMaintenanceStrategyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.code_building_maintenance_strategy</code>
     */
    public static final CodeBuildingMaintenanceStrategy CODE_BUILDING_MAINTENANCE_STRATEGY = new CodeBuildingMaintenanceStrategy();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeBuildingMaintenanceStrategyRecord> getRecordType() {
        return CodeBuildingMaintenanceStrategyRecord.class;
    }

    /**
     * The column <code>public.code_building_maintenance_strategy.id</code>.
     */
    public final TableField<CodeBuildingMaintenanceStrategyRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.code_building_maintenance_strategy.name</code>.
     */
    public final TableField<CodeBuildingMaintenanceStrategyRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private CodeBuildingMaintenanceStrategy(Name alias, Table<CodeBuildingMaintenanceStrategyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CodeBuildingMaintenanceStrategy(Name alias, Table<CodeBuildingMaintenanceStrategyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.code_building_maintenance_strategy</code>
     * table reference
     */
    public CodeBuildingMaintenanceStrategy(String alias) {
        this(DSL.name(alias), CODE_BUILDING_MAINTENANCE_STRATEGY);
    }

    /**
     * Create an aliased <code>public.code_building_maintenance_strategy</code>
     * table reference
     */
    public CodeBuildingMaintenanceStrategy(Name alias) {
        this(alias, CODE_BUILDING_MAINTENANCE_STRATEGY);
    }

    /**
     * Create a <code>public.code_building_maintenance_strategy</code> table
     * reference
     */
    public CodeBuildingMaintenanceStrategy() {
        this(DSL.name("code_building_maintenance_strategy"), null);
    }

    public <O extends Record> CodeBuildingMaintenanceStrategy(Table<O> path, ForeignKey<O, CodeBuildingMaintenanceStrategyRecord> childPath, InverseForeignKey<O, CodeBuildingMaintenanceStrategyRecord> parentPath) {
        super(path, childPath, parentPath, CODE_BUILDING_MAINTENANCE_STRATEGY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CodeBuildingMaintenanceStrategyPath extends CodeBuildingMaintenanceStrategy implements Path<CodeBuildingMaintenanceStrategyRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CodeBuildingMaintenanceStrategyPath(Table<O> path, ForeignKey<O, CodeBuildingMaintenanceStrategyRecord> childPath, InverseForeignKey<O, CodeBuildingMaintenanceStrategyRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CodeBuildingMaintenanceStrategyPath(Name alias, Table<CodeBuildingMaintenanceStrategyRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CodeBuildingMaintenanceStrategyPath as(String alias) {
            return new CodeBuildingMaintenanceStrategyPath(DSL.name(alias), this);
        }

        @Override
        public CodeBuildingMaintenanceStrategyPath as(Name alias) {
            return new CodeBuildingMaintenanceStrategyPath(alias, this);
        }

        @Override
        public CodeBuildingMaintenanceStrategyPath as(Table<?> alias) {
            return new CodeBuildingMaintenanceStrategyPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CodeBuildingMaintenanceStrategyRecord> getPrimaryKey() {
        return Keys.CODE_BUILDING_MAINTENANCE_STRATEGY_PKEY;
    }

    private transient ObjBuildingPartRatingPath _objBuildingPartRating;

    /**
     * Get the implicit to-many join path to the
     * <code>public.obj_building_part_rating</code> table
     */
    public ObjBuildingPartRatingPath objBuildingPartRating() {
        if (_objBuildingPartRating == null)
            _objBuildingPartRating = new ObjBuildingPartRatingPath(this, null, Keys.OBJ_BUILDING_PART_RATING__OBJ_BUILDING_PART_RATING_MAINTENANCE_STRATEGY_ID_FKEY.getInverseKey());

        return _objBuildingPartRating;
    }

    @Override
    public CodeBuildingMaintenanceStrategy as(String alias) {
        return new CodeBuildingMaintenanceStrategy(DSL.name(alias), this);
    }

    @Override
    public CodeBuildingMaintenanceStrategy as(Name alias) {
        return new CodeBuildingMaintenanceStrategy(alias, this);
    }

    @Override
    public CodeBuildingMaintenanceStrategy as(Table<?> alias) {
        return new CodeBuildingMaintenanceStrategy(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeBuildingMaintenanceStrategy rename(String name) {
        return new CodeBuildingMaintenanceStrategy(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeBuildingMaintenanceStrategy rename(Name name) {
        return new CodeBuildingMaintenanceStrategy(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeBuildingMaintenanceStrategy rename(Table<?> name) {
        return new CodeBuildingMaintenanceStrategy(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeBuildingMaintenanceStrategy where(Condition condition) {
        return new CodeBuildingMaintenanceStrategy(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeBuildingMaintenanceStrategy where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeBuildingMaintenanceStrategy where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeBuildingMaintenanceStrategy where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeBuildingMaintenanceStrategy where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeBuildingMaintenanceStrategy where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeBuildingMaintenanceStrategy where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeBuildingMaintenanceStrategy where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeBuildingMaintenanceStrategy whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeBuildingMaintenanceStrategy whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
