/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.building.model.db.tables;


import io.zeitwert.fm.building.model.db.Keys;
import io.zeitwert.fm.building.model.db.Public;
import io.zeitwert.fm.building.model.db.tables.ObjBuildingPartElementRating.ObjBuildingPartElementRatingPath;
import io.zeitwert.fm.building.model.db.tables.records.CodeBuildingPartRecord;

import java.math.BigDecimal;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeBuildingPart extends TableImpl<CodeBuildingPartRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.code_building_part</code>
     */
    public static final CodeBuildingPart CODE_BUILDING_PART = new CodeBuildingPart();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeBuildingPartRecord> getRecordType() {
        return CodeBuildingPartRecord.class;
    }

    /**
     * The column <code>public.code_building_part.id</code>.
     */
    public final TableField<CodeBuildingPartRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.name</code>.
     */
    public final TableField<CodeBuildingPartRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.opt_restore_duration</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> OPT_RESTORE_DURATION = createField(DSL.name("opt_restore_duration"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.opt_restore_time_value</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> OPT_RESTORE_TIME_VALUE = createField(DSL.name("opt_restore_time_value"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.max_restore_duration</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> MAX_RESTORE_DURATION = createField(DSL.name("max_restore_duration"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.max_restore_time_value</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> MAX_RESTORE_TIME_VALUE = createField(DSL.name("max_restore_time_value"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column
     * <code>public.code_building_part.after_restore_time_value</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> AFTER_RESTORE_TIME_VALUE = createField(DSL.name("after_restore_time_value"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.restore_cost_perc</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> RESTORE_COST_PERC = createField(DSL.name("restore_cost_perc"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.new_build_cost_perc</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> NEW_BUILD_COST_PERC = createField(DSL.name("new_build_cost_perc"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.linear_duration</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> LINEAR_DURATION = createField(DSL.name("linear_duration"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.linear_time_value</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> LINEAR_TIME_VALUE = createField(DSL.name("linear_time_value"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.c10</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> C10 = createField(DSL.name("c10"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.c9</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> C9 = createField(DSL.name("c9"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.c8</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> C8 = createField(DSL.name("c8"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.c7</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> C7 = createField(DSL.name("c7"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.c6</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> C6 = createField(DSL.name("c6"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.c5</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> C5 = createField(DSL.name("c5"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.c4</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> C4 = createField(DSL.name("c4"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.c3</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> C3 = createField(DSL.name("c3"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.c2</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> C2 = createField(DSL.name("c2"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.c1</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> C1 = createField(DSL.name("c1"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.code_building_part.c0</code>.
     */
    public final TableField<CodeBuildingPartRecord, BigDecimal> C0 = createField(DSL.name("c0"), SQLDataType.NUMERIC.nullable(false), this, "");

    private CodeBuildingPart(Name alias, Table<CodeBuildingPartRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CodeBuildingPart(Name alias, Table<CodeBuildingPartRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.code_building_part</code> table reference
     */
    public CodeBuildingPart(String alias) {
        this(DSL.name(alias), CODE_BUILDING_PART);
    }

    /**
     * Create an aliased <code>public.code_building_part</code> table reference
     */
    public CodeBuildingPart(Name alias) {
        this(alias, CODE_BUILDING_PART);
    }

    /**
     * Create a <code>public.code_building_part</code> table reference
     */
    public CodeBuildingPart() {
        this(DSL.name("code_building_part"), null);
    }

    public <O extends Record> CodeBuildingPart(Table<O> path, ForeignKey<O, CodeBuildingPartRecord> childPath, InverseForeignKey<O, CodeBuildingPartRecord> parentPath) {
        super(path, childPath, parentPath, CODE_BUILDING_PART);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CodeBuildingPartPath extends CodeBuildingPart implements Path<CodeBuildingPartRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CodeBuildingPartPath(Table<O> path, ForeignKey<O, CodeBuildingPartRecord> childPath, InverseForeignKey<O, CodeBuildingPartRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CodeBuildingPartPath(Name alias, Table<CodeBuildingPartRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CodeBuildingPartPath as(String alias) {
            return new CodeBuildingPartPath(DSL.name(alias), this);
        }

        @Override
        public CodeBuildingPartPath as(Name alias) {
            return new CodeBuildingPartPath(alias, this);
        }

        @Override
        public CodeBuildingPartPath as(Table<?> alias) {
            return new CodeBuildingPartPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CodeBuildingPartRecord> getPrimaryKey() {
        return Keys.CODE_BUILDING_PART_PKEY;
    }

    private transient ObjBuildingPartElementRatingPath _objBuildingPartElementRating;

    /**
     * Get the implicit to-many join path to the
     * <code>public.obj_building_part_element_rating</code> table
     */
    public ObjBuildingPartElementRatingPath objBuildingPartElementRating() {
        if (_objBuildingPartElementRating == null)
            _objBuildingPartElementRating = new ObjBuildingPartElementRatingPath(this, null, Keys.OBJ_BUILDING_PART_ELEMENT_RATING__OBJ_BUILDING_PART_ELEMENT_RATING_BUILDING_PART_ID_FKEY.getInverseKey());

        return _objBuildingPartElementRating;
    }

    @Override
    public CodeBuildingPart as(String alias) {
        return new CodeBuildingPart(DSL.name(alias), this);
    }

    @Override
    public CodeBuildingPart as(Name alias) {
        return new CodeBuildingPart(alias, this);
    }

    @Override
    public CodeBuildingPart as(Table<?> alias) {
        return new CodeBuildingPart(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeBuildingPart rename(String name) {
        return new CodeBuildingPart(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeBuildingPart rename(Name name) {
        return new CodeBuildingPart(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeBuildingPart rename(Table<?> name) {
        return new CodeBuildingPart(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeBuildingPart where(Condition condition) {
        return new CodeBuildingPart(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeBuildingPart where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeBuildingPart where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeBuildingPart where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeBuildingPart where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeBuildingPart where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeBuildingPart where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeBuildingPart where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeBuildingPart whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeBuildingPart whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
