/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.building.model.db.tables;


import io.zeitwert.fm.building.model.db.Keys;
import io.zeitwert.fm.building.model.db.Public;
import io.zeitwert.fm.building.model.db.tables.CodeBuildingType.CodeBuildingTypePath;
import io.zeitwert.fm.building.model.db.tables.ObjBuilding.ObjBuildingPath;
import io.zeitwert.fm.building.model.db.tables.records.CodeBuildingSubTypeRecord;
import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class CodeBuildingSubType extends TableImpl<CodeBuildingSubTypeRecord> {

	/**
	 * The reference instance of <code>public.code_building_sub_type</code>
	 */
	public static final CodeBuildingSubType CODE_BUILDING_SUB_TYPE = new CodeBuildingSubType();
	private static final long serialVersionUID = 1L;
	/**
	 * The column <code>public.code_building_sub_type.id</code>.
	 */
	public final TableField<CodeBuildingSubTypeRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "");
	/**
	 * The column <code>public.code_building_sub_type.name</code>.
	 */
	public final TableField<CodeBuildingSubTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");
	/**
	 * The column <code>public.code_building_sub_type.building_type_id</code>.
	 */
	public final TableField<CodeBuildingSubTypeRecord, String> BUILDING_TYPE_ID = createField(DSL.name("building_type_id"), SQLDataType.VARCHAR(40).nullable(false), this, "");
	private transient CodeBuildingTypePath _codeBuildingType;
	private transient ObjBuildingPath _objBuilding;

	private CodeBuildingSubType(Name alias, Table<CodeBuildingSubTypeRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private CodeBuildingSubType(Name alias, Table<CodeBuildingSubTypeRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>public.code_building_sub_type</code> table
	 * reference
	 */
	public CodeBuildingSubType(String alias) {
		this(DSL.name(alias), CODE_BUILDING_SUB_TYPE);
	}

	/**
	 * Create an aliased <code>public.code_building_sub_type</code> table
	 * reference
	 */
	public CodeBuildingSubType(Name alias) {
		this(alias, CODE_BUILDING_SUB_TYPE);
	}

	/**
	 * Create a <code>public.code_building_sub_type</code> table reference
	 */
	public CodeBuildingSubType() {
		this(DSL.name("code_building_sub_type"), null);
	}

	public <O extends Record> CodeBuildingSubType(Table<O> path, ForeignKey<O, CodeBuildingSubTypeRecord> childPath, InverseForeignKey<O, CodeBuildingSubTypeRecord> parentPath) {
		super(path, childPath, parentPath, CODE_BUILDING_SUB_TYPE);
	}

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CodeBuildingSubTypeRecord> getRecordType() {
		return CodeBuildingSubTypeRecord.class;
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : Public.PUBLIC;
	}

	@Override
	public UniqueKey<CodeBuildingSubTypeRecord> getPrimaryKey() {
		return Keys.CODE_BUILDING_SUB_TYPE_PKEY;
	}

	@Override
	public List<ForeignKey<CodeBuildingSubTypeRecord, ?>> getReferences() {
		return Arrays.asList(Keys.CODE_BUILDING_SUB_TYPE__CODE_BUILDING_SUB_TYPE_BUILDING_TYPE_ID_FKEY);
	}

	/**
	 * Get the implicit join path to the <code>public.code_building_type</code>
	 * table.
	 */
	public CodeBuildingTypePath codeBuildingType() {
		if (_codeBuildingType == null)
			_codeBuildingType = new CodeBuildingTypePath(this, Keys.CODE_BUILDING_SUB_TYPE__CODE_BUILDING_SUB_TYPE_BUILDING_TYPE_ID_FKEY, null);

		return _codeBuildingType;
	}

	/**
	 * Get the implicit to-many join path to the
	 * <code>public.obj_building</code> table
	 */
	public ObjBuildingPath objBuilding() {
		if (_objBuilding == null)
			_objBuilding = new ObjBuildingPath(this, null, Keys.OBJ_BUILDING__OBJ_BUILDING_BUILDING_SUB_TYPE_ID_FKEY.getInverseKey());

		return _objBuilding;
	}

	@Override
	public CodeBuildingSubType as(String alias) {
		return new CodeBuildingSubType(DSL.name(alias), this);
	}

	@Override
	public CodeBuildingSubType as(Name alias) {
		return new CodeBuildingSubType(alias, this);
	}

	@Override
	public CodeBuildingSubType as(Table<?> alias) {
		return new CodeBuildingSubType(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CodeBuildingSubType rename(String name) {
		return new CodeBuildingSubType(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CodeBuildingSubType rename(Name name) {
		return new CodeBuildingSubType(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CodeBuildingSubType rename(Table<?> name) {
		return new CodeBuildingSubType(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CodeBuildingSubType where(Condition condition) {
		return new CodeBuildingSubType(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CodeBuildingSubType where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CodeBuildingSubType where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CodeBuildingSubType where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CodeBuildingSubType where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CodeBuildingSubType where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CodeBuildingSubType where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CodeBuildingSubType where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CodeBuildingSubType whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CodeBuildingSubType whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class CodeBuildingSubTypePath extends CodeBuildingSubType implements Path<CodeBuildingSubTypeRecord> {

		private static final long serialVersionUID = 1L;

		public <O extends Record> CodeBuildingSubTypePath(Table<O> path, ForeignKey<O, CodeBuildingSubTypeRecord> childPath, InverseForeignKey<O, CodeBuildingSubTypeRecord> parentPath) {
			super(path, childPath, parentPath);
		}

		private CodeBuildingSubTypePath(Name alias, Table<CodeBuildingSubTypeRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public CodeBuildingSubTypePath as(String alias) {
			return new CodeBuildingSubTypePath(DSL.name(alias), this);
		}

		@Override
		public CodeBuildingSubTypePath as(Name alias) {
			return new CodeBuildingSubTypePath(alias, this);
		}

		@Override
		public CodeBuildingSubTypePath as(Table<?> alias) {
			return new CodeBuildingSubTypePath(alias.getQualifiedName(), this);
		}

	}

}
