/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.building.model.db.tables;


import io.zeitwert.fm.building.model.db.Keys;
import io.zeitwert.fm.building.model.db.Public;
import io.zeitwert.fm.building.model.db.tables.ObjBuilding.ObjBuildingPath;
import io.zeitwert.fm.building.model.db.tables.records.CodeHistoricPreservationRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeHistoricPreservation extends TableImpl<CodeHistoricPreservationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.code_historic_preservation</code>
     */
    public static final CodeHistoricPreservation CODE_HISTORIC_PRESERVATION = new CodeHistoricPreservation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeHistoricPreservationRecord> getRecordType() {
        return CodeHistoricPreservationRecord.class;
    }

    /**
     * The column <code>public.code_historic_preservation.id</code>.
     */
    public final TableField<CodeHistoricPreservationRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.code_historic_preservation.name</code>.
     */
    public final TableField<CodeHistoricPreservationRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private CodeHistoricPreservation(Name alias, Table<CodeHistoricPreservationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CodeHistoricPreservation(Name alias, Table<CodeHistoricPreservationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.code_historic_preservation</code> table
     * reference
     */
    public CodeHistoricPreservation(String alias) {
        this(DSL.name(alias), CODE_HISTORIC_PRESERVATION);
    }

    /**
     * Create an aliased <code>public.code_historic_preservation</code> table
     * reference
     */
    public CodeHistoricPreservation(Name alias) {
        this(alias, CODE_HISTORIC_PRESERVATION);
    }

    /**
     * Create a <code>public.code_historic_preservation</code> table reference
     */
    public CodeHistoricPreservation() {
        this(DSL.name("code_historic_preservation"), null);
    }

    public <O extends Record> CodeHistoricPreservation(Table<O> path, ForeignKey<O, CodeHistoricPreservationRecord> childPath, InverseForeignKey<O, CodeHistoricPreservationRecord> parentPath) {
        super(path, childPath, parentPath, CODE_HISTORIC_PRESERVATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CodeHistoricPreservationPath extends CodeHistoricPreservation implements Path<CodeHistoricPreservationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CodeHistoricPreservationPath(Table<O> path, ForeignKey<O, CodeHistoricPreservationRecord> childPath, InverseForeignKey<O, CodeHistoricPreservationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CodeHistoricPreservationPath(Name alias, Table<CodeHistoricPreservationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CodeHistoricPreservationPath as(String alias) {
            return new CodeHistoricPreservationPath(DSL.name(alias), this);
        }

        @Override
        public CodeHistoricPreservationPath as(Name alias) {
            return new CodeHistoricPreservationPath(alias, this);
        }

        @Override
        public CodeHistoricPreservationPath as(Table<?> alias) {
            return new CodeHistoricPreservationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CodeHistoricPreservationRecord> getPrimaryKey() {
        return Keys.CODE_HISTORIC_PRESERVATION_PKEY;
    }

    private transient ObjBuildingPath _objBuilding;

    /**
     * Get the implicit to-many join path to the
     * <code>public.obj_building</code> table
     */
    public ObjBuildingPath objBuilding() {
        if (_objBuilding == null)
            _objBuilding = new ObjBuildingPath(this, null, Keys.OBJ_BUILDING__OBJ_BUILDING_HISTORIC_PRESERVATION_ID_FKEY.getInverseKey());

        return _objBuilding;
    }

    @Override
    public CodeHistoricPreservation as(String alias) {
        return new CodeHistoricPreservation(DSL.name(alias), this);
    }

    @Override
    public CodeHistoricPreservation as(Name alias) {
        return new CodeHistoricPreservation(alias, this);
    }

    @Override
    public CodeHistoricPreservation as(Table<?> alias) {
        return new CodeHistoricPreservation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeHistoricPreservation rename(String name) {
        return new CodeHistoricPreservation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeHistoricPreservation rename(Name name) {
        return new CodeHistoricPreservation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeHistoricPreservation rename(Table<?> name) {
        return new CodeHistoricPreservation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeHistoricPreservation where(Condition condition) {
        return new CodeHistoricPreservation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeHistoricPreservation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeHistoricPreservation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeHistoricPreservation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeHistoricPreservation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeHistoricPreservation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeHistoricPreservation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeHistoricPreservation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeHistoricPreservation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeHistoricPreservation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
