/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.building.model.db.tables;


import io.zeitwert.fm.building.model.db.Indexes;
import io.zeitwert.fm.building.model.db.Keys;
import io.zeitwert.fm.building.model.db.Public;
import io.zeitwert.fm.building.model.db.tables.CodeBuildingSubType.CodeBuildingSubTypePath;
import io.zeitwert.fm.building.model.db.tables.CodeBuildingType.CodeBuildingTypePath;
import io.zeitwert.fm.building.model.db.tables.CodeHistoricPreservation.CodeHistoricPreservationPath;
import io.zeitwert.fm.building.model.db.tables.ObjBuildingPartElementRating.ObjBuildingPartElementRatingPath;
import io.zeitwert.fm.building.model.db.tables.ObjBuildingPartRating.ObjBuildingPartRatingPath;
import io.zeitwert.fm.building.model.db.tables.records.ObjBuildingRecord;
import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ObjBuilding extends TableImpl<ObjBuildingRecord> {

	/**
	 * The reference instance of <code>public.obj_building</code>
	 */
	public static final ObjBuilding OBJ_BUILDING = new ObjBuilding();
	private static final long serialVersionUID = 1L;
	/**
	 * The column <code>public.obj_building.obj_id</code>.
	 */
	public final TableField<ObjBuildingRecord, Integer> OBJ_ID = createField(DSL.name("obj_id"), SQLDataType.INTEGER.nullable(false), this, "");
	/**
	 * The column <code>public.obj_building.tenant_id</code>.
	 */
	public final TableField<ObjBuildingRecord, Integer> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.INTEGER.nullable(false), this, "");
	/**
	 * The column <code>public.obj_building.account_id</code>.
	 */
	public final TableField<ObjBuildingRecord, Integer> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.INTEGER.nullable(false), this, "");
	/**
	 * The column <code>public.obj_building.name</code>.
	 */
	public final TableField<ObjBuildingRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100), this, "");
	/**
	 * The column <code>public.obj_building.description</code>.
	 */
	public final TableField<ObjBuildingRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");
	/**
	 * The column <code>public.obj_building.building_nr</code>.
	 */
	public final TableField<ObjBuildingRecord, String> BUILDING_NR = createField(DSL.name("building_nr"), SQLDataType.VARCHAR(200), this, "");
	/**
	 * The column <code>public.obj_building.insurance_nr</code>.
	 */
	public final TableField<ObjBuildingRecord, String> INSURANCE_NR = createField(DSL.name("insurance_nr"), SQLDataType.VARCHAR(200), this, "");
	/**
	 * The column <code>public.obj_building.plot_nr</code>.
	 */
	public final TableField<ObjBuildingRecord, String> PLOT_NR = createField(DSL.name("plot_nr"), SQLDataType.VARCHAR(200), this, "");
	/**
	 * The column <code>public.obj_building.national_building_id</code>.
	 */
	public final TableField<ObjBuildingRecord, String> NATIONAL_BUILDING_ID = createField(DSL.name("national_building_id"), SQLDataType.VARCHAR(200), this, "");
	/**
	 * The column <code>public.obj_building.historic_preservation_id</code>.
	 */
	public final TableField<ObjBuildingRecord, String> HISTORIC_PRESERVATION_ID = createField(DSL.name("historic_preservation_id"), SQLDataType.VARCHAR(40), this, "");
	/**
	 * The column <code>public.obj_building.street</code>.
	 */
	public final TableField<ObjBuildingRecord, String> STREET = createField(DSL.name("street"), SQLDataType.VARCHAR(100), this, "");
	/**
	 * The column <code>public.obj_building.zip</code>.
	 */
	public final TableField<ObjBuildingRecord, String> ZIP = createField(DSL.name("zip"), SQLDataType.VARCHAR(60), this, "");
	/**
	 * The column <code>public.obj_building.city</code>.
	 */
	public final TableField<ObjBuildingRecord, String> CITY = createField(DSL.name("city"), SQLDataType.VARCHAR(60), this, "");
	/**
	 * The column <code>public.obj_building.country_id</code>.
	 */
	public final TableField<ObjBuildingRecord, String> COUNTRY_ID = createField(DSL.name("country_id"), SQLDataType.VARCHAR(40).nullable(false), this, "");
	/**
	 * The column <code>public.obj_building.geo_address</code>.
	 */
	public final TableField<ObjBuildingRecord, String> GEO_ADDRESS = createField(DSL.name("geo_address"), SQLDataType.VARCHAR(200), this, "");
	/**
	 * The column <code>public.obj_building.geo_coordinates</code>.
	 */
	public final TableField<ObjBuildingRecord, String> GEO_COORDINATES = createField(DSL.name("geo_coordinates"), SQLDataType.VARCHAR(200), this, "");
	/**
	 * The column <code>public.obj_building.geo_zoom</code>.
	 */
	public final TableField<ObjBuildingRecord, Integer> GEO_ZOOM = createField(DSL.name("geo_zoom"), SQLDataType.INTEGER, this, "");
	/**
	 * The column <code>public.obj_building.cover_foto_id</code>.
	 */
	public final TableField<ObjBuildingRecord, Integer> COVER_FOTO_ID = createField(DSL.name("cover_foto_id"), SQLDataType.INTEGER.nullable(false), this, "");
	/**
	 * The column <code>public.obj_building.currency_id</code>.
	 */
	public final TableField<ObjBuildingRecord, String> CURRENCY_ID = createField(DSL.name("currency_id"), SQLDataType.VARCHAR(40).nullable(false), this, "");
	/**
	 * The column <code>public.obj_building.volume</code>.
	 */
	public final TableField<ObjBuildingRecord, BigDecimal> VOLUME = createField(DSL.name("volume"), SQLDataType.NUMERIC, this, "");
	/**
	 * The column <code>public.obj_building.area_gross</code>.
	 */
	public final TableField<ObjBuildingRecord, BigDecimal> AREA_GROSS = createField(DSL.name("area_gross"), SQLDataType.NUMERIC, this, "");
	/**
	 * The column <code>public.obj_building.area_net</code>.
	 */
	public final TableField<ObjBuildingRecord, BigDecimal> AREA_NET = createField(DSL.name("area_net"), SQLDataType.NUMERIC, this, "");
	/**
	 * The column <code>public.obj_building.nr_of_floors_above_ground</code>.
	 */
	public final TableField<ObjBuildingRecord, Integer> NR_OF_FLOORS_ABOVE_GROUND = createField(DSL.name("nr_of_floors_above_ground"), SQLDataType.INTEGER, this, "");
	/**
	 * The column <code>public.obj_building.nr_of_floors_below_ground</code>.
	 */
	public final TableField<ObjBuildingRecord, Integer> NR_OF_FLOORS_BELOW_GROUND = createField(DSL.name("nr_of_floors_below_ground"), SQLDataType.INTEGER, this, "");
	/**
	 * The column <code>public.obj_building.building_type_id</code>.
	 */
	public final TableField<ObjBuildingRecord, String> BUILDING_TYPE_ID = createField(DSL.name("building_type_id"), SQLDataType.VARCHAR(40), this, "");
	/**
	 * The column <code>public.obj_building.building_sub_type_id</code>.
	 */
	public final TableField<ObjBuildingRecord, String> BUILDING_SUB_TYPE_ID = createField(DSL.name("building_sub_type_id"), SQLDataType.VARCHAR(40), this, "");
	/**
	 * The column <code>public.obj_building.building_year</code>.
	 */
	public final TableField<ObjBuildingRecord, Integer> BUILDING_YEAR = createField(DSL.name("building_year"), SQLDataType.INTEGER, this, "");
	/**
	 * The column <code>public.obj_building.insured_value</code>.
	 */
	public final TableField<ObjBuildingRecord, BigDecimal> INSURED_VALUE = createField(DSL.name("insured_value"), SQLDataType.NUMERIC, this, "");
	/**
	 * The column <code>public.obj_building.insured_value_year</code>.
	 */
	public final TableField<ObjBuildingRecord, Integer> INSURED_VALUE_YEAR = createField(DSL.name("insured_value_year"), SQLDataType.INTEGER, this, "");
	/**
	 * The column <code>public.obj_building.not_insured_value</code>.
	 */
	public final TableField<ObjBuildingRecord, BigDecimal> NOT_INSURED_VALUE = createField(DSL.name("not_insured_value"), SQLDataType.NUMERIC, this, "");
	/**
	 * The column <code>public.obj_building.not_insured_value_year</code>.
	 */
	public final TableField<ObjBuildingRecord, Integer> NOT_INSURED_VALUE_YEAR = createField(DSL.name("not_insured_value_year"), SQLDataType.INTEGER, this, "");
	/**
	 * The column <code>public.obj_building.third_party_value</code>.
	 */
	public final TableField<ObjBuildingRecord, BigDecimal> THIRD_PARTY_VALUE = createField(DSL.name("third_party_value"), SQLDataType.NUMERIC, this, "");
	/**
	 * The column <code>public.obj_building.third_party_value_year</code>.
	 */
	public final TableField<ObjBuildingRecord, Integer> THIRD_PARTY_VALUE_YEAR = createField(DSL.name("third_party_value_year"), SQLDataType.INTEGER, this, "");
	private transient CodeBuildingSubTypePath _codeBuildingSubType;
	private transient CodeBuildingTypePath _codeBuildingType;
	private transient CodeHistoricPreservationPath _codeHistoricPreservation;
	private transient ObjBuildingPartElementRatingPath _objBuildingPartElementRating;
	private transient ObjBuildingPartRatingPath _objBuildingPartRating;

	private ObjBuilding(Name alias, Table<ObjBuildingRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private ObjBuilding(Name alias, Table<ObjBuildingRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>public.obj_building</code> table reference
	 */
	public ObjBuilding(String alias) {
		this(DSL.name(alias), OBJ_BUILDING);
	}

	/**
	 * Create an aliased <code>public.obj_building</code> table reference
	 */
	public ObjBuilding(Name alias) {
		this(alias, OBJ_BUILDING);
	}

	/**
	 * Create a <code>public.obj_building</code> table reference
	 */
	public ObjBuilding() {
		this(DSL.name("obj_building"), null);
	}

	public <O extends Record> ObjBuilding(Table<O> path, ForeignKey<O, ObjBuildingRecord> childPath, InverseForeignKey<O, ObjBuildingRecord> parentPath) {
		super(path, childPath, parentPath, OBJ_BUILDING);
	}

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ObjBuildingRecord> getRecordType() {
		return ObjBuildingRecord.class;
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : Public.PUBLIC;
	}

	@Override
	public List<Index> getIndexes() {
		return Arrays.asList(Indexes.OBJ_BUILDING$ACCOUNT);
	}

	@Override
	public UniqueKey<ObjBuildingRecord> getPrimaryKey() {
		return Keys.OBJ_BUILDING_PKEY;
	}

	@Override
	public List<ForeignKey<ObjBuildingRecord, ?>> getReferences() {
		return Arrays.asList(Keys.OBJ_BUILDING__OBJ_BUILDING_BUILDING_SUB_TYPE_ID_FKEY, Keys.OBJ_BUILDING__OBJ_BUILDING_BUILDING_TYPE_ID_FKEY, Keys.OBJ_BUILDING__OBJ_BUILDING_HISTORIC_PRESERVATION_ID_FKEY);
	}

	/**
	 * Get the implicit join path to the
	 * <code>public.code_building_sub_type</code> table.
	 */
	public CodeBuildingSubTypePath codeBuildingSubType() {
		if (_codeBuildingSubType == null)
			_codeBuildingSubType = new CodeBuildingSubTypePath(this, Keys.OBJ_BUILDING__OBJ_BUILDING_BUILDING_SUB_TYPE_ID_FKEY, null);

		return _codeBuildingSubType;
	}

	/**
	 * Get the implicit join path to the <code>public.code_building_type</code>
	 * table.
	 */
	public CodeBuildingTypePath codeBuildingType() {
		if (_codeBuildingType == null)
			_codeBuildingType = new CodeBuildingTypePath(this, Keys.OBJ_BUILDING__OBJ_BUILDING_BUILDING_TYPE_ID_FKEY, null);

		return _codeBuildingType;
	}

	/**
	 * Get the implicit join path to the
	 * <code>public.code_historic_preservation</code> table.
	 */
	public CodeHistoricPreservationPath codeHistoricPreservation() {
		if (_codeHistoricPreservation == null)
			_codeHistoricPreservation = new CodeHistoricPreservationPath(this, Keys.OBJ_BUILDING__OBJ_BUILDING_HISTORIC_PRESERVATION_ID_FKEY, null);

		return _codeHistoricPreservation;
	}

	/**
	 * Get the implicit to-many join path to the
	 * <code>public.obj_building_part_element_rating</code> table
	 */
	public ObjBuildingPartElementRatingPath objBuildingPartElementRating() {
		if (_objBuildingPartElementRating == null)
			_objBuildingPartElementRating = new ObjBuildingPartElementRatingPath(this, null, Keys.OBJ_BUILDING_PART_ELEMENT_RATING__OBJ_BUILDING_PART_ELEMENT_RATING_OBJ_ID_FKEY.getInverseKey());

		return _objBuildingPartElementRating;
	}

	/**
	 * Get the implicit to-many join path to the
	 * <code>public.obj_building_part_rating</code> table
	 */
	public ObjBuildingPartRatingPath objBuildingPartRating() {
		if (_objBuildingPartRating == null)
			_objBuildingPartRating = new ObjBuildingPartRatingPath(this, null, Keys.OBJ_BUILDING_PART_RATING__OBJ_BUILDING_PART_RATING_OBJ_ID_FKEY.getInverseKey());

		return _objBuildingPartRating;
	}

	@Override
	public ObjBuilding as(String alias) {
		return new ObjBuilding(DSL.name(alias), this);
	}

	@Override
	public ObjBuilding as(Name alias) {
		return new ObjBuilding(alias, this);
	}

	@Override
	public ObjBuilding as(Table<?> alias) {
		return new ObjBuilding(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ObjBuilding rename(String name) {
		return new ObjBuilding(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ObjBuilding rename(Name name) {
		return new ObjBuilding(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ObjBuilding rename(Table<?> name) {
		return new ObjBuilding(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ObjBuilding where(Condition condition) {
		return new ObjBuilding(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ObjBuilding where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ObjBuilding where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ObjBuilding where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ObjBuilding where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ObjBuilding where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ObjBuilding where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ObjBuilding where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ObjBuilding whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ObjBuilding whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class ObjBuildingPath extends ObjBuilding implements Path<ObjBuildingRecord> {

		private static final long serialVersionUID = 1L;

		public <O extends Record> ObjBuildingPath(Table<O> path, ForeignKey<O, ObjBuildingRecord> childPath, InverseForeignKey<O, ObjBuildingRecord> parentPath) {
			super(path, childPath, parentPath);
		}

		private ObjBuildingPath(Name alias, Table<ObjBuildingRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public ObjBuildingPath as(String alias) {
			return new ObjBuildingPath(DSL.name(alias), this);
		}

		@Override
		public ObjBuildingPath as(Name alias) {
			return new ObjBuildingPath(alias, this);
		}

		@Override
		public ObjBuildingPath as(Table<?> alias) {
			return new ObjBuildingPath(alias.getQualifiedName(), this);
		}

	}

}
