/*
 * This file is generated by jOOQ.
 */
package fm.comunas.ddd.common.model.db;


import fm.comunas.ddd.common.model.db.tables.CodeCountry;
import fm.comunas.ddd.common.model.db.tables.CodeCurrency;
import fm.comunas.ddd.common.model.db.tables.CodeLocale;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.code_country</code>.
     */
    public static final CodeCountry CODE_COUNTRY = CodeCountry.CODE_COUNTRY;

    /**
     * The table <code>public.code_currency</code>.
     */
    public static final CodeCurrency CODE_CURRENCY = CodeCurrency.CODE_CURRENCY;

    /**
     * The table <code>public.code_locale</code>.
     */
    public static final CodeLocale CODE_LOCALE = CodeLocale.CODE_LOCALE;
}
