/*
 * This file is generated by jOOQ.
 */
package fm.comunas.fm.lead.model.db.tables;


import fm.comunas.fm.lead.model.db.Public;
import fm.comunas.fm.lead.model.db.tables.records.DocLeadSearchRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocLeadSearch extends TableImpl<DocLeadSearchRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.doc_lead_search</code>
     */
    public static final DocLeadSearch DOC_LEAD_SEARCH = new DocLeadSearch();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DocLeadSearchRecord> getRecordType() {
        return DocLeadSearchRecord.class;
    }

    /**
     * The column <code>public.doc_lead_search.doc_id</code>.
     */
    public final TableField<DocLeadSearchRecord, Integer> DOC_ID = createField(DSL.name("doc_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.doc_lead_search.tokens</code>.
     */
    public final TableField<DocLeadSearchRecord, String> TOKENS = createField(DSL.name("tokens"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.doc_lead_search.text</code>.
     */
    public final TableField<DocLeadSearchRecord, String> TEXT = createField(DSL.name("text"), SQLDataType.CLOB, this, "");

    private DocLeadSearch(Name alias, Table<DocLeadSearchRecord> aliased) {
        this(alias, aliased, null);
    }

    private DocLeadSearch(Name alias, Table<DocLeadSearchRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("create view \"doc_lead_search\" as  SELECT d.doc_id,\n    (((((((((((((('lead '::text || (COALESCE(d.intl_key, ' '::character varying))::text) || ' '::text) || (COALESCE(d.first_name, ' '::character varying))::text) || ' '::text) || (COALESCE(d.last_name, ' '::character varying))::text) || ' '::text) || (COALESCE(d.email, ' '::character varying))::text) || ' '::text) || (COALESCE(d.street, ' '::character varying))::text) || ' '::text) || (COALESCE(d.city, ' '::character varying))::text) || ' '::text) || (COALESCE(d.zip, ' '::character varying))::text) || ' '::text) AS tokens,\n    ((((((COALESCE(d.subject, ' '::character varying))::text || ' '::text) || COALESCE(d.description, ' '::text)) || ' '::text) || COALESCE(translate((d.email)::text, '@_-.'::text, '    '::text), ' '::text)) || ' '::text) AS text\n   FROM doc_lead_v d;"));
    }

    /**
     * Create an aliased <code>public.doc_lead_search</code> table reference
     */
    public DocLeadSearch(String alias) {
        this(DSL.name(alias), DOC_LEAD_SEARCH);
    }

    /**
     * Create an aliased <code>public.doc_lead_search</code> table reference
     */
    public DocLeadSearch(Name alias) {
        this(alias, DOC_LEAD_SEARCH);
    }

    /**
     * Create a <code>public.doc_lead_search</code> table reference
     */
    public DocLeadSearch() {
        this(DSL.name("doc_lead_search"), null);
    }

    public <O extends Record> DocLeadSearch(Table<O> child, ForeignKey<O, DocLeadSearchRecord> key) {
        super(child, key, DOC_LEAD_SEARCH);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public DocLeadSearch as(String alias) {
        return new DocLeadSearch(DSL.name(alias), this);
    }

    @Override
    public DocLeadSearch as(Name alias) {
        return new DocLeadSearch(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DocLeadSearch rename(String name) {
        return new DocLeadSearch(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DocLeadSearch rename(Name name) {
        return new DocLeadSearch(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
