/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.oe.model.db.tables;


import io.zeitwert.fm.oe.model.db.Keys;
import io.zeitwert.fm.oe.model.db.Public;
import io.zeitwert.fm.oe.model.db.tables.ObjTenant.ObjTenantPath;
import io.zeitwert.fm.oe.model.db.tables.records.CodeTenantTypeRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeTenantType extends TableImpl<CodeTenantTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.code_tenant_type</code>
     */
    public static final CodeTenantType CODE_TENANT_TYPE = new CodeTenantType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeTenantTypeRecord> getRecordType() {
        return CodeTenantTypeRecord.class;
    }

    /**
     * The column <code>public.code_tenant_type.id</code>.
     */
    public final TableField<CodeTenantTypeRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.code_tenant_type.name</code>.
     */
    public final TableField<CodeTenantTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private CodeTenantType(Name alias, Table<CodeTenantTypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CodeTenantType(Name alias, Table<CodeTenantTypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.code_tenant_type</code> table reference
     */
    public CodeTenantType(String alias) {
        this(DSL.name(alias), CODE_TENANT_TYPE);
    }

    /**
     * Create an aliased <code>public.code_tenant_type</code> table reference
     */
    public CodeTenantType(Name alias) {
        this(alias, CODE_TENANT_TYPE);
    }

    /**
     * Create a <code>public.code_tenant_type</code> table reference
     */
    public CodeTenantType() {
        this(DSL.name("code_tenant_type"), null);
    }

    public <O extends Record> CodeTenantType(Table<O> path, ForeignKey<O, CodeTenantTypeRecord> childPath, InverseForeignKey<O, CodeTenantTypeRecord> parentPath) {
        super(path, childPath, parentPath, CODE_TENANT_TYPE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CodeTenantTypePath extends CodeTenantType implements Path<CodeTenantTypeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CodeTenantTypePath(Table<O> path, ForeignKey<O, CodeTenantTypeRecord> childPath, InverseForeignKey<O, CodeTenantTypeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CodeTenantTypePath(Name alias, Table<CodeTenantTypeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CodeTenantTypePath as(String alias) {
            return new CodeTenantTypePath(DSL.name(alias), this);
        }

        @Override
        public CodeTenantTypePath as(Name alias) {
            return new CodeTenantTypePath(alias, this);
        }

        @Override
        public CodeTenantTypePath as(Table<?> alias) {
            return new CodeTenantTypePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CodeTenantTypeRecord> getPrimaryKey() {
        return Keys.CODE_TENANT_TYPE_PKEY;
    }

    private transient ObjTenantPath _objTenant;

    /**
     * Get the implicit to-many join path to the <code>public.obj_tenant</code>
     * table
     */
    public ObjTenantPath objTenant() {
        if (_objTenant == null)
            _objTenant = new ObjTenantPath(this, null, Keys.OBJ_TENANT__OBJ_TENANT_TENANT_TYPE_ID_FKEY.getInverseKey());

        return _objTenant;
    }

    @Override
    public CodeTenantType as(String alias) {
        return new CodeTenantType(DSL.name(alias), this);
    }

    @Override
    public CodeTenantType as(Name alias) {
        return new CodeTenantType(alias, this);
    }

    @Override
    public CodeTenantType as(Table<?> alias) {
        return new CodeTenantType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeTenantType rename(String name) {
        return new CodeTenantType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeTenantType rename(Name name) {
        return new CodeTenantType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeTenantType rename(Table<?> name) {
        return new CodeTenantType(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeTenantType where(Condition condition) {
        return new CodeTenantType(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeTenantType where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeTenantType where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeTenantType where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeTenantType where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeTenantType where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeTenantType where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeTenantType where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeTenantType whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeTenantType whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
