/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.collaboration.model.db.tables;


import io.zeitwert.fm.collaboration.model.db.Keys;
import io.zeitwert.fm.collaboration.model.db.Public;
import io.zeitwert.fm.collaboration.model.db.tables.CodeNoteType.CodeNoteTypePath;
import io.zeitwert.fm.collaboration.model.db.tables.records.ObjNoteRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ObjNote extends TableImpl<ObjNoteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.obj_note</code>
     */
    public static final ObjNote OBJ_NOTE = new ObjNote();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ObjNoteRecord> getRecordType() {
        return ObjNoteRecord.class;
    }

    /**
     * The column <code>public.obj_note.obj_id</code>.
     */
    public final TableField<ObjNoteRecord, Integer> OBJ_ID = createField(DSL.name("obj_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.obj_note.tenant_id</code>.
     */
    public final TableField<ObjNoteRecord, Integer> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.obj_note.note_type_id</code>.
     */
    public final TableField<ObjNoteRecord, String> NOTE_TYPE_ID = createField(DSL.name("note_type_id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.obj_note.subject</code>.
     */
    public final TableField<ObjNoteRecord, String> SUBJECT = createField(DSL.name("subject"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.obj_note.content</code>.
     */
    public final TableField<ObjNoteRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.obj_note.is_private</code>.
     */
    public final TableField<ObjNoteRecord, Boolean> IS_PRIVATE = createField(DSL.name("is_private"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.obj_note.related_to_id</code>.
     */
    public final TableField<ObjNoteRecord, Integer> RELATED_TO_ID = createField(DSL.name("related_to_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private ObjNote(Name alias, Table<ObjNoteRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ObjNote(Name alias, Table<ObjNoteRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.obj_note</code> table reference
     */
    public ObjNote(String alias) {
        this(DSL.name(alias), OBJ_NOTE);
    }

    /**
     * Create an aliased <code>public.obj_note</code> table reference
     */
    public ObjNote(Name alias) {
        this(alias, OBJ_NOTE);
    }

    /**
     * Create a <code>public.obj_note</code> table reference
     */
    public ObjNote() {
        this(DSL.name("obj_note"), null);
    }

    public <O extends Record> ObjNote(Table<O> path, ForeignKey<O, ObjNoteRecord> childPath, InverseForeignKey<O, ObjNoteRecord> parentPath) {
        super(path, childPath, parentPath, OBJ_NOTE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ObjNotePath extends ObjNote implements Path<ObjNoteRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ObjNotePath(Table<O> path, ForeignKey<O, ObjNoteRecord> childPath, InverseForeignKey<O, ObjNoteRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ObjNotePath(Name alias, Table<ObjNoteRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ObjNotePath as(String alias) {
            return new ObjNotePath(DSL.name(alias), this);
        }

        @Override
        public ObjNotePath as(Name alias) {
            return new ObjNotePath(alias, this);
        }

        @Override
        public ObjNotePath as(Table<?> alias) {
            return new ObjNotePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ObjNoteRecord> getPrimaryKey() {
        return Keys.OBJ_NOTE_PKEY;
    }

    @Override
    public List<ForeignKey<ObjNoteRecord, ?>> getReferences() {
        return Arrays.asList(Keys.OBJ_NOTE__OBJ_NOTE_NOTE_TYPE_ID_FKEY);
    }

    private transient CodeNoteTypePath _codeNoteType;

    /**
     * Get the implicit join path to the <code>public.code_note_type</code>
     * table.
     */
    public CodeNoteTypePath codeNoteType() {
        if (_codeNoteType == null)
            _codeNoteType = new CodeNoteTypePath(this, Keys.OBJ_NOTE__OBJ_NOTE_NOTE_TYPE_ID_FKEY, null);

        return _codeNoteType;
    }

    @Override
    public ObjNote as(String alias) {
        return new ObjNote(DSL.name(alias), this);
    }

    @Override
    public ObjNote as(Name alias) {
        return new ObjNote(alias, this);
    }

    @Override
    public ObjNote as(Table<?> alias) {
        return new ObjNote(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjNote rename(String name) {
        return new ObjNote(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjNote rename(Name name) {
        return new ObjNote(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjNote rename(Table<?> name) {
        return new ObjNote(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjNote where(Condition condition) {
        return new ObjNote(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjNote where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjNote where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjNote where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ObjNote where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ObjNote where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ObjNote where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ObjNote where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjNote whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjNote whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
