/*
 * This file is generated by jOOQ.
 */
package fm.comunas.fm.test.model.db.tables;


import fm.comunas.fm.test.model.db.Keys;
import fm.comunas.fm.test.model.db.Public;
import fm.comunas.fm.test.model.db.tables.records.ObjTestRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObjTest extends TableImpl<ObjTestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.obj_test</code>
     */
    public static final ObjTest OBJ_TEST = new ObjTest();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ObjTestRecord> getRecordType() {
        return ObjTestRecord.class;
    }

    /**
     * The column <code>public.obj_test.obj_id</code>.
     */
    public final TableField<ObjTestRecord, Integer> OBJ_ID = createField(DSL.name("obj_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.obj_test.short_text</code>.
     */
    public final TableField<ObjTestRecord, String> SHORT_TEXT = createField(DSL.name("short_text"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.obj_test.long_text</code>.
     */
    public final TableField<ObjTestRecord, String> LONG_TEXT = createField(DSL.name("long_text"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.obj_test.date</code>.
     */
    public final TableField<ObjTestRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.obj_test.int</code>.
     */
    public final TableField<ObjTestRecord, Integer> INT = createField(DSL.name("int"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_test.is_done</code>.
     */
    public final TableField<ObjTestRecord, Boolean> IS_DONE = createField(DSL.name("is_done"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.obj_test.json</code>.
     */
    public final TableField<ObjTestRecord, org.jooq.JSON> JSON = createField(DSL.name("json"), SQLDataType.JSON, this, "");

    /**
     * The column <code>public.obj_test.nr</code>.
     */
    public final TableField<ObjTestRecord, BigDecimal> NR = createField(DSL.name("nr"), SQLDataType.NUMERIC(18, 4), this, "");

    /**
     * The column <code>public.obj_test.country_id</code>.
     */
    public final TableField<ObjTestRecord, String> COUNTRY_ID = createField(DSL.name("country_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.obj_test.ref_test_id</code>.
     */
    public final TableField<ObjTestRecord, Integer> REF_TEST_ID = createField(DSL.name("ref_test_id"), SQLDataType.INTEGER, this, "");

    private ObjTest(Name alias, Table<ObjTestRecord> aliased) {
        this(alias, aliased, null);
    }

    private ObjTest(Name alias, Table<ObjTestRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.obj_test</code> table reference
     */
    public ObjTest(String alias) {
        this(DSL.name(alias), OBJ_TEST);
    }

    /**
     * Create an aliased <code>public.obj_test</code> table reference
     */
    public ObjTest(Name alias) {
        this(alias, OBJ_TEST);
    }

    /**
     * Create a <code>public.obj_test</code> table reference
     */
    public ObjTest() {
        this(DSL.name("obj_test"), null);
    }

    public <O extends Record> ObjTest(Table<O> child, ForeignKey<O, ObjTestRecord> key) {
        super(child, key, OBJ_TEST);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<ObjTestRecord> getPrimaryKey() {
        return Keys.OBJ_TEST_PKEY;
    }

    @Override
    public List<UniqueKey<ObjTestRecord>> getKeys() {
        return Arrays.<UniqueKey<ObjTestRecord>>asList(Keys.OBJ_TEST_PKEY);
    }

    @Override
    public List<ForeignKey<ObjTestRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ObjTestRecord, ?>>asList(Keys.OBJ_TEST__OBJ_TEST_REF_TEST_ID_FKEY);
    }

    private transient ObjTest _objTest;

    public ObjTest objTest() {
        if (_objTest == null)
            _objTest = new ObjTest(this, Keys.OBJ_TEST__OBJ_TEST_REF_TEST_ID_FKEY);

        return _objTest;
    }

    @Override
    public ObjTest as(String alias) {
        return new ObjTest(DSL.name(alias), this);
    }

    @Override
    public ObjTest as(Name alias) {
        return new ObjTest(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjTest rename(String name) {
        return new ObjTest(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjTest rename(Name name) {
        return new ObjTest(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, LocalDate, Integer, Boolean, org.jooq.JSON, BigDecimal, String, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
