
insert into migr_obj_account_v(tenant,owner,key,name,account_type_id,main_contact,client_segment,reference_currency,description) values
('demo', 'martin@zeitwert.io', '8355', 'Aadorf 8355', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8479', 'Altikon 8479', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '9220', 'Bischofszell 9220', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '9220', 'Blidegg 9220', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '5620', 'Bremgarten 5620', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '9470', 'Buchs SG 9470', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8253', 'Diessenhofen 8253', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '9651', 'Ennetbühl 9651', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '9225', 'Gotthaus 9225', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '9223', 'Halden 9223', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '9213', 'Hauptwil 9213', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8444', 'Henggart 8444', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '5626', 'Hermetschwil 5626', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '3032', 'Hinterkappelen 3032', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8335', 'Hittnau 8335', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '9216', 'Hohentannen 9216', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '4950', 'Huttwil 4950', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '4303', 'Kaiseraugst 4303', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '7304', 'Maienfeld 7304', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '5318', 'Mandach 5318', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '3034', 'Murzelen 3034', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '1111', 'Musterstadt 1111', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8477', 'Oberstammheim 8477', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8558', 'Raperswilen 8558', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '9471', 'Rheinau SG 9471', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8153', 'Rümlang 8153', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '3049', 'Säriswil 3049', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8255', 'Schlattingen 8255', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '5425', 'Schneisingen 5425', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '9223', 'Schweizersholz 9223', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8589', 'Sitterdorf 8589', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8564', 'Sonterswil 8564', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8266', 'Steckborn 8266', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '3043', 'Uettligen 3043', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8476', 'Unterstammheim 8476', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8468', 'Waltalingen 8468', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8104', 'Weiningen 8104', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8620', 'Wetzikon 8620', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8556', 'Wigoltingen 8556', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8556', 'Wigoltingen 8556', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '3033', 'Wohlen 3033', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8588', 'Zihlschlacht 8588', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8006', 'Zürich 8006', 'client',null,null,'chf',null),
('demo', 'martin@zeitwert.io', '8022', 'Zürich 8022', 'client',null,null,'chf',null);
