package io.zeitwert.fm.building.adapter.api.rest.dto

import java.math.BigDecimal
import java.time.LocalDate

data class BuildingTransferDto(
	val meta: TransferMetaDto? = null,
	val id: Int? = null,
	val name: String? = null,
	val description: String? = null,
	val buildingNr: String? = null,
	val buildingInsuranceNr: String? = null,
	val plotNr: String? = null,
	val nationalBuildingId: String? = null,
	val historicPreservation: String? = null,
	val street: String? = null,
	val zip: String? = null,
	val city: String? = null,
	val country: String? = null,
	val geoAddress: String? = null,
	val geoCoordinates: String? = null,
	val geoZoom: Int? = null,
	val currency: String? = null,
	val volume: BigDecimal? = null,
	val areaGross: BigDecimal? = null,
	val areaNet: BigDecimal? = null,
	val nrOfFloorsAboveGround: Int? = null,
	val nrOfFloorsBelowGround: Int? = null,
	val buildingType: String? = null,
	val buildingSubType: String? = null,
	val buildingYear: Int? = null,
	val insuredValue: BigDecimal? = null,
	val insuredValueYear: Int? = null,
	val notInsuredValue: BigDecimal? = null,
	val notInsuredValueYear: Int? = null,
	val thirdPartyValue: BigDecimal? = null,
	val thirdPartyValueYear: Int? = null,
	val buildingPartCatalog: String? = null,
	val buildingMaintenanceStrategy: String? = null,
	val ratingStatus: String? = null,
	val ratingDate: LocalDate? = null,
	val ratingUser: String? = null,
	val elements: List<BuildingTransferElementRatingDto>? = null,
	val notes: List<NoteTransferDto>? = null,
)

