/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.test.model.db.tables;


import io.zeitwert.fm.test.model.db.Keys;
import io.zeitwert.fm.test.model.db.Public;
import io.zeitwert.fm.test.model.db.tables.CodeTestType.CodeTestTypePath;
import io.zeitwert.fm.test.model.db.tables.ObjTest.ObjTestPath;
import io.zeitwert.fm.test.model.db.tables.records.ObjTestPartNodeRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ObjTestPartNode extends TableImpl<ObjTestPartNodeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.obj_test_part_node</code>
     */
    public static final ObjTestPartNode OBJ_TEST_PART_NODE = new ObjTestPartNode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ObjTestPartNodeRecord> getRecordType() {
        return ObjTestPartNodeRecord.class;
    }

    /**
     * The column <code>public.obj_test_part_node.id</code>.
     */
    public final TableField<ObjTestPartNodeRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.obj_test_part_node.obj_id</code>.
     */
    public final TableField<ObjTestPartNodeRecord, Integer> OBJ_ID = createField(DSL.name("obj_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.obj_test_part_node.parent_part_id</code>.
     */
    public final TableField<ObjTestPartNodeRecord, Integer> PARENT_PART_ID = createField(DSL.name("parent_part_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_test_part_node.part_list_type_id</code>.
     */
    public final TableField<ObjTestPartNodeRecord, String> PART_LIST_TYPE_ID = createField(DSL.name("part_list_type_id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.obj_test_part_node.seq_nr</code>.
     */
    public final TableField<ObjTestPartNodeRecord, Integer> SEQ_NR = createField(DSL.name("seq_nr"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_test_part_node.short_text</code>.
     */
    public final TableField<ObjTestPartNodeRecord, String> SHORT_TEXT = createField(DSL.name("short_text"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.obj_test_part_node.long_text</code>.
     */
    public final TableField<ObjTestPartNodeRecord, String> LONG_TEXT = createField(DSL.name("long_text"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.obj_test_part_node.date</code>.
     */
    public final TableField<ObjTestPartNodeRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.obj_test_part_node.int</code>.
     */
    public final TableField<ObjTestPartNodeRecord, Integer> INT = createField(DSL.name("int"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_test_part_node.is_done</code>.
     */
    public final TableField<ObjTestPartNodeRecord, Boolean> IS_DONE = createField(DSL.name("is_done"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.obj_test_part_node.json</code>.
     */
    public final TableField<ObjTestPartNodeRecord, org.jooq.JSON> JSON = createField(DSL.name("json"), SQLDataType.JSON, this, "");

    /**
     * The column <code>public.obj_test_part_node.nr</code>.
     */
    public final TableField<ObjTestPartNodeRecord, BigDecimal> NR = createField(DSL.name("nr"), SQLDataType.NUMERIC(18, 4), this, "");

    /**
     * The column <code>public.obj_test_part_node.test_type_id</code>.
     */
    public final TableField<ObjTestPartNodeRecord, String> TEST_TYPE_ID = createField(DSL.name("test_type_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.obj_test_part_node.ref_obj_id</code>.
     */
    public final TableField<ObjTestPartNodeRecord, Integer> REF_OBJ_ID = createField(DSL.name("ref_obj_id"), SQLDataType.INTEGER, this, "");

    private ObjTestPartNode(Name alias, Table<ObjTestPartNodeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ObjTestPartNode(Name alias, Table<ObjTestPartNodeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.obj_test_part_node</code> table reference
     */
    public ObjTestPartNode(String alias) {
        this(DSL.name(alias), OBJ_TEST_PART_NODE);
    }

    /**
     * Create an aliased <code>public.obj_test_part_node</code> table reference
     */
    public ObjTestPartNode(Name alias) {
        this(alias, OBJ_TEST_PART_NODE);
    }

    /**
     * Create a <code>public.obj_test_part_node</code> table reference
     */
    public ObjTestPartNode() {
        this(DSL.name("obj_test_part_node"), null);
    }

    public <O extends Record> ObjTestPartNode(Table<O> path, ForeignKey<O, ObjTestPartNodeRecord> childPath, InverseForeignKey<O, ObjTestPartNodeRecord> parentPath) {
        super(path, childPath, parentPath, OBJ_TEST_PART_NODE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ObjTestPartNodePath extends ObjTestPartNode implements Path<ObjTestPartNodeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ObjTestPartNodePath(Table<O> path, ForeignKey<O, ObjTestPartNodeRecord> childPath, InverseForeignKey<O, ObjTestPartNodeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ObjTestPartNodePath(Name alias, Table<ObjTestPartNodeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ObjTestPartNodePath as(String alias) {
            return new ObjTestPartNodePath(DSL.name(alias), this);
        }

        @Override
        public ObjTestPartNodePath as(Name alias) {
            return new ObjTestPartNodePath(alias, this);
        }

        @Override
        public ObjTestPartNodePath as(Table<?> alias) {
            return new ObjTestPartNodePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ObjTestPartNodeRecord> getPrimaryKey() {
        return Keys.OBJ_TEST_PART_NODE_PKEY;
    }

    @Override
    public List<ForeignKey<ObjTestPartNodeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.OBJ_TEST_PART_NODE__OBJ_TEST_PART_NODE_REF_OBJ_ID_FKEY, Keys.OBJ_TEST_PART_NODE__OBJ_TEST_PART_NODE_TEST_TYPE_ID_FKEY);
    }

    private transient ObjTestPath _objTest;

    /**
     * Get the implicit join path to the <code>public.obj_test</code> table.
     */
    public ObjTestPath objTest() {
        if (_objTest == null)
            _objTest = new ObjTestPath(this, Keys.OBJ_TEST_PART_NODE__OBJ_TEST_PART_NODE_REF_OBJ_ID_FKEY, null);

        return _objTest;
    }

    private transient CodeTestTypePath _codeTestType;

    /**
     * Get the implicit join path to the <code>public.code_test_type</code>
     * table.
     */
    public CodeTestTypePath codeTestType() {
        if (_codeTestType == null)
            _codeTestType = new CodeTestTypePath(this, Keys.OBJ_TEST_PART_NODE__OBJ_TEST_PART_NODE_TEST_TYPE_ID_FKEY, null);

        return _codeTestType;
    }

    @Override
    public ObjTestPartNode as(String alias) {
        return new ObjTestPartNode(DSL.name(alias), this);
    }

    @Override
    public ObjTestPartNode as(Name alias) {
        return new ObjTestPartNode(alias, this);
    }

    @Override
    public ObjTestPartNode as(Table<?> alias) {
        return new ObjTestPartNode(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjTestPartNode rename(String name) {
        return new ObjTestPartNode(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjTestPartNode rename(Name name) {
        return new ObjTestPartNode(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjTestPartNode rename(Table<?> name) {
        return new ObjTestPartNode(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjTestPartNode where(Condition condition) {
        return new ObjTestPartNode(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjTestPartNode where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjTestPartNode where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjTestPartNode where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ObjTestPartNode where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ObjTestPartNode where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ObjTestPartNode where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ObjTestPartNode where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjTestPartNode whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjTestPartNode whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
