/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.contact.model.db.tables;


import io.zeitwert.fm.contact.model.db.Keys;
import io.zeitwert.fm.contact.model.db.Public;
import io.zeitwert.fm.contact.model.db.tables.CodeAddressChannel.CodeAddressChannelPath;
import io.zeitwert.fm.contact.model.db.tables.records.CodeAddressTypeRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeAddressType extends TableImpl<CodeAddressTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.code_address_type</code>
     */
    public static final CodeAddressType CODE_ADDRESS_TYPE = new CodeAddressType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeAddressTypeRecord> getRecordType() {
        return CodeAddressTypeRecord.class;
    }

    /**
     * The column <code>public.code_address_type.id</code>.
     */
    public final TableField<CodeAddressTypeRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.code_address_type.name</code>.
     */
    public final TableField<CodeAddressTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private CodeAddressType(Name alias, Table<CodeAddressTypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CodeAddressType(Name alias, Table<CodeAddressTypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.code_address_type</code> table reference
     */
    public CodeAddressType(String alias) {
        this(DSL.name(alias), CODE_ADDRESS_TYPE);
    }

    /**
     * Create an aliased <code>public.code_address_type</code> table reference
     */
    public CodeAddressType(Name alias) {
        this(alias, CODE_ADDRESS_TYPE);
    }

    /**
     * Create a <code>public.code_address_type</code> table reference
     */
    public CodeAddressType() {
        this(DSL.name("code_address_type"), null);
    }

    public <O extends Record> CodeAddressType(Table<O> path, ForeignKey<O, CodeAddressTypeRecord> childPath, InverseForeignKey<O, CodeAddressTypeRecord> parentPath) {
        super(path, childPath, parentPath, CODE_ADDRESS_TYPE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CodeAddressTypePath extends CodeAddressType implements Path<CodeAddressTypeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CodeAddressTypePath(Table<O> path, ForeignKey<O, CodeAddressTypeRecord> childPath, InverseForeignKey<O, CodeAddressTypeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CodeAddressTypePath(Name alias, Table<CodeAddressTypeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CodeAddressTypePath as(String alias) {
            return new CodeAddressTypePath(DSL.name(alias), this);
        }

        @Override
        public CodeAddressTypePath as(Name alias) {
            return new CodeAddressTypePath(alias, this);
        }

        @Override
        public CodeAddressTypePath as(Table<?> alias) {
            return new CodeAddressTypePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CodeAddressTypeRecord> getPrimaryKey() {
        return Keys.CODE_ADDRESS_TYPE_PKEY;
    }

    private transient CodeAddressChannelPath _codeAddressChannel;

    /**
     * Get the implicit to-many join path to the
     * <code>public.code_address_channel</code> table
     */
    public CodeAddressChannelPath codeAddressChannel() {
        if (_codeAddressChannel == null)
            _codeAddressChannel = new CodeAddressChannelPath(this, null, Keys.CODE_ADDRESS_CHANNEL__CODE_ADDRESS_CHANNEL_ADDRESS_TYPE_ID_FKEY.getInverseKey());

        return _codeAddressChannel;
    }

    @Override
    public CodeAddressType as(String alias) {
        return new CodeAddressType(DSL.name(alias), this);
    }

    @Override
    public CodeAddressType as(Name alias) {
        return new CodeAddressType(alias, this);
    }

    @Override
    public CodeAddressType as(Table<?> alias) {
        return new CodeAddressType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeAddressType rename(String name) {
        return new CodeAddressType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeAddressType rename(Name name) {
        return new CodeAddressType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeAddressType rename(Table<?> name) {
        return new CodeAddressType(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeAddressType where(Condition condition) {
        return new CodeAddressType(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeAddressType where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeAddressType where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeAddressType where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeAddressType where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeAddressType where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeAddressType where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeAddressType where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeAddressType whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeAddressType whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
