/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.building.model.db.tables.records;


import io.zeitwert.fm.building.model.db.tables.ObjBuildingSearch;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObjBuildingSearchRecord extends TableRecordImpl<ObjBuildingSearchRecord> implements Record4<Integer, Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.obj_building_search.obj_id</code>.
     */
    public void setObjId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.obj_building_search.obj_id</code>.
     */
    public Integer getObjId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.obj_building_search.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.obj_building_search.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.obj_building_search.tokens</code>.
     */
    public void setTokens(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.obj_building_search.tokens</code>.
     */
    public String getTokens() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.obj_building_search.text</code>.
     */
    public void setText(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.obj_building_search.text</code>.
     */
    public String getText() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ObjBuildingSearch.OBJ_BUILDING_SEARCH.OBJ_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ObjBuildingSearch.OBJ_BUILDING_SEARCH.ACCOUNT_ID;
    }

    @Override
    public Field<String> field3() {
        return ObjBuildingSearch.OBJ_BUILDING_SEARCH.TOKENS;
    }

    @Override
    public Field<String> field4() {
        return ObjBuildingSearch.OBJ_BUILDING_SEARCH.TEXT;
    }

    @Override
    public Integer component1() {
        return getObjId();
    }

    @Override
    public Integer component2() {
        return getAccountId();
    }

    @Override
    public String component3() {
        return getTokens();
    }

    @Override
    public String component4() {
        return getText();
    }

    @Override
    public Integer value1() {
        return getObjId();
    }

    @Override
    public Integer value2() {
        return getAccountId();
    }

    @Override
    public String value3() {
        return getTokens();
    }

    @Override
    public String value4() {
        return getText();
    }

    @Override
    public ObjBuildingSearchRecord value1(Integer value) {
        setObjId(value);
        return this;
    }

    @Override
    public ObjBuildingSearchRecord value2(Integer value) {
        setAccountId(value);
        return this;
    }

    @Override
    public ObjBuildingSearchRecord value3(String value) {
        setTokens(value);
        return this;
    }

    @Override
    public ObjBuildingSearchRecord value4(String value) {
        setText(value);
        return this;
    }

    @Override
    public ObjBuildingSearchRecord values(Integer value1, Integer value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ObjBuildingSearchRecord
     */
    public ObjBuildingSearchRecord() {
        super(ObjBuildingSearch.OBJ_BUILDING_SEARCH);
    }

    /**
     * Create a detached, initialised ObjBuildingSearchRecord
     */
    public ObjBuildingSearchRecord(Integer objId, Integer accountId, String tokens, String text) {
        super(ObjBuildingSearch.OBJ_BUILDING_SEARCH);

        setObjId(objId);
        setAccountId(accountId);
        setTokens(tokens);
        setText(text);
    }
}
