/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.building.model.db.tables.records;


import io.zeitwert.fm.building.model.db.tables.ObjBuilding;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObjBuildingRecord extends UpdatableRecordImpl<ObjBuildingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.obj_building.obj_id</code>.
     */
    public void setObjId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.obj_building.obj_id</code>.
     */
    public Integer getObjId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.obj_building.intl_key</code>.
     */
    public void setIntlKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.obj_building.intl_key</code>.
     */
    public String getIntlKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.obj_building.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.obj_building.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.obj_building.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.obj_building.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.obj_building.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.obj_building.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.obj_building.building_nr</code>.
     */
    public void setBuildingNr(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.obj_building.building_nr</code>.
     */
    public String getBuildingNr() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.obj_building.building_insurance_nr</code>.
     */
    public void setBuildingInsuranceNr(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.obj_building.building_insurance_nr</code>.
     */
    public String getBuildingInsuranceNr() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.obj_building.plot_nr</code>.
     */
    public void setPlotNr(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.obj_building.plot_nr</code>.
     */
    public String getPlotNr() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.obj_building.national_building_id</code>.
     */
    public void setNationalBuildingId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.obj_building.national_building_id</code>.
     */
    public String getNationalBuildingId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.obj_building.historic_preservation_id</code>.
     */
    public void setHistoricPreservationId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.obj_building.historic_preservation_id</code>.
     */
    public String getHistoricPreservationId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.obj_building.street</code>.
     */
    public void setStreet(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.obj_building.street</code>.
     */
    public String getStreet() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.obj_building.zip</code>.
     */
    public void setZip(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.obj_building.zip</code>.
     */
    public String getZip() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.obj_building.city</code>.
     */
    public void setCity(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.obj_building.city</code>.
     */
    public String getCity() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.obj_building.country_id</code>.
     */
    public void setCountryId(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.obj_building.country_id</code>.
     */
    public String getCountryId() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.obj_building.geo_address</code>.
     */
    public void setGeoAddress(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.obj_building.geo_address</code>.
     */
    public String getGeoAddress() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.obj_building.geo_coordinates</code>.
     */
    public void setGeoCoordinates(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.obj_building.geo_coordinates</code>.
     */
    public String getGeoCoordinates() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.obj_building.geo_zoom</code>.
     */
    public void setGeoZoom(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.obj_building.geo_zoom</code>.
     */
    public Integer getGeoZoom() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>public.obj_building.cover_foto_id</code>.
     */
    public void setCoverFotoId(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.obj_building.cover_foto_id</code>.
     */
    public Integer getCoverFotoId() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>public.obj_building.currency_id</code>.
     */
    public void setCurrencyId(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.obj_building.currency_id</code>.
     */
    public String getCurrencyId() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.obj_building.volume</code>.
     */
    public void setVolume(BigDecimal value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.obj_building.volume</code>.
     */
    public BigDecimal getVolume() {
        return (BigDecimal) get(19);
    }

    /**
     * Setter for <code>public.obj_building.area_gross</code>.
     */
    public void setAreaGross(BigDecimal value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.obj_building.area_gross</code>.
     */
    public BigDecimal getAreaGross() {
        return (BigDecimal) get(20);
    }

    /**
     * Setter for <code>public.obj_building.area_net</code>.
     */
    public void setAreaNet(BigDecimal value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.obj_building.area_net</code>.
     */
    public BigDecimal getAreaNet() {
        return (BigDecimal) get(21);
    }

    /**
     * Setter for <code>public.obj_building.nr_of_floors_above_ground</code>.
     */
    public void setNrOfFloorsAboveGround(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.obj_building.nr_of_floors_above_ground</code>.
     */
    public Integer getNrOfFloorsAboveGround() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>public.obj_building.nr_of_floors_below_ground</code>.
     */
    public void setNrOfFloorsBelowGround(Integer value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.obj_building.nr_of_floors_below_ground</code>.
     */
    public Integer getNrOfFloorsBelowGround() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>public.obj_building.building_type_id</code>.
     */
    public void setBuildingTypeId(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.obj_building.building_type_id</code>.
     */
    public String getBuildingTypeId() {
        return (String) get(24);
    }

    /**
     * Setter for <code>public.obj_building.building_sub_type_id</code>.
     */
    public void setBuildingSubTypeId(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.obj_building.building_sub_type_id</code>.
     */
    public String getBuildingSubTypeId() {
        return (String) get(25);
    }

    /**
     * Setter for <code>public.obj_building.building_year</code>.
     */
    public void setBuildingYear(Integer value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.obj_building.building_year</code>.
     */
    public Integer getBuildingYear() {
        return (Integer) get(26);
    }

    /**
     * Setter for <code>public.obj_building.insured_value</code>.
     */
    public void setInsuredValue(BigDecimal value) {
        set(27, value);
    }

    /**
     * Getter for <code>public.obj_building.insured_value</code>.
     */
    public BigDecimal getInsuredValue() {
        return (BigDecimal) get(27);
    }

    /**
     * Setter for <code>public.obj_building.insured_value_year</code>.
     */
    public void setInsuredValueYear(Integer value) {
        set(28, value);
    }

    /**
     * Getter for <code>public.obj_building.insured_value_year</code>.
     */
    public Integer getInsuredValueYear() {
        return (Integer) get(28);
    }

    /**
     * Setter for <code>public.obj_building.not_insured_value</code>.
     */
    public void setNotInsuredValue(BigDecimal value) {
        set(29, value);
    }

    /**
     * Getter for <code>public.obj_building.not_insured_value</code>.
     */
    public BigDecimal getNotInsuredValue() {
        return (BigDecimal) get(29);
    }

    /**
     * Setter for <code>public.obj_building.not_insured_value_year</code>.
     */
    public void setNotInsuredValueYear(Integer value) {
        set(30, value);
    }

    /**
     * Getter for <code>public.obj_building.not_insured_value_year</code>.
     */
    public Integer getNotInsuredValueYear() {
        return (Integer) get(30);
    }

    /**
     * Setter for <code>public.obj_building.third_party_value</code>.
     */
    public void setThirdPartyValue(BigDecimal value) {
        set(31, value);
    }

    /**
     * Getter for <code>public.obj_building.third_party_value</code>.
     */
    public BigDecimal getThirdPartyValue() {
        return (BigDecimal) get(31);
    }

    /**
     * Setter for <code>public.obj_building.third_party_value_year</code>.
     */
    public void setThirdPartyValueYear(Integer value) {
        set(32, value);
    }

    /**
     * Getter for <code>public.obj_building.third_party_value_year</code>.
     */
    public Integer getThirdPartyValueYear() {
        return (Integer) get(32);
    }

    /**
     * Setter for <code>public.obj_building.building_part_catalog_id</code>.
     */
    public void setBuildingPartCatalogId(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>public.obj_building.building_part_catalog_id</code>.
     */
    public String getBuildingPartCatalogId() {
        return (String) get(33);
    }

    /**
     * Setter for <code>public.obj_building.building_maintenance_strategy_id</code>.
     */
    public void setBuildingMaintenanceStrategyId(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>public.obj_building.building_maintenance_strategy_id</code>.
     */
    public String getBuildingMaintenanceStrategyId() {
        return (String) get(34);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ObjBuildingRecord
     */
    public ObjBuildingRecord() {
        super(ObjBuilding.OBJ_BUILDING);
    }

    /**
     * Create a detached, initialised ObjBuildingRecord
     */
    public ObjBuildingRecord(Integer objId, String intlKey, String name, String description, Integer accountId, String buildingNr, String buildingInsuranceNr, String plotNr, String nationalBuildingId, String historicPreservationId, String street, String zip, String city, String countryId, String geoAddress, String geoCoordinates, Integer geoZoom, Integer coverFotoId, String currencyId, BigDecimal volume, BigDecimal areaGross, BigDecimal areaNet, Integer nrOfFloorsAboveGround, Integer nrOfFloorsBelowGround, String buildingTypeId, String buildingSubTypeId, Integer buildingYear, BigDecimal insuredValue, Integer insuredValueYear, BigDecimal notInsuredValue, Integer notInsuredValueYear, BigDecimal thirdPartyValue, Integer thirdPartyValueYear, String buildingPartCatalogId, String buildingMaintenanceStrategyId) {
        super(ObjBuilding.OBJ_BUILDING);

        setObjId(objId);
        setIntlKey(intlKey);
        setName(name);
        setDescription(description);
        setAccountId(accountId);
        setBuildingNr(buildingNr);
        setBuildingInsuranceNr(buildingInsuranceNr);
        setPlotNr(plotNr);
        setNationalBuildingId(nationalBuildingId);
        setHistoricPreservationId(historicPreservationId);
        setStreet(street);
        setZip(zip);
        setCity(city);
        setCountryId(countryId);
        setGeoAddress(geoAddress);
        setGeoCoordinates(geoCoordinates);
        setGeoZoom(geoZoom);
        setCoverFotoId(coverFotoId);
        setCurrencyId(currencyId);
        setVolume(volume);
        setAreaGross(areaGross);
        setAreaNet(areaNet);
        setNrOfFloorsAboveGround(nrOfFloorsAboveGround);
        setNrOfFloorsBelowGround(nrOfFloorsBelowGround);
        setBuildingTypeId(buildingTypeId);
        setBuildingSubTypeId(buildingSubTypeId);
        setBuildingYear(buildingYear);
        setInsuredValue(insuredValue);
        setInsuredValueYear(insuredValueYear);
        setNotInsuredValue(notInsuredValue);
        setNotInsuredValueYear(notInsuredValueYear);
        setThirdPartyValue(thirdPartyValue);
        setThirdPartyValueYear(thirdPartyValueYear);
        setBuildingPartCatalogId(buildingPartCatalogId);
        setBuildingMaintenanceStrategyId(buildingMaintenanceStrategyId);
    }
}
