/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.building.model.db.tables.records;


import io.zeitwert.fm.building.model.db.tables.ObjBuildingPartRating;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObjBuildingPartRatingRecord extends UpdatableRecordImpl<ObjBuildingPartRatingRecord> implements Record10<Integer, Integer, Integer, String, Integer, String, String, String, LocalDate, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.obj_building_part_rating.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.obj_building_part_rating.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.obj_building_part_rating.obj_id</code>.
     */
    public void setObjId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.obj_building_part_rating.obj_id</code>.
     */
    public Integer getObjId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.obj_building_part_rating.parent_part_id</code>.
     */
    public void setParentPartId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.obj_building_part_rating.parent_part_id</code>.
     */
    public Integer getParentPartId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.obj_building_part_rating.part_list_type_id</code>.
     */
    public void setPartListTypeId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.obj_building_part_rating.part_list_type_id</code>.
     */
    public String getPartListTypeId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.obj_building_part_rating.seq_nr</code>.
     */
    public void setSeqNr(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.obj_building_part_rating.seq_nr</code>.
     */
    public Integer getSeqNr() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.obj_building_part_rating.part_catalog_id</code>.
     */
    public void setPartCatalogId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.obj_building_part_rating.part_catalog_id</code>.
     */
    public String getPartCatalogId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.obj_building_part_rating.maintenance_strategy_id</code>.
     */
    public void setMaintenanceStrategyId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.obj_building_part_rating.maintenance_strategy_id</code>.
     */
    public String getMaintenanceStrategyId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.obj_building_part_rating.rating_status_id</code>.
     */
    public void setRatingStatusId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.obj_building_part_rating.rating_status_id</code>.
     */
    public String getRatingStatusId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.obj_building_part_rating.rating_date</code>.
     */
    public void setRatingDate(LocalDate value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.obj_building_part_rating.rating_date</code>.
     */
    public LocalDate getRatingDate() {
        return (LocalDate) get(8);
    }

    /**
     * Setter for <code>public.obj_building_part_rating.rating_user_id</code>.
     */
    public void setRatingUserId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.obj_building_part_rating.rating_user_id</code>.
     */
    public Integer getRatingUserId() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, Integer, Integer, String, Integer, String, String, String, LocalDate, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, Integer, Integer, String, Integer, String, String, String, LocalDate, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ObjBuildingPartRating.OBJ_BUILDING_PART_RATING.ID;
    }

    @Override
    public Field<Integer> field2() {
        return ObjBuildingPartRating.OBJ_BUILDING_PART_RATING.OBJ_ID;
    }

    @Override
    public Field<Integer> field3() {
        return ObjBuildingPartRating.OBJ_BUILDING_PART_RATING.PARENT_PART_ID;
    }

    @Override
    public Field<String> field4() {
        return ObjBuildingPartRating.OBJ_BUILDING_PART_RATING.PART_LIST_TYPE_ID;
    }

    @Override
    public Field<Integer> field5() {
        return ObjBuildingPartRating.OBJ_BUILDING_PART_RATING.SEQ_NR;
    }

    @Override
    public Field<String> field6() {
        return ObjBuildingPartRating.OBJ_BUILDING_PART_RATING.PART_CATALOG_ID;
    }

    @Override
    public Field<String> field7() {
        return ObjBuildingPartRating.OBJ_BUILDING_PART_RATING.MAINTENANCE_STRATEGY_ID;
    }

    @Override
    public Field<String> field8() {
        return ObjBuildingPartRating.OBJ_BUILDING_PART_RATING.RATING_STATUS_ID;
    }

    @Override
    public Field<LocalDate> field9() {
        return ObjBuildingPartRating.OBJ_BUILDING_PART_RATING.RATING_DATE;
    }

    @Override
    public Field<Integer> field10() {
        return ObjBuildingPartRating.OBJ_BUILDING_PART_RATING.RATING_USER_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getObjId();
    }

    @Override
    public Integer component3() {
        return getParentPartId();
    }

    @Override
    public String component4() {
        return getPartListTypeId();
    }

    @Override
    public Integer component5() {
        return getSeqNr();
    }

    @Override
    public String component6() {
        return getPartCatalogId();
    }

    @Override
    public String component7() {
        return getMaintenanceStrategyId();
    }

    @Override
    public String component8() {
        return getRatingStatusId();
    }

    @Override
    public LocalDate component9() {
        return getRatingDate();
    }

    @Override
    public Integer component10() {
        return getRatingUserId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getObjId();
    }

    @Override
    public Integer value3() {
        return getParentPartId();
    }

    @Override
    public String value4() {
        return getPartListTypeId();
    }

    @Override
    public Integer value5() {
        return getSeqNr();
    }

    @Override
    public String value6() {
        return getPartCatalogId();
    }

    @Override
    public String value7() {
        return getMaintenanceStrategyId();
    }

    @Override
    public String value8() {
        return getRatingStatusId();
    }

    @Override
    public LocalDate value9() {
        return getRatingDate();
    }

    @Override
    public Integer value10() {
        return getRatingUserId();
    }

    @Override
    public ObjBuildingPartRatingRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ObjBuildingPartRatingRecord value2(Integer value) {
        setObjId(value);
        return this;
    }

    @Override
    public ObjBuildingPartRatingRecord value3(Integer value) {
        setParentPartId(value);
        return this;
    }

    @Override
    public ObjBuildingPartRatingRecord value4(String value) {
        setPartListTypeId(value);
        return this;
    }

    @Override
    public ObjBuildingPartRatingRecord value5(Integer value) {
        setSeqNr(value);
        return this;
    }

    @Override
    public ObjBuildingPartRatingRecord value6(String value) {
        setPartCatalogId(value);
        return this;
    }

    @Override
    public ObjBuildingPartRatingRecord value7(String value) {
        setMaintenanceStrategyId(value);
        return this;
    }

    @Override
    public ObjBuildingPartRatingRecord value8(String value) {
        setRatingStatusId(value);
        return this;
    }

    @Override
    public ObjBuildingPartRatingRecord value9(LocalDate value) {
        setRatingDate(value);
        return this;
    }

    @Override
    public ObjBuildingPartRatingRecord value10(Integer value) {
        setRatingUserId(value);
        return this;
    }

    @Override
    public ObjBuildingPartRatingRecord values(Integer value1, Integer value2, Integer value3, String value4, Integer value5, String value6, String value7, String value8, LocalDate value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ObjBuildingPartRatingRecord
     */
    public ObjBuildingPartRatingRecord() {
        super(ObjBuildingPartRating.OBJ_BUILDING_PART_RATING);
    }

    /**
     * Create a detached, initialised ObjBuildingPartRatingRecord
     */
    public ObjBuildingPartRatingRecord(Integer id, Integer objId, Integer parentPartId, String partListTypeId, Integer seqNr, String partCatalogId, String maintenanceStrategyId, String ratingStatusId, LocalDate ratingDate, Integer ratingUserId) {
        super(ObjBuildingPartRating.OBJ_BUILDING_PART_RATING);

        setId(id);
        setObjId(objId);
        setParentPartId(parentPartId);
        setPartListTypeId(partListTypeId);
        setSeqNr(seqNr);
        setPartCatalogId(partCatalogId);
        setMaintenanceStrategyId(maintenanceStrategyId);
        setRatingStatusId(ratingStatusId);
        setRatingDate(ratingDate);
        setRatingUserId(ratingUserId);
    }
}
