/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.test.model.db.tables.records;


import io.zeitwert.fm.test.model.db.tables.DocTest;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocTestRecord extends UpdatableRecordImpl<DocTestRecord> implements Record9<Integer, String, String, LocalDate, Integer, Boolean, JSON, BigDecimal, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.doc_test.doc_id</code>.
     */
    public void setDocId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.doc_test.doc_id</code>.
     */
    public Integer getDocId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.doc_test.short_text</code>.
     */
    public void setShortText(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.doc_test.short_text</code>.
     */
    public String getShortText() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.doc_test.long_text</code>.
     */
    public void setLongText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.doc_test.long_text</code>.
     */
    public String getLongText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.doc_test.date</code>.
     */
    public void setDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.doc_test.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>public.doc_test.int</code>.
     */
    public void setInt(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.doc_test.int</code>.
     */
    public Integer getInt() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.doc_test.is_done</code>.
     */
    public void setIsDone(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.doc_test.is_done</code>.
     */
    public Boolean getIsDone() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.doc_test.json</code>.
     */
    public void setJson(JSON value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.doc_test.json</code>.
     */
    public JSON getJson() {
        return (JSON) get(6);
    }

    /**
     * Setter for <code>public.doc_test.nr</code>.
     */
    public void setNr(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.doc_test.nr</code>.
     */
    public BigDecimal getNr() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>public.doc_test.country_id</code>.
     */
    public void setCountryId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.doc_test.country_id</code>.
     */
    public String getCountryId() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, String, LocalDate, Integer, Boolean, JSON, BigDecimal, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, String, LocalDate, Integer, Boolean, JSON, BigDecimal, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DocTest.DOC_TEST.DOC_ID;
    }

    @Override
    public Field<String> field2() {
        return DocTest.DOC_TEST.SHORT_TEXT;
    }

    @Override
    public Field<String> field3() {
        return DocTest.DOC_TEST.LONG_TEXT;
    }

    @Override
    public Field<LocalDate> field4() {
        return DocTest.DOC_TEST.DATE;
    }

    @Override
    public Field<Integer> field5() {
        return DocTest.DOC_TEST.INT;
    }

    @Override
    public Field<Boolean> field6() {
        return DocTest.DOC_TEST.IS_DONE;
    }

    @Override
    public Field<JSON> field7() {
        return DocTest.DOC_TEST.JSON;
    }

    @Override
    public Field<BigDecimal> field8() {
        return DocTest.DOC_TEST.NR;
    }

    @Override
    public Field<String> field9() {
        return DocTest.DOC_TEST.COUNTRY_ID;
    }

    @Override
    public Integer component1() {
        return getDocId();
    }

    @Override
    public String component2() {
        return getShortText();
    }

    @Override
    public String component3() {
        return getLongText();
    }

    @Override
    public LocalDate component4() {
        return getDate();
    }

    @Override
    public Integer component5() {
        return getInt();
    }

    @Override
    public Boolean component6() {
        return getIsDone();
    }

    @Override
    public JSON component7() {
        return getJson();
    }

    @Override
    public BigDecimal component8() {
        return getNr();
    }

    @Override
    public String component9() {
        return getCountryId();
    }

    @Override
    public Integer value1() {
        return getDocId();
    }

    @Override
    public String value2() {
        return getShortText();
    }

    @Override
    public String value3() {
        return getLongText();
    }

    @Override
    public LocalDate value4() {
        return getDate();
    }

    @Override
    public Integer value5() {
        return getInt();
    }

    @Override
    public Boolean value6() {
        return getIsDone();
    }

    @Override
    public JSON value7() {
        return getJson();
    }

    @Override
    public BigDecimal value8() {
        return getNr();
    }

    @Override
    public String value9() {
        return getCountryId();
    }

    @Override
    public DocTestRecord value1(Integer value) {
        setDocId(value);
        return this;
    }

    @Override
    public DocTestRecord value2(String value) {
        setShortText(value);
        return this;
    }

    @Override
    public DocTestRecord value3(String value) {
        setLongText(value);
        return this;
    }

    @Override
    public DocTestRecord value4(LocalDate value) {
        setDate(value);
        return this;
    }

    @Override
    public DocTestRecord value5(Integer value) {
        setInt(value);
        return this;
    }

    @Override
    public DocTestRecord value6(Boolean value) {
        setIsDone(value);
        return this;
    }

    @Override
    public DocTestRecord value7(JSON value) {
        setJson(value);
        return this;
    }

    @Override
    public DocTestRecord value8(BigDecimal value) {
        setNr(value);
        return this;
    }

    @Override
    public DocTestRecord value9(String value) {
        setCountryId(value);
        return this;
    }

    @Override
    public DocTestRecord values(Integer value1, String value2, String value3, LocalDate value4, Integer value5, Boolean value6, JSON value7, BigDecimal value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DocTestRecord
     */
    public DocTestRecord() {
        super(DocTest.DOC_TEST);
    }

    /**
     * Create a detached, initialised DocTestRecord
     */
    public DocTestRecord(Integer docId, String shortText, String longText, LocalDate date, Integer int_, Boolean isDone, JSON json, BigDecimal nr, String countryId) {
        super(DocTest.DOC_TEST);

        setDocId(docId);
        setShortText(shortText);
        setLongText(longText);
        setDate(date);
        setInt(int_);
        setIsDone(isDone);
        setJson(json);
        setNr(nr);
        setCountryId(countryId);
    }
}
