/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.test.model.db.tables.records;


import io.zeitwert.fm.test.model.db.tables.ObjTest;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObjTestRecord extends UpdatableRecordImpl<ObjTestRecord> implements Record11<Integer, Integer, String, String, LocalDate, Integer, Boolean, JSON, BigDecimal, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.obj_test.obj_id</code>.
     */
    public void setObjId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.obj_test.obj_id</code>.
     */
    public Integer getObjId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.obj_test.tenant_id</code>.
     */
    public void setTenantId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.obj_test.tenant_id</code>.
     */
    public Integer getTenantId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.obj_test.short_text</code>.
     */
    public void setShortText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.obj_test.short_text</code>.
     */
    public String getShortText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.obj_test.long_text</code>.
     */
    public void setLongText(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.obj_test.long_text</code>.
     */
    public String getLongText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.obj_test.date</code>.
     */
    public void setDate(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.obj_test.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>public.obj_test.int</code>.
     */
    public void setInt(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.obj_test.int</code>.
     */
    public Integer getInt() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.obj_test.is_done</code>.
     */
    public void setIsDone(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.obj_test.is_done</code>.
     */
    public Boolean getIsDone() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.obj_test.json</code>.
     */
    public void setJson(JSON value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.obj_test.json</code>.
     */
    public JSON getJson() {
        return (JSON) get(7);
    }

    /**
     * Setter for <code>public.obj_test.nr</code>.
     */
    public void setNr(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.obj_test.nr</code>.
     */
    public BigDecimal getNr() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>public.obj_test.country_id</code>.
     */
    public void setCountryId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.obj_test.country_id</code>.
     */
    public String getCountryId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.obj_test.ref_test_id</code>.
     */
    public void setRefTestId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.obj_test.ref_test_id</code>.
     */
    public Integer getRefTestId() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, Integer, String, String, LocalDate, Integer, Boolean, JSON, BigDecimal, String, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Integer, Integer, String, String, LocalDate, Integer, Boolean, JSON, BigDecimal, String, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ObjTest.OBJ_TEST.OBJ_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ObjTest.OBJ_TEST.TENANT_ID;
    }

    @Override
    public Field<String> field3() {
        return ObjTest.OBJ_TEST.SHORT_TEXT;
    }

    @Override
    public Field<String> field4() {
        return ObjTest.OBJ_TEST.LONG_TEXT;
    }

    @Override
    public Field<LocalDate> field5() {
        return ObjTest.OBJ_TEST.DATE;
    }

    @Override
    public Field<Integer> field6() {
        return ObjTest.OBJ_TEST.INT;
    }

    @Override
    public Field<Boolean> field7() {
        return ObjTest.OBJ_TEST.IS_DONE;
    }

    @Override
    public Field<JSON> field8() {
        return ObjTest.OBJ_TEST.JSON;
    }

    @Override
    public Field<BigDecimal> field9() {
        return ObjTest.OBJ_TEST.NR;
    }

    @Override
    public Field<String> field10() {
        return ObjTest.OBJ_TEST.COUNTRY_ID;
    }

    @Override
    public Field<Integer> field11() {
        return ObjTest.OBJ_TEST.REF_TEST_ID;
    }

    @Override
    public Integer component1() {
        return getObjId();
    }

    @Override
    public Integer component2() {
        return getTenantId();
    }

    @Override
    public String component3() {
        return getShortText();
    }

    @Override
    public String component4() {
        return getLongText();
    }

    @Override
    public LocalDate component5() {
        return getDate();
    }

    @Override
    public Integer component6() {
        return getInt();
    }

    @Override
    public Boolean component7() {
        return getIsDone();
    }

    @Override
    public JSON component8() {
        return getJson();
    }

    @Override
    public BigDecimal component9() {
        return getNr();
    }

    @Override
    public String component10() {
        return getCountryId();
    }

    @Override
    public Integer component11() {
        return getRefTestId();
    }

    @Override
    public Integer value1() {
        return getObjId();
    }

    @Override
    public Integer value2() {
        return getTenantId();
    }

    @Override
    public String value3() {
        return getShortText();
    }

    @Override
    public String value4() {
        return getLongText();
    }

    @Override
    public LocalDate value5() {
        return getDate();
    }

    @Override
    public Integer value6() {
        return getInt();
    }

    @Override
    public Boolean value7() {
        return getIsDone();
    }

    @Override
    public JSON value8() {
        return getJson();
    }

    @Override
    public BigDecimal value9() {
        return getNr();
    }

    @Override
    public String value10() {
        return getCountryId();
    }

    @Override
    public Integer value11() {
        return getRefTestId();
    }

    @Override
    public ObjTestRecord value1(Integer value) {
        setObjId(value);
        return this;
    }

    @Override
    public ObjTestRecord value2(Integer value) {
        setTenantId(value);
        return this;
    }

    @Override
    public ObjTestRecord value3(String value) {
        setShortText(value);
        return this;
    }

    @Override
    public ObjTestRecord value4(String value) {
        setLongText(value);
        return this;
    }

    @Override
    public ObjTestRecord value5(LocalDate value) {
        setDate(value);
        return this;
    }

    @Override
    public ObjTestRecord value6(Integer value) {
        setInt(value);
        return this;
    }

    @Override
    public ObjTestRecord value7(Boolean value) {
        setIsDone(value);
        return this;
    }

    @Override
    public ObjTestRecord value8(JSON value) {
        setJson(value);
        return this;
    }

    @Override
    public ObjTestRecord value9(BigDecimal value) {
        setNr(value);
        return this;
    }

    @Override
    public ObjTestRecord value10(String value) {
        setCountryId(value);
        return this;
    }

    @Override
    public ObjTestRecord value11(Integer value) {
        setRefTestId(value);
        return this;
    }

    @Override
    public ObjTestRecord values(Integer value1, Integer value2, String value3, String value4, LocalDate value5, Integer value6, Boolean value7, JSON value8, BigDecimal value9, String value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ObjTestRecord
     */
    public ObjTestRecord() {
        super(ObjTest.OBJ_TEST);
    }

    /**
     * Create a detached, initialised ObjTestRecord
     */
    public ObjTestRecord(Integer objId, Integer tenantId, String shortText, String longText, LocalDate date, Integer int_, Boolean isDone, JSON json, BigDecimal nr, String countryId, Integer refTestId) {
        super(ObjTest.OBJ_TEST);

        setObjId(objId);
        setTenantId(tenantId);
        setShortText(shortText);
        setLongText(longText);
        setDate(date);
        setInt(int_);
        setIsDone(isDone);
        setJson(json);
        setNr(nr);
        setCountryId(countryId);
        setRefTestId(refTestId);
    }
}
