/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.dddrive.doc.model.db.tables.records;


import io.zeitwert.dddrive.doc.model.db.tables.CodeCaseDef;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class CodeCaseDefRecord extends UpdatableRecordImpl<CodeCaseDefRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Create a detached CodeCaseDefRecord
	 */
	public CodeCaseDefRecord() {
		super(CodeCaseDef.CODE_CASE_DEF);
	}

	/**
	 * Create a detached, initialised CodeCaseDefRecord
	 */
	public CodeCaseDefRecord(String id, String docTypeId, String name) {
		super(CodeCaseDef.CODE_CASE_DEF);

		setId(id);
		setDocTypeId(docTypeId);
		setName(name);
		resetChangedOnNotNull();
	}

	/**
	 * Getter for <code>public.code_case_def.id</code>.
	 */
	public String getId() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>public.code_case_def.id</code>.
	 */
	public void setId(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>public.code_case_def.doc_type_id</code>.
	 */
	public String getDocTypeId() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>public.code_case_def.doc_type_id</code>.
	 */
	public void setDocTypeId(String value) {
		set(1, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>public.code_case_def.name</code>.
	 */
	public String getName() {
		return (String) get(2);
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>public.code_case_def.name</code>.
	 */
	public void setName(String value) {
		set(2, value);
	}

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

}
