/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.dddrive.doc.model.db.tables.records;


import io.zeitwert.dddrive.doc.model.db.tables.DocActivityV;

import java.time.OffsetDateTime;

import org.jooq.JSON;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class DocActivityVRecord extends TableRecordImpl<DocActivityVRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Create a detached DocActivityVRecord
	 */
	public DocActivityVRecord() {
		super(DocActivityV.DOC_ACTIVITY_V);
	}

	/**
	 * Create a detached, initialised DocActivityVRecord
	 */
	public DocActivityVRecord(Integer id, String aggregateTypeId, Integer seqNr, OffsetDateTime timestamp, Integer userId, Integer tenantId, JSON changes, Integer ownerId, Integer accountId, String docTypeId, String caption, String oldCaseStageId, String newCaseStageId) {
		super(DocActivityV.DOC_ACTIVITY_V);

		setId(id);
		setAggregateTypeId(aggregateTypeId);
		setSeqNr(seqNr);
		setTimestamp(timestamp);
		setUserId(userId);
		setTenantId(tenantId);
		setChanges(changes);
		setOwnerId(ownerId);
		setAccountId(accountId);
		setDocTypeId(docTypeId);
		setCaption(caption);
		setOldCaseStageId(oldCaseStageId);
		setNewCaseStageId(newCaseStageId);
		resetChangedOnNotNull();
	}

	/**
	 * Getter for <code>public.doc_activity_v.id</code>.
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>public.doc_activity_v.id</code>.
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>public.doc_activity_v.aggregate_type_id</code>.
	 */
	public String getAggregateTypeId() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>public.doc_activity_v.aggregate_type_id</code>.
	 */
	public void setAggregateTypeId(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>public.doc_activity_v.seq_nr</code>.
	 */
	public Integer getSeqNr() {
		return (Integer) get(2);
	}

	/**
	 * Setter for <code>public.doc_activity_v.seq_nr</code>.
	 */
	public void setSeqNr(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>public.doc_activity_v.timestamp</code>.
	 */
	public OffsetDateTime getTimestamp() {
		return (OffsetDateTime) get(3);
	}

	/**
	 * Setter for <code>public.doc_activity_v.timestamp</code>.
	 */
	public void setTimestamp(OffsetDateTime value) {
		set(3, value);
	}

	/**
	 * Getter for <code>public.doc_activity_v.user_id</code>.
	 */
	public Integer getUserId() {
		return (Integer) get(4);
	}

	/**
	 * Setter for <code>public.doc_activity_v.user_id</code>.
	 */
	public void setUserId(Integer value) {
		set(4, value);
	}

	/**
	 * Getter for <code>public.doc_activity_v.tenant_id</code>.
	 */
	public Integer getTenantId() {
		return (Integer) get(5);
	}

	/**
	 * Setter for <code>public.doc_activity_v.tenant_id</code>.
	 */
	public void setTenantId(Integer value) {
		set(5, value);
	}

	/**
	 * Getter for <code>public.doc_activity_v.changes</code>.
	 */
	public JSON getChanges() {
		return (JSON) get(6);
	}

	/**
	 * Setter for <code>public.doc_activity_v.changes</code>.
	 */
	public void setChanges(JSON value) {
		set(6, value);
	}

	/**
	 * Getter for <code>public.doc_activity_v.owner_id</code>.
	 */
	public Integer getOwnerId() {
		return (Integer) get(7);
	}

	/**
	 * Setter for <code>public.doc_activity_v.owner_id</code>.
	 */
	public void setOwnerId(Integer value) {
		set(7, value);
	}

	/**
	 * Getter for <code>public.doc_activity_v.account_id</code>.
	 */
	public Integer getAccountId() {
		return (Integer) get(8);
	}

	/**
	 * Setter for <code>public.doc_activity_v.account_id</code>.
	 */
	public void setAccountId(Integer value) {
		set(8, value);
	}

	/**
	 * Getter for <code>public.doc_activity_v.doc_type_id</code>.
	 */
	public String getDocTypeId() {
		return (String) get(9);
	}

	/**
	 * Setter for <code>public.doc_activity_v.doc_type_id</code>.
	 */
	public void setDocTypeId(String value) {
		set(9, value);
	}

	/**
	 * Getter for <code>public.doc_activity_v.caption</code>.
	 */
	public String getCaption() {
		return (String) get(10);
	}

	/**
	 * Setter for <code>public.doc_activity_v.caption</code>.
	 */
	public void setCaption(String value) {
		set(10, value);
	}

	/**
	 * Getter for <code>public.doc_activity_v.old_case_stage_id</code>.
	 */
	public String getOldCaseStageId() {
		return (String) get(11);
	}

	/**
	 * Setter for <code>public.doc_activity_v.old_case_stage_id</code>.
	 */
	public void setOldCaseStageId(String value) {
		set(11, value);
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>public.doc_activity_v.new_case_stage_id</code>.
	 */
	public String getNewCaseStageId() {
		return (String) get(12);
	}

	/**
	 * Setter for <code>public.doc_activity_v.new_case_stage_id</code>.
	 */
	public void setNewCaseStageId(String value) {
		set(12, value);
	}

}
