/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.item.model.db;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.item_part_id_seq</code>
     */
    public static final Sequence<Long> ITEM_PART_ID_SEQ = Internal.createSequence("item_part_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
