/*
 * This file is generated by jOOQ.
 */
package fm.comunas.ddd.aggregate.model.db.tables;


import fm.comunas.ddd.aggregate.model.db.Keys;
import fm.comunas.ddd.aggregate.model.db.Public;
import fm.comunas.ddd.aggregate.model.db.tables.records.CodePartListTypeRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CodePartListType extends TableImpl<CodePartListTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.code_part_list_type</code>
     */
    public static final CodePartListType CODE_PART_LIST_TYPE = new CodePartListType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodePartListTypeRecord> getRecordType() {
        return CodePartListTypeRecord.class;
    }

    /**
     * The column <code>public.code_part_list_type.id</code>.
     */
    public final TableField<CodePartListTypeRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.code_part_list_type.name</code>.
     */
    public final TableField<CodePartListTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private CodePartListType(Name alias, Table<CodePartListTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private CodePartListType(Name alias, Table<CodePartListTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.code_part_list_type</code> table reference
     */
    public CodePartListType(String alias) {
        this(DSL.name(alias), CODE_PART_LIST_TYPE);
    }

    /**
     * Create an aliased <code>public.code_part_list_type</code> table reference
     */
    public CodePartListType(Name alias) {
        this(alias, CODE_PART_LIST_TYPE);
    }

    /**
     * Create a <code>public.code_part_list_type</code> table reference
     */
    public CodePartListType() {
        this(DSL.name("code_part_list_type"), null);
    }

    public <O extends Record> CodePartListType(Table<O> child, ForeignKey<O, CodePartListTypeRecord> key) {
        super(child, key, CODE_PART_LIST_TYPE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<CodePartListTypeRecord> getPrimaryKey() {
        return Keys.CODE_PART_LIST_TYPE_PKEY;
    }

    @Override
    public List<UniqueKey<CodePartListTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<CodePartListTypeRecord>>asList(Keys.CODE_PART_LIST_TYPE_PKEY);
    }

    @Override
    public CodePartListType as(String alias) {
        return new CodePartListType(DSL.name(alias), this);
    }

    @Override
    public CodePartListType as(Name alias) {
        return new CodePartListType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodePartListType rename(String name) {
        return new CodePartListType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodePartListType rename(Name name) {
        return new CodePartListType(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
