/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.test.model.db.tables.records;


import io.zeitwert.fm.test.model.db.tables.ObjTestV;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;

import org.jooq.JSON;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ObjTestVRecord extends TableRecordImpl<ObjTestVRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.obj_test_v.obj_type_id</code>.
     */
    public void setObjTypeId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.obj_test_v.obj_type_id</code>.
     */
    public String getObjTypeId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.obj_test_v.id</code>.
     */
    public void setId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.obj_test_v.id</code>.
     */
    public Integer getId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.obj_test_v.version</code>.
     */
    public void setVersion(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.obj_test_v.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.obj_test_v.owner_id</code>.
     */
    public void setOwnerId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.obj_test_v.owner_id</code>.
     */
    public Integer getOwnerId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.obj_test_v.caption</code>.
     */
    public void setCaption(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.obj_test_v.caption</code>.
     */
    public String getCaption() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.obj_test_v.created_by_user_id</code>.
     */
    public void setCreatedByUserId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.obj_test_v.created_by_user_id</code>.
     */
    public Integer getCreatedByUserId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.obj_test_v.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.obj_test_v.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.obj_test_v.modified_by_user_id</code>.
     */
    public void setModifiedByUserId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.obj_test_v.modified_by_user_id</code>.
     */
    public Integer getModifiedByUserId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.obj_test_v.modified_at</code>.
     */
    public void setModifiedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.obj_test_v.modified_at</code>.
     */
    public OffsetDateTime getModifiedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.obj_test_v.closed_by_user_id</code>.
     */
    public void setClosedByUserId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.obj_test_v.closed_by_user_id</code>.
     */
    public Integer getClosedByUserId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.obj_test_v.closed_at</code>.
     */
    public void setClosedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.obj_test_v.closed_at</code>.
     */
    public OffsetDateTime getClosedAt() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>public.obj_test_v.obj_id</code>.
     */
    public void setObjId(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.obj_test_v.obj_id</code>.
     */
    public Integer getObjId() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.obj_test_v.tenant_id</code>.
     */
    public void setTenantId(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.obj_test_v.tenant_id</code>.
     */
    public Integer getTenantId() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.obj_test_v.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.obj_test_v.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.obj_test_v.short_text</code>.
     */
    public void setShortText(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.obj_test_v.short_text</code>.
     */
    public String getShortText() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.obj_test_v.long_text</code>.
     */
    public void setLongText(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.obj_test_v.long_text</code>.
     */
    public String getLongText() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.obj_test_v.date</code>.
     */
    public void setDate(LocalDate value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.obj_test_v.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(16);
    }

    /**
     * Setter for <code>public.obj_test_v.int</code>.
     */
    public void setInt(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.obj_test_v.int</code>.
     */
    public Integer getInt() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>public.obj_test_v.is_done</code>.
     */
    public void setIsDone(Boolean value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.obj_test_v.is_done</code>.
     */
    public Boolean getIsDone() {
        return (Boolean) get(18);
    }

    /**
     * Setter for <code>public.obj_test_v.json</code>.
     */
    public void setJson(JSON value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.obj_test_v.json</code>.
     */
    public JSON getJson() {
        return (JSON) get(19);
    }

    /**
     * Setter for <code>public.obj_test_v.nr</code>.
     */
    public void setNr(BigDecimal value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.obj_test_v.nr</code>.
     */
    public BigDecimal getNr() {
        return (BigDecimal) get(20);
    }

    /**
     * Setter for <code>public.obj_test_v.test_type_id</code>.
     */
    public void setTestTypeId(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.obj_test_v.test_type_id</code>.
     */
    public String getTestTypeId() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.obj_test_v.ref_test_id</code>.
     */
    public void setRefTestId(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.obj_test_v.ref_test_id</code>.
     */
    public Integer getRefTestId() {
        return (Integer) get(22);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ObjTestVRecord
     */
    public ObjTestVRecord() {
        super(ObjTestV.OBJ_TEST_V);
    }

    /**
     * Create a detached, initialised ObjTestVRecord
     */
    public ObjTestVRecord(String objTypeId, Integer id, Integer version, Integer ownerId, String caption, Integer createdByUserId, OffsetDateTime createdAt, Integer modifiedByUserId, OffsetDateTime modifiedAt, Integer closedByUserId, OffsetDateTime closedAt, Integer objId, Integer tenantId, Integer accountId, String shortText, String longText, LocalDate date, Integer int_, Boolean isDone, JSON json, BigDecimal nr, String testTypeId, Integer refTestId) {
        super(ObjTestV.OBJ_TEST_V);

        setObjTypeId(objTypeId);
        setId(id);
        setVersion(version);
        setOwnerId(ownerId);
        setCaption(caption);
        setCreatedByUserId(createdByUserId);
        setCreatedAt(createdAt);
        setModifiedByUserId(modifiedByUserId);
        setModifiedAt(modifiedAt);
        setClosedByUserId(closedByUserId);
        setClosedAt(closedAt);
        setObjId(objId);
        setTenantId(tenantId);
        setAccountId(accountId);
        setShortText(shortText);
        setLongText(longText);
        setDate(date);
        setInt(int_);
        setIsDone(isDone);
        setJson(json);
        setNr(nr);
        setTestTypeId(testTypeId);
        setRefTestId(refTestId);
        resetChangedOnNotNull();
    }
}
