/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.ddd.oe.model.db.tables;


import io.zeitwert.ddd.oe.model.db.Keys;
import io.zeitwert.ddd.oe.model.db.Public;
import io.zeitwert.ddd.oe.model.db.tables.records.CodeUserRoleRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CodeUserRole extends TableImpl<CodeUserRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.code_user_role</code>
     */
    public static final CodeUserRole CODE_USER_ROLE = new CodeUserRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeUserRoleRecord> getRecordType() {
        return CodeUserRoleRecord.class;
    }

    /**
     * The column <code>public.code_user_role.id</code>.
     */
    public final TableField<CodeUserRoleRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.code_user_role.name</code>.
     */
    public final TableField<CodeUserRoleRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private CodeUserRole(Name alias, Table<CodeUserRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private CodeUserRole(Name alias, Table<CodeUserRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.code_user_role</code> table reference
     */
    public CodeUserRole(String alias) {
        this(DSL.name(alias), CODE_USER_ROLE);
    }

    /**
     * Create an aliased <code>public.code_user_role</code> table reference
     */
    public CodeUserRole(Name alias) {
        this(alias, CODE_USER_ROLE);
    }

    /**
     * Create a <code>public.code_user_role</code> table reference
     */
    public CodeUserRole() {
        this(DSL.name("code_user_role"), null);
    }

    public <O extends Record> CodeUserRole(Table<O> child, ForeignKey<O, CodeUserRoleRecord> key) {
        super(child, key, CODE_USER_ROLE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<CodeUserRoleRecord> getPrimaryKey() {
        return Keys.CODE_USER_ROLE_PKEY;
    }

    @Override
    public List<UniqueKey<CodeUserRoleRecord>> getKeys() {
        return Arrays.<UniqueKey<CodeUserRoleRecord>>asList(Keys.CODE_USER_ROLE_PKEY);
    }

    @Override
    public CodeUserRole as(String alias) {
        return new CodeUserRole(DSL.name(alias), this);
    }

    @Override
    public CodeUserRole as(Name alias) {
        return new CodeUserRole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeUserRole rename(String name) {
        return new CodeUserRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeUserRole rename(Name name) {
        return new CodeUserRole(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
