/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.ddd.oe.model.db.tables;


import io.zeitwert.ddd.oe.model.db.Indexes;
import io.zeitwert.ddd.oe.model.db.Keys;
import io.zeitwert.ddd.oe.model.db.Public;
import io.zeitwert.ddd.oe.model.db.tables.records.ObjUserRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObjUser extends TableImpl<ObjUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.obj_user</code>
     */
    public static final ObjUser OBJ_USER = new ObjUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ObjUserRecord> getRecordType() {
        return ObjUserRecord.class;
    }

    /**
     * The column <code>public.obj_user.obj_id</code>.
     */
    public final TableField<ObjUserRecord, Integer> OBJ_ID = createField(DSL.name("obj_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.obj_user.tenant_id</code>.
     */
    public final TableField<ObjUserRecord, Integer> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.obj_user.email</code>.
     */
    public final TableField<ObjUserRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.obj_user.name</code>.
     */
    public final TableField<ObjUserRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.obj_user.role_list</code>.
     */
    public final TableField<ObjUserRecord, String> ROLE_LIST = createField(DSL.name("role_list"), SQLDataType.VARCHAR(400).nullable(false), this, "");

    /**
     * The column <code>public.obj_user.description</code>.
     */
    public final TableField<ObjUserRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.obj_user.password</code>.
     */
    public final TableField<ObjUserRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.obj_user.need_password_change</code>.
     */
    public final TableField<ObjUserRecord, Boolean> NEED_PASSWORD_CHANGE = createField(DSL.name("need_password_change"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.obj_user.picture</code>.
     */
    public final TableField<ObjUserRecord, String> PICTURE = createField(DSL.name("picture"), SQLDataType.VARCHAR(400), this, "");

    /**
     * The column <code>public.obj_user.avatar_img_id</code>.
     */
    public final TableField<ObjUserRecord, Integer> AVATAR_IMG_ID = createField(DSL.name("avatar_img_id"), SQLDataType.INTEGER, this, "");

    private ObjUser(Name alias, Table<ObjUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private ObjUser(Name alias, Table<ObjUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.obj_user</code> table reference
     */
    public ObjUser(String alias) {
        this(DSL.name(alias), OBJ_USER);
    }

    /**
     * Create an aliased <code>public.obj_user</code> table reference
     */
    public ObjUser(Name alias) {
        this(alias, OBJ_USER);
    }

    /**
     * Create a <code>public.obj_user</code> table reference
     */
    public ObjUser() {
        this(DSL.name("obj_user"), null);
    }

    public <O extends Record> ObjUser(Table<O> child, ForeignKey<O, ObjUserRecord> key) {
        super(child, key, OBJ_USER);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.OBJ_USER$EMAIL, Indexes.OBJ_USER$TENANT);
    }

    @Override
    public UniqueKey<ObjUserRecord> getPrimaryKey() {
        return Keys.OBJ_USER_PKEY;
    }

    @Override
    public List<UniqueKey<ObjUserRecord>> getKeys() {
        return Arrays.<UniqueKey<ObjUserRecord>>asList(Keys.OBJ_USER_PKEY, Keys.EMAIL_UNIQUE);
    }

    @Override
    public List<ForeignKey<ObjUserRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ObjUserRecord, ?>>asList(Keys.OBJ_USER__OBJ_USER_TENANT_ID_FKEY);
    }

    private transient ObjTenant _objTenant;

    public ObjTenant objTenant() {
        if (_objTenant == null)
            _objTenant = new ObjTenant(this, Keys.OBJ_USER__OBJ_USER_TENANT_ID_FKEY);

        return _objTenant;
    }

    @Override
    public ObjUser as(String alias) {
        return new ObjUser(DSL.name(alias), this);
    }

    @Override
    public ObjUser as(Name alias) {
        return new ObjUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjUser rename(String name) {
        return new ObjUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjUser rename(Name name) {
        return new ObjUser(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, Integer, String, String, String, String, String, Boolean, String, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
