/*
 * This file is generated by jOOQ.
 */
package fm.comunas.fm.building.model.db.tables.records;


import fm.comunas.fm.building.model.db.tables.CodeBuildingPriceIndex;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CodeBuildingPriceIndexRecord extends UpdatableRecordImpl<CodeBuildingPriceIndexRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.code_building_price_index.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.code_building_price_index.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.code_building_price_index.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.code_building_price_index.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return CodeBuildingPriceIndex.CODE_BUILDING_PRICE_INDEX.ID;
    }

    @Override
    public Field<String> field2() {
        return CodeBuildingPriceIndex.CODE_BUILDING_PRICE_INDEX.NAME;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public CodeBuildingPriceIndexRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public CodeBuildingPriceIndexRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CodeBuildingPriceIndexRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CodeBuildingPriceIndexRecord
     */
    public CodeBuildingPriceIndexRecord() {
        super(CodeBuildingPriceIndex.CODE_BUILDING_PRICE_INDEX);
    }

    /**
     * Create a detached, initialised CodeBuildingPriceIndexRecord
     */
    public CodeBuildingPriceIndexRecord(String id, String name) {
        super(CodeBuildingPriceIndex.CODE_BUILDING_PRICE_INDEX);

        setId(id);
        setName(name);
    }
}
