/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.account.model.db.tables.records;


import io.zeitwert.fm.account.model.db.tables.ObjAccountV;

import java.math.BigDecimal;
import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObjAccountVRecord extends TableRecordImpl<ObjAccountVRecord> implements Record22<String, Integer, Integer, Integer, String, Integer, OffsetDateTime, Integer, OffsetDateTime, Integer, OffsetDateTime, Integer, Integer, String, String, String, String, Integer, String, Integer, BigDecimal, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.obj_account_v.obj_type_id</code>.
     */
    public void setObjTypeId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.obj_account_v.obj_type_id</code>.
     */
    public String getObjTypeId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.obj_account_v.id</code>.
     */
    public void setId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.obj_account_v.id</code>.
     */
    public Integer getId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.obj_account_v.version</code>.
     */
    public void setVersion(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.obj_account_v.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.obj_account_v.owner_id</code>.
     */
    public void setOwnerId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.obj_account_v.owner_id</code>.
     */
    public Integer getOwnerId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.obj_account_v.caption</code>.
     */
    public void setCaption(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.obj_account_v.caption</code>.
     */
    public String getCaption() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.obj_account_v.created_by_user_id</code>.
     */
    public void setCreatedByUserId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.obj_account_v.created_by_user_id</code>.
     */
    public Integer getCreatedByUserId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.obj_account_v.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.obj_account_v.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.obj_account_v.modified_by_user_id</code>.
     */
    public void setModifiedByUserId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.obj_account_v.modified_by_user_id</code>.
     */
    public Integer getModifiedByUserId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.obj_account_v.modified_at</code>.
     */
    public void setModifiedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.obj_account_v.modified_at</code>.
     */
    public OffsetDateTime getModifiedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.obj_account_v.closed_by_user_id</code>.
     */
    public void setClosedByUserId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.obj_account_v.closed_by_user_id</code>.
     */
    public Integer getClosedByUserId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.obj_account_v.closed_at</code>.
     */
    public void setClosedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.obj_account_v.closed_at</code>.
     */
    public OffsetDateTime getClosedAt() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>public.obj_account_v.obj_id</code>.
     */
    public void setObjId(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.obj_account_v.obj_id</code>.
     */
    public Integer getObjId() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.obj_account_v.tenant_id</code>.
     */
    public void setTenantId(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.obj_account_v.tenant_id</code>.
     */
    public Integer getTenantId() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.obj_account_v.name</code>.
     */
    public void setName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.obj_account_v.name</code>.
     */
    public String getName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.obj_account_v.description</code>.
     */
    public void setDescription(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.obj_account_v.description</code>.
     */
    public String getDescription() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.obj_account_v.account_type_id</code>.
     */
    public void setAccountTypeId(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.obj_account_v.account_type_id</code>.
     */
    public String getAccountTypeId() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.obj_account_v.client_segment_id</code>.
     */
    public void setClientSegmentId(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.obj_account_v.client_segment_id</code>.
     */
    public String getClientSegmentId() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.obj_account_v.main_contact_id</code>.
     */
    public void setMainContactId(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.obj_account_v.main_contact_id</code>.
     */
    public Integer getMainContactId() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>public.obj_account_v.reference_currency_id</code>.
     */
    public void setReferenceCurrencyId(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.obj_account_v.reference_currency_id</code>.
     */
    public String getReferenceCurrencyId() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.obj_account_v.logo_img_id</code>.
     */
    public void setLogoImgId(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.obj_account_v.logo_img_id</code>.
     */
    public Integer getLogoImgId() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>public.obj_account_v.inflation_rate</code>.
     */
    public void setInflationRate(BigDecimal value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.obj_account_v.inflation_rate</code>.
     */
    public BigDecimal getInflationRate() {
        return (BigDecimal) get(20);
    }

    /**
     * Setter for <code>public.obj_account_v.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.obj_account_v.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(21);
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row22<String, Integer, Integer, Integer, String, Integer, OffsetDateTime, Integer, OffsetDateTime, Integer, OffsetDateTime, Integer, Integer, String, String, String, String, Integer, String, Integer, BigDecimal, Integer> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    @Override
    public Row22<String, Integer, Integer, Integer, String, Integer, OffsetDateTime, Integer, OffsetDateTime, Integer, OffsetDateTime, Integer, Integer, String, String, String, String, Integer, String, Integer, BigDecimal, Integer> valuesRow() {
        return (Row22) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ObjAccountV.OBJ_ACCOUNT_V.OBJ_TYPE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ObjAccountV.OBJ_ACCOUNT_V.ID;
    }

    @Override
    public Field<Integer> field3() {
        return ObjAccountV.OBJ_ACCOUNT_V.VERSION;
    }

    @Override
    public Field<Integer> field4() {
        return ObjAccountV.OBJ_ACCOUNT_V.OWNER_ID;
    }

    @Override
    public Field<String> field5() {
        return ObjAccountV.OBJ_ACCOUNT_V.CAPTION;
    }

    @Override
    public Field<Integer> field6() {
        return ObjAccountV.OBJ_ACCOUNT_V.CREATED_BY_USER_ID;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return ObjAccountV.OBJ_ACCOUNT_V.CREATED_AT;
    }

    @Override
    public Field<Integer> field8() {
        return ObjAccountV.OBJ_ACCOUNT_V.MODIFIED_BY_USER_ID;
    }

    @Override
    public Field<OffsetDateTime> field9() {
        return ObjAccountV.OBJ_ACCOUNT_V.MODIFIED_AT;
    }

    @Override
    public Field<Integer> field10() {
        return ObjAccountV.OBJ_ACCOUNT_V.CLOSED_BY_USER_ID;
    }

    @Override
    public Field<OffsetDateTime> field11() {
        return ObjAccountV.OBJ_ACCOUNT_V.CLOSED_AT;
    }

    @Override
    public Field<Integer> field12() {
        return ObjAccountV.OBJ_ACCOUNT_V.OBJ_ID;
    }

    @Override
    public Field<Integer> field13() {
        return ObjAccountV.OBJ_ACCOUNT_V.TENANT_ID;
    }

    @Override
    public Field<String> field14() {
        return ObjAccountV.OBJ_ACCOUNT_V.NAME;
    }

    @Override
    public Field<String> field15() {
        return ObjAccountV.OBJ_ACCOUNT_V.DESCRIPTION;
    }

    @Override
    public Field<String> field16() {
        return ObjAccountV.OBJ_ACCOUNT_V.ACCOUNT_TYPE_ID;
    }

    @Override
    public Field<String> field17() {
        return ObjAccountV.OBJ_ACCOUNT_V.CLIENT_SEGMENT_ID;
    }

    @Override
    public Field<Integer> field18() {
        return ObjAccountV.OBJ_ACCOUNT_V.MAIN_CONTACT_ID;
    }

    @Override
    public Field<String> field19() {
        return ObjAccountV.OBJ_ACCOUNT_V.REFERENCE_CURRENCY_ID;
    }

    @Override
    public Field<Integer> field20() {
        return ObjAccountV.OBJ_ACCOUNT_V.LOGO_IMG_ID;
    }

    @Override
    public Field<BigDecimal> field21() {
        return ObjAccountV.OBJ_ACCOUNT_V.INFLATION_RATE;
    }

    @Override
    public Field<Integer> field22() {
        return ObjAccountV.OBJ_ACCOUNT_V.ACCOUNT_ID;
    }

    @Override
    public String component1() {
        return getObjTypeId();
    }

    @Override
    public Integer component2() {
        return getId();
    }

    @Override
    public Integer component3() {
        return getVersion();
    }

    @Override
    public Integer component4() {
        return getOwnerId();
    }

    @Override
    public String component5() {
        return getCaption();
    }

    @Override
    public Integer component6() {
        return getCreatedByUserId();
    }

    @Override
    public OffsetDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public Integer component8() {
        return getModifiedByUserId();
    }

    @Override
    public OffsetDateTime component9() {
        return getModifiedAt();
    }

    @Override
    public Integer component10() {
        return getClosedByUserId();
    }

    @Override
    public OffsetDateTime component11() {
        return getClosedAt();
    }

    @Override
    public Integer component12() {
        return getObjId();
    }

    @Override
    public Integer component13() {
        return getTenantId();
    }

    @Override
    public String component14() {
        return getName();
    }

    @Override
    public String component15() {
        return getDescription();
    }

    @Override
    public String component16() {
        return getAccountTypeId();
    }

    @Override
    public String component17() {
        return getClientSegmentId();
    }

    @Override
    public Integer component18() {
        return getMainContactId();
    }

    @Override
    public String component19() {
        return getReferenceCurrencyId();
    }

    @Override
    public Integer component20() {
        return getLogoImgId();
    }

    @Override
    public BigDecimal component21() {
        return getInflationRate();
    }

    @Override
    public Integer component22() {
        return getAccountId();
    }

    @Override
    public String value1() {
        return getObjTypeId();
    }

    @Override
    public Integer value2() {
        return getId();
    }

    @Override
    public Integer value3() {
        return getVersion();
    }

    @Override
    public Integer value4() {
        return getOwnerId();
    }

    @Override
    public String value5() {
        return getCaption();
    }

    @Override
    public Integer value6() {
        return getCreatedByUserId();
    }

    @Override
    public OffsetDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public Integer value8() {
        return getModifiedByUserId();
    }

    @Override
    public OffsetDateTime value9() {
        return getModifiedAt();
    }

    @Override
    public Integer value10() {
        return getClosedByUserId();
    }

    @Override
    public OffsetDateTime value11() {
        return getClosedAt();
    }

    @Override
    public Integer value12() {
        return getObjId();
    }

    @Override
    public Integer value13() {
        return getTenantId();
    }

    @Override
    public String value14() {
        return getName();
    }

    @Override
    public String value15() {
        return getDescription();
    }

    @Override
    public String value16() {
        return getAccountTypeId();
    }

    @Override
    public String value17() {
        return getClientSegmentId();
    }

    @Override
    public Integer value18() {
        return getMainContactId();
    }

    @Override
    public String value19() {
        return getReferenceCurrencyId();
    }

    @Override
    public Integer value20() {
        return getLogoImgId();
    }

    @Override
    public BigDecimal value21() {
        return getInflationRate();
    }

    @Override
    public Integer value22() {
        return getAccountId();
    }

    @Override
    public ObjAccountVRecord value1(String value) {
        setObjTypeId(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value2(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value3(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value4(Integer value) {
        setOwnerId(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value5(String value) {
        setCaption(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value6(Integer value) {
        setCreatedByUserId(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value7(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value8(Integer value) {
        setModifiedByUserId(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value9(OffsetDateTime value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value10(Integer value) {
        setClosedByUserId(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value11(OffsetDateTime value) {
        setClosedAt(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value12(Integer value) {
        setObjId(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value13(Integer value) {
        setTenantId(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value14(String value) {
        setName(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value15(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value16(String value) {
        setAccountTypeId(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value17(String value) {
        setClientSegmentId(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value18(Integer value) {
        setMainContactId(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value19(String value) {
        setReferenceCurrencyId(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value20(Integer value) {
        setLogoImgId(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value21(BigDecimal value) {
        setInflationRate(value);
        return this;
    }

    @Override
    public ObjAccountVRecord value22(Integer value) {
        setAccountId(value);
        return this;
    }

    @Override
    public ObjAccountVRecord values(String value1, Integer value2, Integer value3, Integer value4, String value5, Integer value6, OffsetDateTime value7, Integer value8, OffsetDateTime value9, Integer value10, OffsetDateTime value11, Integer value12, Integer value13, String value14, String value15, String value16, String value17, Integer value18, String value19, Integer value20, BigDecimal value21, Integer value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ObjAccountVRecord
     */
    public ObjAccountVRecord() {
        super(ObjAccountV.OBJ_ACCOUNT_V);
    }

    /**
     * Create a detached, initialised ObjAccountVRecord
     */
    public ObjAccountVRecord(String objTypeId, Integer id, Integer version, Integer ownerId, String caption, Integer createdByUserId, OffsetDateTime createdAt, Integer modifiedByUserId, OffsetDateTime modifiedAt, Integer closedByUserId, OffsetDateTime closedAt, Integer objId, Integer tenantId, String name, String description, String accountTypeId, String clientSegmentId, Integer mainContactId, String referenceCurrencyId, Integer logoImgId, BigDecimal inflationRate, Integer accountId) {
        super(ObjAccountV.OBJ_ACCOUNT_V);

        setObjTypeId(objTypeId);
        setId(id);
        setVersion(version);
        setOwnerId(ownerId);
        setCaption(caption);
        setCreatedByUserId(createdByUserId);
        setCreatedAt(createdAt);
        setModifiedByUserId(modifiedByUserId);
        setModifiedAt(modifiedAt);
        setClosedByUserId(closedByUserId);
        setClosedAt(closedAt);
        setObjId(objId);
        setTenantId(tenantId);
        setName(name);
        setDescription(description);
        setAccountTypeId(accountTypeId);
        setClientSegmentId(clientSegmentId);
        setMainContactId(mainContactId);
        setReferenceCurrencyId(referenceCurrencyId);
        setLogoImgId(logoImgId);
        setInflationRate(inflationRate);
        setAccountId(accountId);
    }
}
