/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.lead.model.db.tables.records;


import io.zeitwert.fm.lead.model.db.tables.DocLead;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocLeadRecord extends UpdatableRecordImpl<DocLeadRecord> implements Record21<Integer, Integer, Integer, Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.doc_lead.doc_id</code>.
     */
    public void setDocId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.doc_lead.doc_id</code>.
     */
    public Integer getDocId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.doc_lead.tenant_id</code>.
     */
    public void setTenantId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.doc_lead.tenant_id</code>.
     */
    public Integer getTenantId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.doc_lead.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.doc_lead.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.doc_lead.contact_id</code>.
     */
    public void setContactId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.doc_lead.contact_id</code>.
     */
    public Integer getContactId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.doc_lead.intl_key</code>.
     */
    public void setIntlKey(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.doc_lead.intl_key</code>.
     */
    public String getIntlKey() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.doc_lead.subject</code>.
     */
    public void setSubject(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.doc_lead.subject</code>.
     */
    public String getSubject() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.doc_lead.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.doc_lead.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.doc_lead.lead_source_id</code>.
     */
    public void setLeadSourceId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.doc_lead.lead_source_id</code>.
     */
    public String getLeadSourceId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.doc_lead.salutation_id</code>.
     */
    public void setSalutationId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.doc_lead.salutation_id</code>.
     */
    public String getSalutationId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.doc_lead.title_id</code>.
     */
    public void setTitleId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.doc_lead.title_id</code>.
     */
    public String getTitleId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.doc_lead.first_name</code>.
     */
    public void setFirstName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.doc_lead.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.doc_lead.last_name</code>.
     */
    public void setLastName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.doc_lead.last_name</code>.
     */
    public String getLastName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.doc_lead.phone</code>.
     */
    public void setPhone(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.doc_lead.phone</code>.
     */
    public String getPhone() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.doc_lead.mobile</code>.
     */
    public void setMobile(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.doc_lead.mobile</code>.
     */
    public String getMobile() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.doc_lead.email</code>.
     */
    public void setEmail(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.doc_lead.email</code>.
     */
    public String getEmail() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.doc_lead.lead_rating_id</code>.
     */
    public void setLeadRatingId(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.doc_lead.lead_rating_id</code>.
     */
    public String getLeadRatingId() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.doc_lead.street</code>.
     */
    public void setStreet(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.doc_lead.street</code>.
     */
    public String getStreet() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.doc_lead.zip</code>.
     */
    public void setZip(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.doc_lead.zip</code>.
     */
    public String getZip() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.doc_lead.city</code>.
     */
    public void setCity(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.doc_lead.city</code>.
     */
    public String getCity() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.doc_lead.state</code>.
     */
    public void setState(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.doc_lead.state</code>.
     */
    public String getState() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.doc_lead.country_id</code>.
     */
    public void setCountryId(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.doc_lead.country_id</code>.
     */
    public String getCountryId() {
        return (String) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row21<Integer, Integer, Integer, Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    @Override
    public Row21<Integer, Integer, Integer, Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row21) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DocLead.DOC_LEAD.DOC_ID;
    }

    @Override
    public Field<Integer> field2() {
        return DocLead.DOC_LEAD.TENANT_ID;
    }

    @Override
    public Field<Integer> field3() {
        return DocLead.DOC_LEAD.ACCOUNT_ID;
    }

    @Override
    public Field<Integer> field4() {
        return DocLead.DOC_LEAD.CONTACT_ID;
    }

    @Override
    public Field<String> field5() {
        return DocLead.DOC_LEAD.INTL_KEY;
    }

    @Override
    public Field<String> field6() {
        return DocLead.DOC_LEAD.SUBJECT;
    }

    @Override
    public Field<String> field7() {
        return DocLead.DOC_LEAD.DESCRIPTION;
    }

    @Override
    public Field<String> field8() {
        return DocLead.DOC_LEAD.LEAD_SOURCE_ID;
    }

    @Override
    public Field<String> field9() {
        return DocLead.DOC_LEAD.SALUTATION_ID;
    }

    @Override
    public Field<String> field10() {
        return DocLead.DOC_LEAD.TITLE_ID;
    }

    @Override
    public Field<String> field11() {
        return DocLead.DOC_LEAD.FIRST_NAME;
    }

    @Override
    public Field<String> field12() {
        return DocLead.DOC_LEAD.LAST_NAME;
    }

    @Override
    public Field<String> field13() {
        return DocLead.DOC_LEAD.PHONE;
    }

    @Override
    public Field<String> field14() {
        return DocLead.DOC_LEAD.MOBILE;
    }

    @Override
    public Field<String> field15() {
        return DocLead.DOC_LEAD.EMAIL;
    }

    @Override
    public Field<String> field16() {
        return DocLead.DOC_LEAD.LEAD_RATING_ID;
    }

    @Override
    public Field<String> field17() {
        return DocLead.DOC_LEAD.STREET;
    }

    @Override
    public Field<String> field18() {
        return DocLead.DOC_LEAD.ZIP;
    }

    @Override
    public Field<String> field19() {
        return DocLead.DOC_LEAD.CITY;
    }

    @Override
    public Field<String> field20() {
        return DocLead.DOC_LEAD.STATE;
    }

    @Override
    public Field<String> field21() {
        return DocLead.DOC_LEAD.COUNTRY_ID;
    }

    @Override
    public Integer component1() {
        return getDocId();
    }

    @Override
    public Integer component2() {
        return getTenantId();
    }

    @Override
    public Integer component3() {
        return getAccountId();
    }

    @Override
    public Integer component4() {
        return getContactId();
    }

    @Override
    public String component5() {
        return getIntlKey();
    }

    @Override
    public String component6() {
        return getSubject();
    }

    @Override
    public String component7() {
        return getDescription();
    }

    @Override
    public String component8() {
        return getLeadSourceId();
    }

    @Override
    public String component9() {
        return getSalutationId();
    }

    @Override
    public String component10() {
        return getTitleId();
    }

    @Override
    public String component11() {
        return getFirstName();
    }

    @Override
    public String component12() {
        return getLastName();
    }

    @Override
    public String component13() {
        return getPhone();
    }

    @Override
    public String component14() {
        return getMobile();
    }

    @Override
    public String component15() {
        return getEmail();
    }

    @Override
    public String component16() {
        return getLeadRatingId();
    }

    @Override
    public String component17() {
        return getStreet();
    }

    @Override
    public String component18() {
        return getZip();
    }

    @Override
    public String component19() {
        return getCity();
    }

    @Override
    public String component20() {
        return getState();
    }

    @Override
    public String component21() {
        return getCountryId();
    }

    @Override
    public Integer value1() {
        return getDocId();
    }

    @Override
    public Integer value2() {
        return getTenantId();
    }

    @Override
    public Integer value3() {
        return getAccountId();
    }

    @Override
    public Integer value4() {
        return getContactId();
    }

    @Override
    public String value5() {
        return getIntlKey();
    }

    @Override
    public String value6() {
        return getSubject();
    }

    @Override
    public String value7() {
        return getDescription();
    }

    @Override
    public String value8() {
        return getLeadSourceId();
    }

    @Override
    public String value9() {
        return getSalutationId();
    }

    @Override
    public String value10() {
        return getTitleId();
    }

    @Override
    public String value11() {
        return getFirstName();
    }

    @Override
    public String value12() {
        return getLastName();
    }

    @Override
    public String value13() {
        return getPhone();
    }

    @Override
    public String value14() {
        return getMobile();
    }

    @Override
    public String value15() {
        return getEmail();
    }

    @Override
    public String value16() {
        return getLeadRatingId();
    }

    @Override
    public String value17() {
        return getStreet();
    }

    @Override
    public String value18() {
        return getZip();
    }

    @Override
    public String value19() {
        return getCity();
    }

    @Override
    public String value20() {
        return getState();
    }

    @Override
    public String value21() {
        return getCountryId();
    }

    @Override
    public DocLeadRecord value1(Integer value) {
        setDocId(value);
        return this;
    }

    @Override
    public DocLeadRecord value2(Integer value) {
        setTenantId(value);
        return this;
    }

    @Override
    public DocLeadRecord value3(Integer value) {
        setAccountId(value);
        return this;
    }

    @Override
    public DocLeadRecord value4(Integer value) {
        setContactId(value);
        return this;
    }

    @Override
    public DocLeadRecord value5(String value) {
        setIntlKey(value);
        return this;
    }

    @Override
    public DocLeadRecord value6(String value) {
        setSubject(value);
        return this;
    }

    @Override
    public DocLeadRecord value7(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public DocLeadRecord value8(String value) {
        setLeadSourceId(value);
        return this;
    }

    @Override
    public DocLeadRecord value9(String value) {
        setSalutationId(value);
        return this;
    }

    @Override
    public DocLeadRecord value10(String value) {
        setTitleId(value);
        return this;
    }

    @Override
    public DocLeadRecord value11(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public DocLeadRecord value12(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public DocLeadRecord value13(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public DocLeadRecord value14(String value) {
        setMobile(value);
        return this;
    }

    @Override
    public DocLeadRecord value15(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public DocLeadRecord value16(String value) {
        setLeadRatingId(value);
        return this;
    }

    @Override
    public DocLeadRecord value17(String value) {
        setStreet(value);
        return this;
    }

    @Override
    public DocLeadRecord value18(String value) {
        setZip(value);
        return this;
    }

    @Override
    public DocLeadRecord value19(String value) {
        setCity(value);
        return this;
    }

    @Override
    public DocLeadRecord value20(String value) {
        setState(value);
        return this;
    }

    @Override
    public DocLeadRecord value21(String value) {
        setCountryId(value);
        return this;
    }

    @Override
    public DocLeadRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, String value17, String value18, String value19, String value20, String value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DocLeadRecord
     */
    public DocLeadRecord() {
        super(DocLead.DOC_LEAD);
    }

    /**
     * Create a detached, initialised DocLeadRecord
     */
    public DocLeadRecord(Integer docId, Integer tenantId, Integer accountId, Integer contactId, String intlKey, String subject, String description, String leadSourceId, String salutationId, String titleId, String firstName, String lastName, String phone, String mobile, String email, String leadRatingId, String street, String zip, String city, String state, String countryId) {
        super(DocLead.DOC_LEAD);

        setDocId(docId);
        setTenantId(tenantId);
        setAccountId(accountId);
        setContactId(contactId);
        setIntlKey(intlKey);
        setSubject(subject);
        setDescription(description);
        setLeadSourceId(leadSourceId);
        setSalutationId(salutationId);
        setTitleId(titleId);
        setFirstName(firstName);
        setLastName(lastName);
        setPhone(phone);
        setMobile(mobile);
        setEmail(email);
        setLeadRatingId(leadRatingId);
        setStreet(street);
        setZip(zip);
        setCity(city);
        setState(state);
        setCountryId(countryId);
    }
}
