/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.doc.model.db.tables;


import io.zeitwert.fm.doc.model.db.Keys;
import io.zeitwert.fm.doc.model.db.Public;
import io.zeitwert.fm.doc.model.db.tables.CodeCaseDef.CodeCaseDefPath;
import io.zeitwert.fm.doc.model.db.tables.CodeCaseStage.CodeCaseStagePath;
import io.zeitwert.fm.doc.model.db.tables.CodeCaseStageType.CodeCaseStageTypePath;
import io.zeitwert.fm.doc.model.db.tables.Doc.DocPath;
import io.zeitwert.fm.doc.model.db.tables.DocPartTransition.DocPartTransitionPath;
import io.zeitwert.fm.doc.model.db.tables.records.CodeCaseStageRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeCaseStage extends TableImpl<CodeCaseStageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.code_case_stage</code>
     */
    public static final CodeCaseStage CODE_CASE_STAGE = new CodeCaseStage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeCaseStageRecord> getRecordType() {
        return CodeCaseStageRecord.class;
    }

    /**
     * The column <code>public.code_case_stage.id</code>.
     */
    public final TableField<CodeCaseStageRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.code_case_stage.case_def_id</code>.
     */
    public final TableField<CodeCaseStageRecord, String> CASE_DEF_ID = createField(DSL.name("case_def_id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.code_case_stage.seq_nr</code>.
     */
    public final TableField<CodeCaseStageRecord, Integer> SEQ_NR = createField(DSL.name("seq_nr"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.code_case_stage.case_stage_type_id</code>.
     */
    public final TableField<CodeCaseStageRecord, String> CASE_STAGE_TYPE_ID = createField(DSL.name("case_stage_type_id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.code_case_stage.name</code>.
     */
    public final TableField<CodeCaseStageRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.code_case_stage.description</code>.
     */
    public final TableField<CodeCaseStageRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.code_case_stage.due</code>.
     */
    public final TableField<CodeCaseStageRecord, Integer> DUE = createField(DSL.name("due"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.code_case_stage.action</code>.
     */
    public final TableField<CodeCaseStageRecord, String> ACTION = createField(DSL.name("action"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.code_case_stage.abstract_case_stage_id</code>.
     */
    public final TableField<CodeCaseStageRecord, String> ABSTRACT_CASE_STAGE_ID = createField(DSL.name("abstract_case_stage_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.code_case_stage.available_actions</code>.
     */
    public final TableField<CodeCaseStageRecord, String> AVAILABLE_ACTIONS = createField(DSL.name("available_actions"), SQLDataType.VARCHAR(1000), this, "");

    private CodeCaseStage(Name alias, Table<CodeCaseStageRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CodeCaseStage(Name alias, Table<CodeCaseStageRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.code_case_stage</code> table reference
     */
    public CodeCaseStage(String alias) {
        this(DSL.name(alias), CODE_CASE_STAGE);
    }

    /**
     * Create an aliased <code>public.code_case_stage</code> table reference
     */
    public CodeCaseStage(Name alias) {
        this(alias, CODE_CASE_STAGE);
    }

    /**
     * Create a <code>public.code_case_stage</code> table reference
     */
    public CodeCaseStage() {
        this(DSL.name("code_case_stage"), null);
    }

    public <O extends Record> CodeCaseStage(Table<O> path, ForeignKey<O, CodeCaseStageRecord> childPath, InverseForeignKey<O, CodeCaseStageRecord> parentPath) {
        super(path, childPath, parentPath, CODE_CASE_STAGE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CodeCaseStagePath extends CodeCaseStage implements Path<CodeCaseStageRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CodeCaseStagePath(Table<O> path, ForeignKey<O, CodeCaseStageRecord> childPath, InverseForeignKey<O, CodeCaseStageRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CodeCaseStagePath(Name alias, Table<CodeCaseStageRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CodeCaseStagePath as(String alias) {
            return new CodeCaseStagePath(DSL.name(alias), this);
        }

        @Override
        public CodeCaseStagePath as(Name alias) {
            return new CodeCaseStagePath(alias, this);
        }

        @Override
        public CodeCaseStagePath as(Table<?> alias) {
            return new CodeCaseStagePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CodeCaseStageRecord> getPrimaryKey() {
        return Keys.CODE_CASE_STAGE_PKEY;
    }

    @Override
    public List<ForeignKey<CodeCaseStageRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CODE_CASE_STAGE__CODE_CASE_STAGE_ABSTRACT_CASE_STAGE_ID_FKEY, Keys.CODE_CASE_STAGE__CODE_CASE_STAGE_CASE_DEF_ID_FKEY, Keys.CODE_CASE_STAGE__CODE_CASE_STAGE_CASE_STAGE_TYPE_ID_FKEY);
    }

    private transient CodeCaseStagePath _codeCaseStage;

    /**
     * Get the implicit join path to the <code>public.code_case_stage</code>
     * table.
     */
    public CodeCaseStagePath codeCaseStage() {
        if (_codeCaseStage == null)
            _codeCaseStage = new CodeCaseStagePath(this, Keys.CODE_CASE_STAGE__CODE_CASE_STAGE_ABSTRACT_CASE_STAGE_ID_FKEY, null);

        return _codeCaseStage;
    }

    private transient CodeCaseDefPath _codeCaseDef;

    /**
     * Get the implicit join path to the <code>public.code_case_def</code>
     * table.
     */
    public CodeCaseDefPath codeCaseDef() {
        if (_codeCaseDef == null)
            _codeCaseDef = new CodeCaseDefPath(this, Keys.CODE_CASE_STAGE__CODE_CASE_STAGE_CASE_DEF_ID_FKEY, null);

        return _codeCaseDef;
    }

    private transient CodeCaseStageTypePath _codeCaseStageType;

    /**
     * Get the implicit join path to the
     * <code>public.code_case_stage_type</code> table.
     */
    public CodeCaseStageTypePath codeCaseStageType() {
        if (_codeCaseStageType == null)
            _codeCaseStageType = new CodeCaseStageTypePath(this, Keys.CODE_CASE_STAGE__CODE_CASE_STAGE_CASE_STAGE_TYPE_ID_FKEY, null);

        return _codeCaseStageType;
    }

    private transient DocPath _doc;

    /**
     * Get the implicit to-many join path to the <code>public.doc</code> table
     */
    public DocPath doc() {
        if (_doc == null)
            _doc = new DocPath(this, null, Keys.DOC__DOC_CASE_STAGE_ID_FKEY.getInverseKey());

        return _doc;
    }

    private transient DocPartTransitionPath _docPartTransitionNewCaseStageIdFkey;

    /**
     * Get the implicit to-many join path to the
     * <code>public.doc_part_transition</code> table, via the
     * <code>doc_part_transition_new_case_stage_id_fkey</code> key
     */
    public DocPartTransitionPath docPartTransitionNewCaseStageIdFkey() {
        if (_docPartTransitionNewCaseStageIdFkey == null)
            _docPartTransitionNewCaseStageIdFkey = new DocPartTransitionPath(this, null, Keys.DOC_PART_TRANSITION__DOC_PART_TRANSITION_NEW_CASE_STAGE_ID_FKEY.getInverseKey());

        return _docPartTransitionNewCaseStageIdFkey;
    }

    private transient DocPartTransitionPath _docPartTransitionOldCaseStageIdFkey;

    /**
     * Get the implicit to-many join path to the
     * <code>public.doc_part_transition</code> table, via the
     * <code>doc_part_transition_old_case_stage_id_fkey</code> key
     */
    public DocPartTransitionPath docPartTransitionOldCaseStageIdFkey() {
        if (_docPartTransitionOldCaseStageIdFkey == null)
            _docPartTransitionOldCaseStageIdFkey = new DocPartTransitionPath(this, null, Keys.DOC_PART_TRANSITION__DOC_PART_TRANSITION_OLD_CASE_STAGE_ID_FKEY.getInverseKey());

        return _docPartTransitionOldCaseStageIdFkey;
    }

    @Override
    public CodeCaseStage as(String alias) {
        return new CodeCaseStage(DSL.name(alias), this);
    }

    @Override
    public CodeCaseStage as(Name alias) {
        return new CodeCaseStage(alias, this);
    }

    @Override
    public CodeCaseStage as(Table<?> alias) {
        return new CodeCaseStage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeCaseStage rename(String name) {
        return new CodeCaseStage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeCaseStage rename(Name name) {
        return new CodeCaseStage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeCaseStage rename(Table<?> name) {
        return new CodeCaseStage(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeCaseStage where(Condition condition) {
        return new CodeCaseStage(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeCaseStage where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeCaseStage where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeCaseStage where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeCaseStage where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeCaseStage where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeCaseStage where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeCaseStage where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeCaseStage whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeCaseStage whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
