/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.oe.model.db.tables.records;


import io.zeitwert.fm.oe.model.db.tables.CodeLocale;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CodeLocaleRecord extends UpdatableRecordImpl<CodeLocaleRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.code_locale.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.code_locale.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.code_locale.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.code_locale.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return CodeLocale.CODE_LOCALE.ID;
    }

    @Override
    public Field<String> field2() {
        return CodeLocale.CODE_LOCALE.NAME;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public CodeLocaleRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public CodeLocaleRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CodeLocaleRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CodeLocaleRecord
     */
    public CodeLocaleRecord() {
        super(CodeLocale.CODE_LOCALE);
    }

    /**
     * Create a detached, initialised CodeLocaleRecord
     */
    public CodeLocaleRecord(String id, String name) {
        super(CodeLocale.CODE_LOCALE);

        setId(id);
        setName(name);
    }
}
