/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.task.model.db.tables.records;


import io.zeitwert.fm.task.model.db.tables.DocTaskV;
import org.jooq.impl.TableRecordImpl;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class DocTaskVRecord extends TableRecordImpl<DocTaskVRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Create a detached DocTaskVRecord
	 */
	public DocTaskVRecord() {
		super(DocTaskV.DOC_TASK_V);
	}

	/**
	 * Create a detached, initialised DocTaskVRecord
	 */
	public DocTaskVRecord(String docTypeId, Integer id, Integer version, Integer ownerId, String caption, String caseDefId, String caseStageId, Boolean isInWork, Integer assigneeId, Integer createdByUserId, OffsetDateTime createdAt, Integer modifiedByUserId, OffsetDateTime modifiedAt, Integer docId, Integer tenantId, Integer accountId, String subject, String content, Boolean isPrivate, String priorityId, OffsetDateTime dueAt, OffsetDateTime remindAt, Integer relatedToId) {
		super(DocTaskV.DOC_TASK_V);

		setDocTypeId(docTypeId);
		setId(id);
		setVersion(version);
		setOwnerId(ownerId);
		setCaption(caption);
		setCaseDefId(caseDefId);
		setCaseStageId(caseStageId);
		setIsInWork(isInWork);
		setAssigneeId(assigneeId);
		setCreatedByUserId(createdByUserId);
		setCreatedAt(createdAt);
		setModifiedByUserId(modifiedByUserId);
		setModifiedAt(modifiedAt);
		setDocId(docId);
		setTenantId(tenantId);
		setAccountId(accountId);
		setSubject(subject);
		setContent(content);
		setIsPrivate(isPrivate);
		setPriorityId(priorityId);
		setDueAt(dueAt);
		setRemindAt(remindAt);
		setRelatedToId(relatedToId);
		resetChangedOnNotNull();
	}

	/**
	 * Getter for <code>public.doc_task_v.doc_type_id</code>.
	 */
	public String getDocTypeId() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>public.doc_task_v.doc_type_id</code>.
	 */
	public void setDocTypeId(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.id</code>.
	 */
	public Integer getId() {
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>public.doc_task_v.id</code>.
	 */
	public void setId(Integer value) {
		set(1, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.version</code>.
	 */
	public Integer getVersion() {
		return (Integer) get(2);
	}

	/**
	 * Setter for <code>public.doc_task_v.version</code>.
	 */
	public void setVersion(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.owner_id</code>.
	 */
	public Integer getOwnerId() {
		return (Integer) get(3);
	}

	/**
	 * Setter for <code>public.doc_task_v.owner_id</code>.
	 */
	public void setOwnerId(Integer value) {
		set(3, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.caption</code>.
	 */
	public String getCaption() {
		return (String) get(4);
	}

	/**
	 * Setter for <code>public.doc_task_v.caption</code>.
	 */
	public void setCaption(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.case_def_id</code>.
	 */
	public String getCaseDefId() {
		return (String) get(5);
	}

	/**
	 * Setter for <code>public.doc_task_v.case_def_id</code>.
	 */
	public void setCaseDefId(String value) {
		set(5, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.case_stage_id</code>.
	 */
	public String getCaseStageId() {
		return (String) get(6);
	}

	/**
	 * Setter for <code>public.doc_task_v.case_stage_id</code>.
	 */
	public void setCaseStageId(String value) {
		set(6, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.is_in_work</code>.
	 */
	public Boolean getIsInWork() {
		return (Boolean) get(7);
	}

	/**
	 * Setter for <code>public.doc_task_v.is_in_work</code>.
	 */
	public void setIsInWork(Boolean value) {
		set(7, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.assignee_id</code>.
	 */
	public Integer getAssigneeId() {
		return (Integer) get(8);
	}

	/**
	 * Setter for <code>public.doc_task_v.assignee_id</code>.
	 */
	public void setAssigneeId(Integer value) {
		set(8, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.created_by_user_id</code>.
	 */
	public Integer getCreatedByUserId() {
		return (Integer) get(9);
	}

	/**
	 * Setter for <code>public.doc_task_v.created_by_user_id</code>.
	 */
	public void setCreatedByUserId(Integer value) {
		set(9, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.created_at</code>.
	 */
	public OffsetDateTime getCreatedAt() {
		return (OffsetDateTime) get(10);
	}

	/**
	 * Setter for <code>public.doc_task_v.created_at</code>.
	 */
	public void setCreatedAt(OffsetDateTime value) {
		set(10, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.modified_by_user_id</code>.
	 */
	public Integer getModifiedByUserId() {
		return (Integer) get(11);
	}

	/**
	 * Setter for <code>public.doc_task_v.modified_by_user_id</code>.
	 */
	public void setModifiedByUserId(Integer value) {
		set(11, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.modified_at</code>.
	 */
	public OffsetDateTime getModifiedAt() {
		return (OffsetDateTime) get(12);
	}

	/**
	 * Setter for <code>public.doc_task_v.modified_at</code>.
	 */
	public void setModifiedAt(OffsetDateTime value) {
		set(12, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.doc_id</code>.
	 */
	public Integer getDocId() {
		return (Integer) get(13);
	}

	/**
	 * Setter for <code>public.doc_task_v.doc_id</code>.
	 */
	public void setDocId(Integer value) {
		set(13, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.tenant_id</code>.
	 */
	public Integer getTenantId() {
		return (Integer) get(14);
	}

	/**
	 * Setter for <code>public.doc_task_v.tenant_id</code>.
	 */
	public void setTenantId(Integer value) {
		set(14, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.account_id</code>.
	 */
	public Integer getAccountId() {
		return (Integer) get(15);
	}

	/**
	 * Setter for <code>public.doc_task_v.account_id</code>.
	 */
	public void setAccountId(Integer value) {
		set(15, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.subject</code>.
	 */
	public String getSubject() {
		return (String) get(16);
	}

	/**
	 * Setter for <code>public.doc_task_v.subject</code>.
	 */
	public void setSubject(String value) {
		set(16, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.content</code>.
	 */
	public String getContent() {
		return (String) get(17);
	}

	/**
	 * Setter for <code>public.doc_task_v.content</code>.
	 */
	public void setContent(String value) {
		set(17, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.is_private</code>.
	 */
	public Boolean getIsPrivate() {
		return (Boolean) get(18);
	}

	/**
	 * Setter for <code>public.doc_task_v.is_private</code>.
	 */
	public void setIsPrivate(Boolean value) {
		set(18, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.priority_id</code>.
	 */
	public String getPriorityId() {
		return (String) get(19);
	}

	/**
	 * Setter for <code>public.doc_task_v.priority_id</code>.
	 */
	public void setPriorityId(String value) {
		set(19, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.due_at</code>.
	 */
	public OffsetDateTime getDueAt() {
		return (OffsetDateTime) get(20);
	}

	/**
	 * Setter for <code>public.doc_task_v.due_at</code>.
	 */
	public void setDueAt(OffsetDateTime value) {
		set(20, value);
	}

	/**
	 * Getter for <code>public.doc_task_v.remind_at</code>.
	 */
	public OffsetDateTime getRemindAt() {
		return (OffsetDateTime) get(21);
	}

	/**
	 * Setter for <code>public.doc_task_v.remind_at</code>.
	 */
	public void setRemindAt(OffsetDateTime value) {
		set(21, value);
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>public.doc_task_v.related_to_id</code>.
	 */
	public Integer getRelatedToId() {
		return (Integer) get(22);
	}

	/**
	 * Setter for <code>public.doc_task_v.related_to_id</code>.
	 */
	public void setRelatedToId(Integer value) {
		set(22, value);
	}

}
