/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.dms.model.db.tables;


import io.zeitwert.fm.dms.model.db.Keys;
import io.zeitwert.fm.dms.model.db.Public;
import io.zeitwert.fm.dms.model.db.tables.records.ObjDocumentPartContentRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObjDocumentPartContent extends TableImpl<ObjDocumentPartContentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.obj_document_part_content</code>
     */
    public static final ObjDocumentPartContent OBJ_DOCUMENT_PART_CONTENT = new ObjDocumentPartContent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ObjDocumentPartContentRecord> getRecordType() {
        return ObjDocumentPartContentRecord.class;
    }

    /**
     * The column <code>public.obj_document_part_content.obj_id</code>.
     */
    public final TableField<ObjDocumentPartContentRecord, Integer> OBJ_ID = createField(DSL.name("obj_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.obj_document_part_content.version_nr</code>.
     */
    public final TableField<ObjDocumentPartContentRecord, Integer> VERSION_NR = createField(DSL.name("version_nr"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.obj_document_part_content.content_type_id</code>.
     */
    public final TableField<ObjDocumentPartContentRecord, String> CONTENT_TYPE_ID = createField(DSL.name("content_type_id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.obj_document_part_content.content</code>.
     */
    public final TableField<ObjDocumentPartContentRecord, byte[]> CONTENT = createField(DSL.name("content"), SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>public.obj_document_part_content.created_by_user_id</code>.
     */
    public final TableField<ObjDocumentPartContentRecord, Integer> CREATED_BY_USER_ID = createField(DSL.name("created_by_user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.obj_document_part_content.created_at</code>.
     */
    public final TableField<ObjDocumentPartContentRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field("(now())::timestamp without time zone", SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private ObjDocumentPartContent(Name alias, Table<ObjDocumentPartContentRecord> aliased) {
        this(alias, aliased, null);
    }

    private ObjDocumentPartContent(Name alias, Table<ObjDocumentPartContentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.obj_document_part_content</code> table reference
     */
    public ObjDocumentPartContent(String alias) {
        this(DSL.name(alias), OBJ_DOCUMENT_PART_CONTENT);
    }

    /**
     * Create an aliased <code>public.obj_document_part_content</code> table reference
     */
    public ObjDocumentPartContent(Name alias) {
        this(alias, OBJ_DOCUMENT_PART_CONTENT);
    }

    /**
     * Create a <code>public.obj_document_part_content</code> table reference
     */
    public ObjDocumentPartContent() {
        this(DSL.name("obj_document_part_content"), null);
    }

    public <O extends Record> ObjDocumentPartContent(Table<O> child, ForeignKey<O, ObjDocumentPartContentRecord> key) {
        super(child, key, OBJ_DOCUMENT_PART_CONTENT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<ObjDocumentPartContentRecord> getPrimaryKey() {
        return Keys.OBJ_DOCUMENT_PART_CONTENT_PKEY;
    }

    @Override
    public List<UniqueKey<ObjDocumentPartContentRecord>> getKeys() {
        return Arrays.<UniqueKey<ObjDocumentPartContentRecord>>asList(Keys.OBJ_DOCUMENT_PART_CONTENT_PKEY);
    }

    @Override
    public List<ForeignKey<ObjDocumentPartContentRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ObjDocumentPartContentRecord, ?>>asList(Keys.OBJ_DOCUMENT_PART_CONTENT__OBJ_DOCUMENT_PART_CONTENT_OBJ_ID_FKEY, Keys.OBJ_DOCUMENT_PART_CONTENT__OBJ_DOCUMENT_PART_CONTENT_CONTENT_TYPE_ID_FKEY);
    }

    private transient ObjDocument _objDocument;
    private transient CodeContentType _codeContentType;

    public ObjDocument objDocument() {
        if (_objDocument == null)
            _objDocument = new ObjDocument(this, Keys.OBJ_DOCUMENT_PART_CONTENT__OBJ_DOCUMENT_PART_CONTENT_OBJ_ID_FKEY);

        return _objDocument;
    }

    public CodeContentType codeContentType() {
        if (_codeContentType == null)
            _codeContentType = new CodeContentType(this, Keys.OBJ_DOCUMENT_PART_CONTENT__OBJ_DOCUMENT_PART_CONTENT_CONTENT_TYPE_ID_FKEY);

        return _codeContentType;
    }

    @Override
    public ObjDocumentPartContent as(String alias) {
        return new ObjDocumentPartContent(DSL.name(alias), this);
    }

    @Override
    public ObjDocumentPartContent as(Name alias) {
        return new ObjDocumentPartContent(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjDocumentPartContent rename(String name) {
        return new ObjDocumentPartContent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjDocumentPartContent rename(Name name) {
        return new ObjDocumentPartContent(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, byte[], Integer, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
