/*
 * This file is generated by jOOQ.
 */
package io.domain.test.model.db.tables;


import io.domain.test.model.db.Keys;
import io.domain.test.model.db.Public;
import io.domain.test.model.db.tables.DocTest.DocTestPath;
import io.domain.test.model.db.tables.DocTestPartNode.DocTestPartNodePath;
import io.domain.test.model.db.tables.ObjTest.ObjTestPath;
import io.domain.test.model.db.tables.ObjTestPartNode.ObjTestPartNodePath;
import io.domain.test.model.db.tables.records.CodeTestTypeRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeTestType extends TableImpl<CodeTestTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.code_test_type</code>
     */
    public static final CodeTestType CODE_TEST_TYPE = new CodeTestType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeTestTypeRecord> getRecordType() {
        return CodeTestTypeRecord.class;
    }

    /**
     * The column <code>public.code_test_type.id</code>.
     */
    public final TableField<CodeTestTypeRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.code_test_type.name</code>.
     */
    public final TableField<CodeTestTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    private CodeTestType(Name alias, Table<CodeTestTypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CodeTestType(Name alias, Table<CodeTestTypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.code_test_type</code> table reference
     */
    public CodeTestType(String alias) {
        this(DSL.name(alias), CODE_TEST_TYPE);
    }

    /**
     * Create an aliased <code>public.code_test_type</code> table reference
     */
    public CodeTestType(Name alias) {
        this(alias, CODE_TEST_TYPE);
    }

    /**
     * Create a <code>public.code_test_type</code> table reference
     */
    public CodeTestType() {
        this(DSL.name("code_test_type"), null);
    }

    public <O extends Record> CodeTestType(Table<O> path, ForeignKey<O, CodeTestTypeRecord> childPath, InverseForeignKey<O, CodeTestTypeRecord> parentPath) {
        super(path, childPath, parentPath, CODE_TEST_TYPE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CodeTestTypePath extends CodeTestType implements Path<CodeTestTypeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CodeTestTypePath(Table<O> path, ForeignKey<O, CodeTestTypeRecord> childPath, InverseForeignKey<O, CodeTestTypeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CodeTestTypePath(Name alias, Table<CodeTestTypeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CodeTestTypePath as(String alias) {
            return new CodeTestTypePath(DSL.name(alias), this);
        }

        @Override
        public CodeTestTypePath as(Name alias) {
            return new CodeTestTypePath(alias, this);
        }

        @Override
        public CodeTestTypePath as(Table<?> alias) {
            return new CodeTestTypePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CodeTestTypeRecord> getPrimaryKey() {
        return Keys.CODE_TEST_TYPE_PKEY;
    }

    private transient DocTestPartNodePath _docTestPartNode;

    /**
     * Get the implicit to-many join path to the
     * <code>public.doc_test_part_node</code> table
     */
    public DocTestPartNodePath docTestPartNode() {
        if (_docTestPartNode == null)
            _docTestPartNode = new DocTestPartNodePath(this, null, Keys.DOC_TEST_PART_NODE__DOC_TEST_PART_NODE_TEST_TYPE_ID_FKEY.getInverseKey());

        return _docTestPartNode;
    }

    private transient DocTestPath _docTest;

    /**
     * Get the implicit to-many join path to the <code>public.doc_test</code>
     * table
     */
    public DocTestPath docTest() {
        if (_docTest == null)
            _docTest = new DocTestPath(this, null, Keys.DOC_TEST__DOC_TEST_TEST_TYPE_ID_FKEY.getInverseKey());

        return _docTest;
    }

    private transient ObjTestPartNodePath _objTestPartNode;

    /**
     * Get the implicit to-many join path to the
     * <code>public.obj_test_part_node</code> table
     */
    public ObjTestPartNodePath objTestPartNode() {
        if (_objTestPartNode == null)
            _objTestPartNode = new ObjTestPartNodePath(this, null, Keys.OBJ_TEST_PART_NODE__OBJ_TEST_PART_NODE_TEST_TYPE_ID_FKEY.getInverseKey());

        return _objTestPartNode;
    }

    private transient ObjTestPath _objTest;

    /**
     * Get the implicit to-many join path to the <code>public.obj_test</code>
     * table
     */
    public ObjTestPath objTest() {
        if (_objTest == null)
            _objTest = new ObjTestPath(this, null, Keys.OBJ_TEST__OBJ_TEST_TEST_TYPE_ID_FKEY.getInverseKey());

        return _objTest;
    }

    @Override
    public CodeTestType as(String alias) {
        return new CodeTestType(DSL.name(alias), this);
    }

    @Override
    public CodeTestType as(Name alias) {
        return new CodeTestType(alias, this);
    }

    @Override
    public CodeTestType as(Table<?> alias) {
        return new CodeTestType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeTestType rename(String name) {
        return new CodeTestType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeTestType rename(Name name) {
        return new CodeTestType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeTestType rename(Table<?> name) {
        return new CodeTestType(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeTestType where(Condition condition) {
        return new CodeTestType(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeTestType where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeTestType where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeTestType where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeTestType where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeTestType where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeTestType where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeTestType where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeTestType whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeTestType whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
