/*
 * This file is generated by jOOQ.
 */
package io.domain.test.model.db.tables;


import io.domain.test.model.db.Public;
import io.domain.test.model.db.tables.records.ObjTestVRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ObjTestV extends TableImpl<ObjTestVRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.obj_test_v</code>
     */
    public static final ObjTestV OBJ_TEST_V = new ObjTestV();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ObjTestVRecord> getRecordType() {
        return ObjTestVRecord.class;
    }

    /**
     * The column <code>public.obj_test_v.obj_type_id</code>.
     */
    public final TableField<ObjTestVRecord, String> OBJ_TYPE_ID = createField(DSL.name("obj_type_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.obj_test_v.id</code>.
     */
    public final TableField<ObjTestVRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_test_v.version</code>.
     */
    public final TableField<ObjTestVRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_test_v.owner_id</code>.
     */
    public final TableField<ObjTestVRecord, Integer> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_test_v.caption</code>.
     */
    public final TableField<ObjTestVRecord, String> CAPTION = createField(DSL.name("caption"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.obj_test_v.created_by_user_id</code>.
     */
    public final TableField<ObjTestVRecord, Integer> CREATED_BY_USER_ID = createField(DSL.name("created_by_user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_test_v.created_at</code>.
     */
    public final TableField<ObjTestVRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.obj_test_v.modified_by_user_id</code>.
     */
    public final TableField<ObjTestVRecord, Integer> MODIFIED_BY_USER_ID = createField(DSL.name("modified_by_user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_test_v.modified_at</code>.
     */
    public final TableField<ObjTestVRecord, OffsetDateTime> MODIFIED_AT = createField(DSL.name("modified_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.obj_test_v.closed_by_user_id</code>.
     */
    public final TableField<ObjTestVRecord, Integer> CLOSED_BY_USER_ID = createField(DSL.name("closed_by_user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_test_v.closed_at</code>.
     */
    public final TableField<ObjTestVRecord, OffsetDateTime> CLOSED_AT = createField(DSL.name("closed_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.obj_test_v.obj_id</code>.
     */
    public final TableField<ObjTestVRecord, Integer> OBJ_ID = createField(DSL.name("obj_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_test_v.tenant_id</code>.
     */
    public final TableField<ObjTestVRecord, Integer> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_test_v.account_id</code>.
     */
    public final TableField<ObjTestVRecord, Integer> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_test_v.short_text</code>.
     */
    public final TableField<ObjTestVRecord, String> SHORT_TEXT = createField(DSL.name("short_text"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.obj_test_v.short_text_u</code>.
     */
    public final TableField<ObjTestVRecord, String> SHORT_TEXT_U = createField(DSL.name("short_text_u"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.obj_test_v.long_text</code>.
     */
    public final TableField<ObjTestVRecord, String> LONG_TEXT = createField(DSL.name("long_text"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.obj_test_v.date</code>.
     */
    public final TableField<ObjTestVRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.obj_test_v.int</code>.
     */
    public final TableField<ObjTestVRecord, Integer> INT = createField(DSL.name("int"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_test_v.is_done</code>.
     */
    public final TableField<ObjTestVRecord, Boolean> IS_DONE = createField(DSL.name("is_done"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.obj_test_v.json</code>.
     */
    public final TableField<ObjTestVRecord, org.jooq.JSON> JSON = createField(DSL.name("json"), SQLDataType.JSON, this, "");

    /**
     * The column <code>public.obj_test_v.nr</code>.
     */
    public final TableField<ObjTestVRecord, BigDecimal> NR = createField(DSL.name("nr"), SQLDataType.NUMERIC(18, 4), this, "");

    /**
     * The column <code>public.obj_test_v.test_type_id</code>.
     */
    public final TableField<ObjTestVRecord, String> TEST_TYPE_ID = createField(DSL.name("test_type_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.obj_test_v.ref_test_id</code>.
     */
    public final TableField<ObjTestVRecord, Integer> REF_TEST_ID = createField(DSL.name("ref_test_id"), SQLDataType.INTEGER, this, "");

    private ObjTestV(Name alias, Table<ObjTestVRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ObjTestV(Name alias, Table<ObjTestVRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "obj_test_v" as  SELECT obj.obj_type_id,
         ot.obj_id AS id,
         obj.version,
         obj.owner_id,
         obj.caption,
         obj.created_by_user_id,
         obj.created_at,
         obj.modified_by_user_id,
         obj.modified_at,
         obj.closed_by_user_id,
         obj.closed_at,
         ot.obj_id,
         ot.tenant_id,
         ot.account_id,
         ot.short_text,
         ot.short_text_u,
         ot.long_text,
         ot.date,
         ot."int",
         ot.is_done,
         ot."json",
         ot.nr,
         ot.test_type_id,
         ot.ref_test_id
        FROM (obj_test ot
          JOIN obj ON ((obj.id = ot.obj_id)));
        """), where);
    }

    /**
     * Create an aliased <code>public.obj_test_v</code> table reference
     */
    public ObjTestV(String alias) {
        this(DSL.name(alias), OBJ_TEST_V);
    }

    /**
     * Create an aliased <code>public.obj_test_v</code> table reference
     */
    public ObjTestV(Name alias) {
        this(alias, OBJ_TEST_V);
    }

    /**
     * Create a <code>public.obj_test_v</code> table reference
     */
    public ObjTestV() {
        this(DSL.name("obj_test_v"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public ObjTestV as(String alias) {
        return new ObjTestV(DSL.name(alias), this);
    }

    @Override
    public ObjTestV as(Name alias) {
        return new ObjTestV(alias, this);
    }

    @Override
    public ObjTestV as(Table<?> alias) {
        return new ObjTestV(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjTestV rename(String name) {
        return new ObjTestV(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjTestV rename(Name name) {
        return new ObjTestV(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjTestV rename(Table<?> name) {
        return new ObjTestV(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjTestV where(Condition condition) {
        return new ObjTestV(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjTestV where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjTestV where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjTestV where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ObjTestV where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ObjTestV where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ObjTestV where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ObjTestV where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjTestV whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjTestV whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
