/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.lead.model.db.tables;


import io.zeitwert.fm.lead.model.db.Public;
import io.zeitwert.fm.lead.model.db.tables.records.DocLeadVRecord;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocLeadV extends TableImpl<DocLeadVRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.doc_lead_v</code>
     */
    public static final DocLeadV DOC_LEAD_V = new DocLeadV();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DocLeadVRecord> getRecordType() {
        return DocLeadVRecord.class;
    }

    /**
     * The column <code>public.doc_lead_v.doc_type_id</code>.
     */
    public final TableField<DocLeadVRecord, String> DOC_TYPE_ID = createField(DSL.name("doc_type_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.doc_lead_v.id</code>.
     */
    public final TableField<DocLeadVRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.doc_lead_v.owner_id</code>.
     */
    public final TableField<DocLeadVRecord, Integer> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.doc_lead_v.assignee_id</code>.
     */
    public final TableField<DocLeadVRecord, Integer> ASSIGNEE_ID = createField(DSL.name("assignee_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.doc_lead_v.caption</code>.
     */
    public final TableField<DocLeadVRecord, String> CAPTION = createField(DSL.name("caption"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.doc_lead_v.case_def_id</code>.
     */
    public final TableField<DocLeadVRecord, String> CASE_DEF_ID = createField(DSL.name("case_def_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.doc_lead_v.case_stage_id</code>.
     */
    public final TableField<DocLeadVRecord, String> CASE_STAGE_ID = createField(DSL.name("case_stage_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.doc_lead_v.is_in_work</code>.
     */
    public final TableField<DocLeadVRecord, Boolean> IS_IN_WORK = createField(DSL.name("is_in_work"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.doc_lead_v.created_by_user_id</code>.
     */
    public final TableField<DocLeadVRecord, Integer> CREATED_BY_USER_ID = createField(DSL.name("created_by_user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.doc_lead_v.created_at</code>.
     */
    public final TableField<DocLeadVRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.doc_lead_v.modified_by_user_id</code>.
     */
    public final TableField<DocLeadVRecord, Integer> MODIFIED_BY_USER_ID = createField(DSL.name("modified_by_user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.doc_lead_v.modified_at</code>.
     */
    public final TableField<DocLeadVRecord, OffsetDateTime> MODIFIED_AT = createField(DSL.name("modified_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.doc_lead_v.doc_id</code>.
     */
    public final TableField<DocLeadVRecord, Integer> DOC_ID = createField(DSL.name("doc_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.doc_lead_v.tenant_id</code>.
     */
    public final TableField<DocLeadVRecord, Integer> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.doc_lead_v.account_id</code>.
     */
    public final TableField<DocLeadVRecord, Integer> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.doc_lead_v.contact_id</code>.
     */
    public final TableField<DocLeadVRecord, Integer> CONTACT_ID = createField(DSL.name("contact_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.doc_lead_v.intl_key</code>.
     */
    public final TableField<DocLeadVRecord, String> INTL_KEY = createField(DSL.name("intl_key"), SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>public.doc_lead_v.subject</code>.
     */
    public final TableField<DocLeadVRecord, String> SUBJECT = createField(DSL.name("subject"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.doc_lead_v.description</code>.
     */
    public final TableField<DocLeadVRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.doc_lead_v.lead_source_id</code>.
     */
    public final TableField<DocLeadVRecord, String> LEAD_SOURCE_ID = createField(DSL.name("lead_source_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.doc_lead_v.salutation_id</code>.
     */
    public final TableField<DocLeadVRecord, String> SALUTATION_ID = createField(DSL.name("salutation_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.doc_lead_v.title_id</code>.
     */
    public final TableField<DocLeadVRecord, String> TITLE_ID = createField(DSL.name("title_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.doc_lead_v.first_name</code>.
     */
    public final TableField<DocLeadVRecord, String> FIRST_NAME = createField(DSL.name("first_name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.doc_lead_v.last_name</code>.
     */
    public final TableField<DocLeadVRecord, String> LAST_NAME = createField(DSL.name("last_name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.doc_lead_v.phone</code>.
     */
    public final TableField<DocLeadVRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>public.doc_lead_v.mobile</code>.
     */
    public final TableField<DocLeadVRecord, String> MOBILE = createField(DSL.name("mobile"), SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>public.doc_lead_v.email</code>.
     */
    public final TableField<DocLeadVRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>public.doc_lead_v.lead_rating_id</code>.
     */
    public final TableField<DocLeadVRecord, String> LEAD_RATING_ID = createField(DSL.name("lead_rating_id"), SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>public.doc_lead_v.street</code>.
     */
    public final TableField<DocLeadVRecord, String> STREET = createField(DSL.name("street"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.doc_lead_v.zip</code>.
     */
    public final TableField<DocLeadVRecord, String> ZIP = createField(DSL.name("zip"), SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>public.doc_lead_v.city</code>.
     */
    public final TableField<DocLeadVRecord, String> CITY = createField(DSL.name("city"), SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>public.doc_lead_v.state</code>.
     */
    public final TableField<DocLeadVRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>public.doc_lead_v.country_id</code>.
     */
    public final TableField<DocLeadVRecord, String> COUNTRY_ID = createField(DSL.name("country_id"), SQLDataType.VARCHAR(40), this, "");

    private DocLeadV(Name alias, Table<DocLeadVRecord> aliased) {
        this(alias, aliased, null);
    }

    private DocLeadV(Name alias, Table<DocLeadVRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("create view \"doc_lead_v\" as  SELECT doc.doc_type_id,\n    doc.id,\n    doc.owner_id,\n    doc.assignee_id,\n    doc.caption,\n    doc.case_def_id,\n    doc.case_stage_id,\n    doc.is_in_work,\n    doc.created_by_user_id,\n    doc.created_at,\n    doc.modified_by_user_id,\n    doc.modified_at,\n    dl.doc_id,\n    dl.tenant_id,\n    dl.account_id,\n    dl.contact_id,\n    dl.intl_key,\n    dl.subject,\n    dl.description,\n    dl.lead_source_id,\n    dl.salutation_id,\n    dl.title_id,\n    dl.first_name,\n    dl.last_name,\n    dl.phone,\n    dl.mobile,\n    dl.email,\n    dl.lead_rating_id,\n    dl.street,\n    dl.zip,\n    dl.city,\n    dl.state,\n    dl.country_id\n   FROM (doc_lead dl\n     JOIN doc ON ((doc.id = dl.doc_id)));"));
    }

    /**
     * Create an aliased <code>public.doc_lead_v</code> table reference
     */
    public DocLeadV(String alias) {
        this(DSL.name(alias), DOC_LEAD_V);
    }

    /**
     * Create an aliased <code>public.doc_lead_v</code> table reference
     */
    public DocLeadV(Name alias) {
        this(alias, DOC_LEAD_V);
    }

    /**
     * Create a <code>public.doc_lead_v</code> table reference
     */
    public DocLeadV() {
        this(DSL.name("doc_lead_v"), null);
    }

    public <O extends Record> DocLeadV(Table<O> child, ForeignKey<O, DocLeadVRecord> key) {
        super(child, key, DOC_LEAD_V);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public DocLeadV as(String alias) {
        return new DocLeadV(DSL.name(alias), this);
    }

    @Override
    public DocLeadV as(Name alias) {
        return new DocLeadV(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DocLeadV rename(String name) {
        return new DocLeadV(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DocLeadV rename(Name name) {
        return new DocLeadV(name, null);
    }
}
