/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.portfolio.model.db;


import io.zeitwert.fm.portfolio.model.db.tables.ObjPortfolio;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index OBJ_PORTFOLIO$ACCOUNT = Internal.createIndex(DSL.name("obj_portfolio$account"), ObjPortfolio.OBJ_PORTFOLIO, new OrderField[] { ObjPortfolio.OBJ_PORTFOLIO.ACCOUNT_ID }, false);
}
