/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.dms.model.db.tables;


import io.zeitwert.fm.dms.model.db.Keys;
import io.zeitwert.fm.dms.model.db.Public;
import io.zeitwert.fm.dms.model.db.tables.ObjDocument.ObjDocumentPath;
import io.zeitwert.fm.dms.model.db.tables.records.CodeDocumentCategoryRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeDocumentCategory extends TableImpl<CodeDocumentCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.code_document_category</code>
     */
    public static final CodeDocumentCategory CODE_DOCUMENT_CATEGORY = new CodeDocumentCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeDocumentCategoryRecord> getRecordType() {
        return CodeDocumentCategoryRecord.class;
    }

    /**
     * The column <code>public.code_document_category.id</code>.
     */
    public final TableField<CodeDocumentCategoryRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.code_document_category.name</code>.
     */
    public final TableField<CodeDocumentCategoryRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private CodeDocumentCategory(Name alias, Table<CodeDocumentCategoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CodeDocumentCategory(Name alias, Table<CodeDocumentCategoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.code_document_category</code> table
     * reference
     */
    public CodeDocumentCategory(String alias) {
        this(DSL.name(alias), CODE_DOCUMENT_CATEGORY);
    }

    /**
     * Create an aliased <code>public.code_document_category</code> table
     * reference
     */
    public CodeDocumentCategory(Name alias) {
        this(alias, CODE_DOCUMENT_CATEGORY);
    }

    /**
     * Create a <code>public.code_document_category</code> table reference
     */
    public CodeDocumentCategory() {
        this(DSL.name("code_document_category"), null);
    }

    public <O extends Record> CodeDocumentCategory(Table<O> path, ForeignKey<O, CodeDocumentCategoryRecord> childPath, InverseForeignKey<O, CodeDocumentCategoryRecord> parentPath) {
        super(path, childPath, parentPath, CODE_DOCUMENT_CATEGORY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CodeDocumentCategoryPath extends CodeDocumentCategory implements Path<CodeDocumentCategoryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CodeDocumentCategoryPath(Table<O> path, ForeignKey<O, CodeDocumentCategoryRecord> childPath, InverseForeignKey<O, CodeDocumentCategoryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CodeDocumentCategoryPath(Name alias, Table<CodeDocumentCategoryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CodeDocumentCategoryPath as(String alias) {
            return new CodeDocumentCategoryPath(DSL.name(alias), this);
        }

        @Override
        public CodeDocumentCategoryPath as(Name alias) {
            return new CodeDocumentCategoryPath(alias, this);
        }

        @Override
        public CodeDocumentCategoryPath as(Table<?> alias) {
            return new CodeDocumentCategoryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CodeDocumentCategoryRecord> getPrimaryKey() {
        return Keys.CODE_DOCUMENT_CATEGORY_PKEY;
    }

    private transient ObjDocumentPath _objDocument;

    /**
     * Get the implicit to-many join path to the
     * <code>public.obj_document</code> table
     */
    public ObjDocumentPath objDocument() {
        if (_objDocument == null)
            _objDocument = new ObjDocumentPath(this, null, Keys.OBJ_DOCUMENT__OBJ_DOCUMENT_DOCUMENT_CATEGORY_ID_FKEY.getInverseKey());

        return _objDocument;
    }

    @Override
    public CodeDocumentCategory as(String alias) {
        return new CodeDocumentCategory(DSL.name(alias), this);
    }

    @Override
    public CodeDocumentCategory as(Name alias) {
        return new CodeDocumentCategory(alias, this);
    }

    @Override
    public CodeDocumentCategory as(Table<?> alias) {
        return new CodeDocumentCategory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeDocumentCategory rename(String name) {
        return new CodeDocumentCategory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeDocumentCategory rename(Name name) {
        return new CodeDocumentCategory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeDocumentCategory rename(Table<?> name) {
        return new CodeDocumentCategory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeDocumentCategory where(Condition condition) {
        return new CodeDocumentCategory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeDocumentCategory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeDocumentCategory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeDocumentCategory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeDocumentCategory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeDocumentCategory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeDocumentCategory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeDocumentCategory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeDocumentCategory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeDocumentCategory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
