/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.dms.model.db.tables;


import io.zeitwert.fm.dms.model.db.Public;
import io.zeitwert.fm.dms.model.db.tables.records.ObjDocumentVRecord;

import java.time.OffsetDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ObjDocumentV extends TableImpl<ObjDocumentVRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.obj_document_v</code>
     */
    public static final ObjDocumentV OBJ_DOCUMENT_V = new ObjDocumentV();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ObjDocumentVRecord> getRecordType() {
        return ObjDocumentVRecord.class;
    }

    /**
     * The column <code>public.obj_document_v.obj_type_id</code>.
     */
    public final TableField<ObjDocumentVRecord, String> OBJ_TYPE_ID = createField(DSL.name("obj_type_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.obj_document_v.id</code>.
     */
    public final TableField<ObjDocumentVRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_document_v.version</code>.
     */
    public final TableField<ObjDocumentVRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_document_v.owner_id</code>.
     */
    public final TableField<ObjDocumentVRecord, Integer> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_document_v.caption</code>.
     */
    public final TableField<ObjDocumentVRecord, String> CAPTION = createField(DSL.name("caption"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.obj_document_v.created_by_user_id</code>.
     */
    public final TableField<ObjDocumentVRecord, Integer> CREATED_BY_USER_ID = createField(DSL.name("created_by_user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_document_v.created_at</code>.
     */
    public final TableField<ObjDocumentVRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.obj_document_v.modified_by_user_id</code>.
     */
    public final TableField<ObjDocumentVRecord, Integer> MODIFIED_BY_USER_ID = createField(DSL.name("modified_by_user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_document_v.modified_at</code>.
     */
    public final TableField<ObjDocumentVRecord, OffsetDateTime> MODIFIED_AT = createField(DSL.name("modified_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.obj_document_v.closed_by_user_id</code>.
     */
    public final TableField<ObjDocumentVRecord, Integer> CLOSED_BY_USER_ID = createField(DSL.name("closed_by_user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_document_v.closed_at</code>.
     */
    public final TableField<ObjDocumentVRecord, OffsetDateTime> CLOSED_AT = createField(DSL.name("closed_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.obj_document_v.obj_id</code>.
     */
    public final TableField<ObjDocumentVRecord, Integer> OBJ_ID = createField(DSL.name("obj_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_document_v.tenant_id</code>.
     */
    public final TableField<ObjDocumentVRecord, Integer> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_document_v.account_id</code>.
     */
    public final TableField<ObjDocumentVRecord, Integer> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.obj_document_v.document_kind_id</code>.
     */
    public final TableField<ObjDocumentVRecord, String> DOCUMENT_KIND_ID = createField(DSL.name("document_kind_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.obj_document_v.content_kind_id</code>.
     */
    public final TableField<ObjDocumentVRecord, String> CONTENT_KIND_ID = createField(DSL.name("content_kind_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.obj_document_v.name</code>.
     */
    public final TableField<ObjDocumentVRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.obj_document_v.document_category_id</code>.
     */
    public final TableField<ObjDocumentVRecord, String> DOCUMENT_CATEGORY_ID = createField(DSL.name("document_category_id"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.obj_document_v.template_document_id</code>.
     */
    public final TableField<ObjDocumentVRecord, Integer> TEMPLATE_DOCUMENT_ID = createField(DSL.name("template_document_id"), SQLDataType.INTEGER, this, "");

    private ObjDocumentV(Name alias, Table<ObjDocumentVRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ObjDocumentV(Name alias, Table<ObjDocumentVRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "obj_document_v" as  SELECT obj.obj_type_id,
         d.obj_id AS id,
         obj.version,
         obj.owner_id,
         obj.caption,
         obj.created_by_user_id,
         obj.created_at,
         obj.modified_by_user_id,
         obj.modified_at,
         obj.closed_by_user_id,
         obj.closed_at,
         d.obj_id,
         d.tenant_id,
         d.account_id,
         d.document_kind_id,
         d.content_kind_id,
         d.name,
         d.document_category_id,
         d.template_document_id
        FROM (obj_document d
          JOIN obj ON ((obj.id = d.obj_id)));
        """), where);
    }

    /**
     * Create an aliased <code>public.obj_document_v</code> table reference
     */
    public ObjDocumentV(String alias) {
        this(DSL.name(alias), OBJ_DOCUMENT_V);
    }

    /**
     * Create an aliased <code>public.obj_document_v</code> table reference
     */
    public ObjDocumentV(Name alias) {
        this(alias, OBJ_DOCUMENT_V);
    }

    /**
     * Create a <code>public.obj_document_v</code> table reference
     */
    public ObjDocumentV() {
        this(DSL.name("obj_document_v"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public ObjDocumentV as(String alias) {
        return new ObjDocumentV(DSL.name(alias), this);
    }

    @Override
    public ObjDocumentV as(Name alias) {
        return new ObjDocumentV(alias, this);
    }

    @Override
    public ObjDocumentV as(Table<?> alias) {
        return new ObjDocumentV(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjDocumentV rename(String name) {
        return new ObjDocumentV(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjDocumentV rename(Name name) {
        return new ObjDocumentV(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ObjDocumentV rename(Table<?> name) {
        return new ObjDocumentV(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjDocumentV where(Condition condition) {
        return new ObjDocumentV(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjDocumentV where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjDocumentV where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjDocumentV where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ObjDocumentV where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ObjDocumentV where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ObjDocumentV where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ObjDocumentV where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjDocumentV whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ObjDocumentV whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
