/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.ddd.oe.model.db;


import io.zeitwert.ddd.oe.model.db.tables.CodeTenantType;
import io.zeitwert.ddd.oe.model.db.tables.CodeUserRole;
import io.zeitwert.ddd.oe.model.db.tables.ObjTenant;
import io.zeitwert.ddd.oe.model.db.tables.ObjTenantV;
import io.zeitwert.ddd.oe.model.db.tables.ObjUser;
import io.zeitwert.ddd.oe.model.db.tables.ObjUserV;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.code_tenant_type</code>.
     */
    public static final CodeTenantType CODE_TENANT_TYPE = CodeTenantType.CODE_TENANT_TYPE;

    /**
     * The table <code>public.code_user_role</code>.
     */
    public static final CodeUserRole CODE_USER_ROLE = CodeUserRole.CODE_USER_ROLE;

    /**
     * The table <code>public.obj_tenant</code>.
     */
    public static final ObjTenant OBJ_TENANT = ObjTenant.OBJ_TENANT;

    /**
     * The table <code>public.obj_tenant_v</code>.
     */
    public static final ObjTenantV OBJ_TENANT_V = ObjTenantV.OBJ_TENANT_V;

    /**
     * The table <code>public.obj_user</code>.
     */
    public static final ObjUser OBJ_USER = ObjUser.OBJ_USER;

    /**
     * The table <code>public.obj_user_v</code>.
     */
    public static final ObjUserV OBJ_USER_V = ObjUserV.OBJ_USER_V;
}
