/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.task.model.db;


import io.zeitwert.fm.task.model.db.tables.CodeTaskPriority;
import io.zeitwert.fm.task.model.db.tables.DocTask;
import io.zeitwert.fm.task.model.db.tables.records.CodeTaskPriorityRecord;
import io.zeitwert.fm.task.model.db.tables.records.DocTaskRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CodeTaskPriorityRecord> CODE_TASK_PRIORITY_PKEY = Internal.createUniqueKey(CodeTaskPriority.CODE_TASK_PRIORITY, DSL.name("code_task_priority_pkey"), new TableField[] { CodeTaskPriority.CODE_TASK_PRIORITY.ID }, true);
    public static final UniqueKey<DocTaskRecord> DOC_TASK_PKEY = Internal.createUniqueKey(DocTask.DOC_TASK, DSL.name("doc_task_pkey"), new TableField[] { DocTask.DOC_TASK.DOC_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<DocTaskRecord, CodeTaskPriorityRecord> DOC_TASK__DOC_TASK_PRIORITY_ID_FKEY = Internal.createForeignKey(DocTask.DOC_TASK, DSL.name("doc_task_priority_id_fkey"), new TableField[] { DocTask.DOC_TASK.PRIORITY_ID }, Keys.CODE_TASK_PRIORITY_PKEY, new TableField[] { CodeTaskPriority.CODE_TASK_PRIORITY.ID }, true);
}
