/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.app.search.model.db.tables;


import io.zeitwert.app.search.model.db.Indexes;
import io.zeitwert.app.search.model.db.Keys;
import io.zeitwert.app.search.model.db.Public;
import io.zeitwert.app.search.model.db.tables.records.ItemSearchRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemSearch extends TableImpl<ItemSearchRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.item_search</code>
     */
    public static final ItemSearch ITEM_SEARCH = new ItemSearch();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemSearchRecord> getRecordType() {
        return ItemSearchRecord.class;
    }

    /**
     * The column <code>public.item_search.id</code>.
     */
    public final TableField<ItemSearchRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.item_search.item_type_id</code>.
     */
    public final TableField<ItemSearchRecord, String> ITEM_TYPE_ID = createField(DSL.name("item_type_id"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.item_search.item_id</code>.
     */
    public final TableField<ItemSearchRecord, Integer> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.item_search.a_simple</code>.
     */
    public final TableField<ItemSearchRecord, String> A_SIMPLE = createField(DSL.name("a_simple"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.item_search.b_german</code>.
     */
    public final TableField<ItemSearchRecord, String> B_GERMAN = createField(DSL.name("b_german"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.item_search.b_english</code>.
     */
    public final TableField<ItemSearchRecord, String> B_ENGLISH = createField(DSL.name("b_english"), SQLDataType.CLOB, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<ItemSearchRecord, Object> SEARCH_KEY = createField(DSL.name("search_key"), DefaultDataType.getDefaultDataType("\"pg_catalog\".\"tsvector\""), this, "");

    private ItemSearch(Name alias, Table<ItemSearchRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ItemSearch(Name alias, Table<ItemSearchRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.item_search</code> table reference
     */
    public ItemSearch(String alias) {
        this(DSL.name(alias), ITEM_SEARCH);
    }

    /**
     * Create an aliased <code>public.item_search</code> table reference
     */
    public ItemSearch(Name alias) {
        this(alias, ITEM_SEARCH);
    }

    /**
     * Create a <code>public.item_search</code> table reference
     */
    public ItemSearch() {
        this(DSL.name("item_search"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ITEM_SEARCH_KEY);
    }

    @Override
    public UniqueKey<ItemSearchRecord> getPrimaryKey() {
        return Keys.ITEM_SEARCH_PKEY;
    }

    @Override
    public ItemSearch as(String alias) {
        return new ItemSearch(DSL.name(alias), this);
    }

    @Override
    public ItemSearch as(Name alias) {
        return new ItemSearch(alias, this);
    }

    @Override
    public ItemSearch as(Table<?> alias) {
        return new ItemSearch(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemSearch rename(String name) {
        return new ItemSearch(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemSearch rename(Name name) {
        return new ItemSearch(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemSearch rename(Table<?> name) {
        return new ItemSearch(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemSearch where(Condition condition) {
        return new ItemSearch(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemSearch where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemSearch where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemSearch where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemSearch where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemSearch where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemSearch where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemSearch where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemSearch whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemSearch whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
