/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.account.model.db.tables.records;


import io.zeitwert.fm.account.model.db.tables.ObjAccount;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ObjAccountRecord extends UpdatableRecordImpl<ObjAccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.obj_account.obj_id</code>.
     */
    public void setObjId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.obj_account.obj_id</code>.
     */
    public Integer getObjId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.obj_account.tenant_id</code>.
     */
    public void setTenantId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.obj_account.tenant_id</code>.
     */
    public Integer getTenantId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.obj_account.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.obj_account.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.obj_account.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.obj_account.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.obj_account.account_type_id</code>.
     */
    public void setAccountTypeId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.obj_account.account_type_id</code>.
     */
    public String getAccountTypeId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.obj_account.client_segment_id</code>.
     */
    public void setClientSegmentId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.obj_account.client_segment_id</code>.
     */
    public String getClientSegmentId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.obj_account.main_contact_id</code>.
     */
    public void setMainContactId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.obj_account.main_contact_id</code>.
     */
    public Integer getMainContactId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.obj_account.reference_currency_id</code>.
     */
    public void setReferenceCurrencyId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.obj_account.reference_currency_id</code>.
     */
    public String getReferenceCurrencyId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.obj_account.logo_img_id</code>.
     */
    public void setLogoImgId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.obj_account.logo_img_id</code>.
     */
    public Integer getLogoImgId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.obj_account.inflation_rate</code>.
     */
    public void setInflationRate(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.obj_account.inflation_rate</code>.
     */
    public BigDecimal getInflationRate() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>public.obj_account.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.obj_account.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.obj_account.discount_rate</code>.
     */
    public void setDiscountRate(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.obj_account.discount_rate</code>.
     */
    public BigDecimal getDiscountRate() {
        return (BigDecimal) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ObjAccountRecord
     */
    public ObjAccountRecord() {
        super(ObjAccount.OBJ_ACCOUNT);
    }

    /**
     * Create a detached, initialised ObjAccountRecord
     */
    public ObjAccountRecord(Integer objId, Integer tenantId, String name, String description, String accountTypeId, String clientSegmentId, Integer mainContactId, String referenceCurrencyId, Integer logoImgId, BigDecimal inflationRate, Integer accountId, BigDecimal discountRate) {
        super(ObjAccount.OBJ_ACCOUNT);

        setObjId(objId);
        setTenantId(tenantId);
        setName(name);
        setDescription(description);
        setAccountTypeId(accountTypeId);
        setClientSegmentId(clientSegmentId);
        setMainContactId(mainContactId);
        setReferenceCurrencyId(referenceCurrencyId);
        setLogoImgId(logoImgId);
        setInflationRate(inflationRate);
        setAccountId(accountId);
        setDiscountRate(discountRate);
        resetChangedOnNotNull();
    }
}
