/*
 * This file is generated by jOOQ.
 */
package fm.comunas.fm.test.model.db;


import fm.comunas.fm.test.model.db.tables.DocTest;
import fm.comunas.fm.test.model.db.tables.DocTestPartNode;
import fm.comunas.fm.test.model.db.tables.DocTestV;
import fm.comunas.fm.test.model.db.tables.ObjTest;
import fm.comunas.fm.test.model.db.tables.ObjTestPartNode;
import fm.comunas.fm.test.model.db.tables.ObjTestV;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.doc_test</code>.
     */
    public final DocTest DOC_TEST = DocTest.DOC_TEST;

    /**
     * The table <code>public.doc_test_part_node</code>.
     */
    public final DocTestPartNode DOC_TEST_PART_NODE = DocTestPartNode.DOC_TEST_PART_NODE;

    /**
     * The table <code>public.doc_test_v</code>.
     */
    public final DocTestV DOC_TEST_V = DocTestV.DOC_TEST_V;

    /**
     * The table <code>public.obj_test</code>.
     */
    public final ObjTest OBJ_TEST = ObjTest.OBJ_TEST;

    /**
     * The table <code>public.obj_test_part_node</code>.
     */
    public final ObjTestPartNode OBJ_TEST_PART_NODE = ObjTestPartNode.OBJ_TEST_PART_NODE;

    /**
     * The table <code>public.obj_test_v</code>.
     */
    public final ObjTestV OBJ_TEST_V = ObjTestV.OBJ_TEST_V;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            DocTest.DOC_TEST,
            DocTestPartNode.DOC_TEST_PART_NODE,
            DocTestV.DOC_TEST_V,
            ObjTest.OBJ_TEST,
            ObjTestPartNode.OBJ_TEST_PART_NODE,
            ObjTestV.OBJ_TEST_V);
    }
}
