/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.app.doc.model.db.tables.records;


import io.zeitwert.app.doc.model.db.tables.CodeCaseStage;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeCaseStageRecord extends UpdatableRecordImpl<CodeCaseStageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.code_case_stage.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.code_case_stage.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.code_case_stage.case_def_id</code>.
     */
    public void setCaseDefId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.code_case_stage.case_def_id</code>.
     */
    public String getCaseDefId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.code_case_stage.seq_nr</code>.
     */
    public void setSeqNr(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.code_case_stage.seq_nr</code>.
     */
    public Integer getSeqNr() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.code_case_stage.case_stage_type_id</code>.
     */
    public void setCaseStageTypeId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.code_case_stage.case_stage_type_id</code>.
     */
    public String getCaseStageTypeId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.code_case_stage.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.code_case_stage.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.code_case_stage.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.code_case_stage.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.code_case_stage.due</code>.
     */
    public void setDue(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.code_case_stage.due</code>.
     */
    public Integer getDue() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.code_case_stage.action</code>.
     */
    public void setAction(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.code_case_stage.action</code>.
     */
    public String getAction() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.code_case_stage.abstract_case_stage_id</code>.
     */
    public void setAbstractCaseStageId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.code_case_stage.abstract_case_stage_id</code>.
     */
    public String getAbstractCaseStageId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.code_case_stage.available_actions</code>.
     */
    public void setAvailableActions(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.code_case_stage.available_actions</code>.
     */
    public String getAvailableActions() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CodeCaseStageRecord
     */
    public CodeCaseStageRecord() {
        super(CodeCaseStage.CODE_CASE_STAGE);
    }

    /**
     * Create a detached, initialised CodeCaseStageRecord
     */
    public CodeCaseStageRecord(String id, String caseDefId, Integer seqNr, String caseStageTypeId, String name, String description, Integer due, String action, String abstractCaseStageId, String availableActions) {
        super(CodeCaseStage.CODE_CASE_STAGE);

        setId(id);
        setCaseDefId(caseDefId);
        setSeqNr(seqNr);
        setCaseStageTypeId(caseStageTypeId);
        setName(name);
        setDescription(description);
        setDue(due);
        setAction(action);
        setAbstractCaseStageId(abstractCaseStageId);
        setAvailableActions(availableActions);
        resetChangedOnNotNull();
    }
}
