/*
 * This file is generated by jOOQ.
 */
package io.zeitwert.fm.dms.model.db.tables.records;


import io.zeitwert.fm.dms.model.db.tables.CodeDocumentKind;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeDocumentKindRecord extends UpdatableRecordImpl<CodeDocumentKindRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.code_document_kind.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.code_document_kind.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.code_document_kind.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.code_document_kind.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CodeDocumentKindRecord
     */
    public CodeDocumentKindRecord() {
        super(CodeDocumentKind.CODE_DOCUMENT_KIND);
    }

    /**
     * Create a detached, initialised CodeDocumentKindRecord
     */
    public CodeDocumentKindRecord(String id, String name) {
        super(CodeDocumentKind.CODE_DOCUMENT_KIND);

        setId(id);
        setName(name);
        resetChangedOnNotNull();
    }
}
